Repository holochain/holochain, pull requests merged in 2020-12, with the labels that each got.

#511 HostFnApi struct
  Cargo.lock
  crates/hdk/src/host_fn/emit_signal.rs
  crates/holochain/src/core/ribosome/host_fn.rs
  crates/holochain/src/core/ribosome/host_fn/agent_info.rs
  crates/holochain/src/core/ribosome/host_fn/call.rs
  crates/holochain/src/core/ribosome/host_fn/call_remote.rs
  crates/holochain/src/core/ribosome/host_fn/capability_grants.rs
  crates/holochain/src/core/ribosome/host_fn/delete_link.rs
  crates/holochain/src/core/ribosome/host_fn/emit_signal.rs
  crates/holochain/src/core/ribosome/host_fn/get_link_details.rs
  crates/holochain/src/core/ribosome/host_fn/get_links.rs
  crates/holochain/src/core/ribosome/host_fn/query.rs
  crates/holochain/src/core/ribosome/host_fn/sign.rs
  crates/holochain/src/core/ribosome/host_fn/sys_time.rs
  crates/holochain/src/core/ribosome/host_fn/verify_signature.rs
  crates/holochain/src/core/ribosome/host_fn/zome_info.rs
  crates/holochain/src/core/ribosome/wasm_ribosome.rs
  crates/holochain/src/core/signal.rs
  crates/holochain/src/core/state/cascade/network_tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/network_call_tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain/src/test_utils/conductor_setup.rs
  crates/holochain/src/test_utils/host_fn_api.rs
  crates/holochain/tests/websocket.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/zome_types/Cargo.toml
  crates/zome_types/src/lib.rs
  crates/zome_types/src/signal.rs
  crates/zome_types/src/zome_io.rs
Labels: please-one-approval

#523 test_utils/wasm: remove 'imports' leftover testcase
  crates/test_utils/wasm/src/lib.rs
Labels: bug, please-one-approval

#499 [TK-06088] Spike: Executing Network Topology Tests in Containernet
  containernet/.gitignore
  containernet/README.md
  containernet/Vagrantfile
  containernet/containernet-script.py
  containernet/guest_run.bash
  containernet/run-containernet.bash
Labels: please-one-approval

#527 condcutor/api_external: don't use unwrap_to in production code
  crates/holochain/src/conductor/api/api_external/app_interface.rs
Labels: tiny

#534 types/dna: only import InlineZome with test_utils feature
  crates/types/src/dna.rs
Labels: tiny

#521 TestConductorHandle to remove test boilerplate
  Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/api/api_external/app_interface.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/dna_store.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/conductor/p2p_store.rs
  crates/holochain/src/core/ribosome.rs
  crates/holochain/src/core/ribosome/host_fn/capability_grants.rs
  crates/holochain/src/core/state/cascade/authored_test.rs
  crates/holochain/src/core/state/cascade/network_tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/network_call_tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/produce_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain/src/local_network_tests.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/src/test_utils/conductor_setup.rs
  crates/holochain/src/test_utils/host_fn_caller.rs
  crates/holochain/src/test_utils/test_conductor.rs
  crates/holochain/src/test_utils/test_conductor/test_agents.rs
  crates/holochain/src/test_utils/test_conductor/test_cell.rs
  crates/holochain/src/test_utils/test_conductor/test_handle.rs
  crates/holochain/src/test_utils/test_conductor/test_set.rs
  crates/holochain/src/test_utils/test_conductor/test_zome.rs
  crates/holochain/tests/inline_zome_sketch.rs
  crates/holochain/tests/multi_conductor.rs
  crates/types/src/dna.rs
  crates/types/src/dna/zome/inline_zome.rs
  crates/zome_types/Cargo.toml
  crates/zome_types/src/entry_def.rs
Labels: please-one-approval

#518 [TK-06381] Many fixes to gossip and other parts of holochain
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/hdk/src/hash_path/anchor.rs
  crates/hdk/src/hash_path/path.rs
  crates/holochain/src/conductor.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/authority.rs
  crates/holochain/src/conductor/cell/gossip_test.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/core/ribosome/host_fn/delete.rs
  crates/holochain/src/core/ribosome/host_fn/delete_link.rs
  crates/holochain/src/core/ribosome/host_fn/get.rs
  crates/holochain/src/core/ribosome/host_fn/get_details.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/state/cascade/error.rs
  crates/holochain/src/core/state/cascade/network_tests.rs
  crates/holochain/src/core/state/element_buf.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/core/workflow/error.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/local_network_tests.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/src/test_utils/host_fn_caller.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/wire.rs
  crates/kitsune_p2p/proxy/src/inner_listen.rs
  crates/kitsune_p2p/proxy/src/tls_cli.rs
  crates/kitsune_p2p/proxy/src/tls_srv.rs
  crates/kitsune_p2p/proxy/src/tls_tests.rs
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/transport_quic/src/listener.rs
  crates/kitsune_p2p/transport_quic/src/test.rs
  crates/state/src/buffer/cas/buf_sync.rs
  crates/state/src/buffer/kv/buf.rs
  crates/test_utils/wasm/wasm_workspace/capability/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/crd/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/create_entry/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/crud/src/countree.rs
  crates/test_utils/wasm/wasm_workspace/multiple_calls/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/update_entry/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/validate_link/src/lib.rs
  crates/types/src/dna.rs
  crates/zome_types/src/entry.rs
Labels: please-two-approvals

#536 [TK-06441] Sort links, remove dup paths, fix shutdown issue
  crates/hdk/src/hash_path/path.rs
  crates/holochain/src/core/queue_consumer.rs
  crates/holochain/src/core/ribosome/host_fn/get_links.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/test_utils.rs
  crates/test_utils/wasm/wasm_workspace/link/src/lib.rs
  crates/types/src/dht_op.rs
Labels: please-one-approval

#541 shells/happDev: expose binaries based on a wrapper script around cargo
  README.md
  default.nix
  nix/pkgs/default.nix
  nix/pkgs/dev/core.nix
  nix/pkgs/dev/default.nix
  nix/pkgs/dev/happ.nix
  nix/shells.nix
Labels: please-one-approval

#517 [TK-06379] proxy stress test
  Cargo.lock
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/proxy/src/bin/proxy-stress.rs
Labels: please-one-approval

#522 [TK-06413] prune bad proxy addrs
  crates/kitsune_p2p/proxy/src/inner_listen.rs
Labels: please-one-approval

#543 Fix ZomeCall RibosomeError
  crates/holochain/src/conductor/api/api_external/app_interface.rs
Labels: tiny

#544 [TK-06471] tls persistance
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/tests/websocket.rs
  crates/holochain_p2p/src/spawn.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/test.rs
  crates/keystore/src/keystore_actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/lib.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_agent.rs
Labels: please-one-approval

#552 fix tls cert alg mismatch
  Cargo.lock
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/tests.rs
  crates/keystore/Cargo.toml
  crates/keystore/src/agent_pubkey_ext.rs
  crates/keystore/src/keystore_actor.rs
  crates/keystore/src/test_keystore.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/proxy/src/lib.rs
  crates/kitsune_p2p/transport_quic/Cargo.toml
Labels: please-one-approval

#546 [TK-06619] Remote signal
  CHANGELOG-UNRELEASED.md
  Cargo.lock
  Cargo.toml
  crates/dna_util/Cargo.toml
  crates/fixt/Cargo.toml
  crates/hdk/Cargo.toml
  crates/hdk/src/host_fn.rs
  crates/hdk/src/host_fn/emit_signal.rs
  crates/hdk/src/host_fn/remote_signal.rs
  crates/hdk/src/prelude.rs
  crates/holo_hash/Cargo.toml
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/interface.rs
  crates/holochain/src/core/ribosome/host_fn.rs
  crates/holochain/src/core/ribosome/host_fn/remote_signal.rs
  crates/holochain/src/core/ribosome/real_ribosome.rs
  crates/holochain/src/test_utils/test_conductor/test_handle.rs
  crates/holochain/tests/websocket.rs
  crates/holochain_p2p/Cargo.toml
  crates/keystore/Cargo.toml
  crates/state/Cargo.toml
  crates/state/src/test_utils.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/emit_signal/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/random_bytes/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/sign/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/update_entry/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/validate_link/src/lib.rs
  crates/test_utils/wasm_common/Cargo.toml
  crates/types/Cargo.toml
  crates/websocket/Cargo.toml
  crates/zome_types/Cargo.toml
  crates/zome_types/src/fixt.rs
  crates/zome_types/src/prelude.rs
  crates/zome_types/src/signal.rs
  crates/zome_types/src/zome_io.rs
Labels: please-two-approvals

#567 [TK-06834] Fix conductor is stuck at 31 read handles and deadlocks
  Cargo.toml
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/test.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/p2p_store.rs
  crates/holochain/src/core/queue_consumer.rs
  crates/holochain/src/test_utils/conductor_setup.rs
  crates/holochain/tests/agent_scaling.rs
  crates/holochain_zome_types/src/zome_io.rs
  crates/test_utils/wasm/wasm_workspace/multiple_calls/src/lib.rs
Labels: please-one-approval
