Repository holochain/holochain, pull requests merged in 2020-09, with the labels that each got.

#357 [TK-04770] QUIC Transport Fixes
  Cargo.lock
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/transport_quic/src/connection.rs
  crates/kitsune_p2p/transport_quic/src/listener.rs
  crates/kitsune_p2p/transport_quic/src/test.rs
  crates/kitsune_p2p/types/src/lib.rs
Labels: please-one-approval

#346 [TK-04484] remove list agent keys in favor of list cell ids
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
Labels: please-one-approval

#319 [TK-04484] Implement Lair Keystore & Lair Test Keystore
  Cargo.lock
  crates/hdk/src/map_extern.rs
  crates/holo_hash/src/fixt.rs
  crates/holochain/src/conductor.rs
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
  crates/holochain/src/conductor/compat.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/config.rs
  crates/holochain/src/conductor/error.rs
  crates/holochain/src/core/ribosome/host_fn/create.rs
  crates/holochain/src/core/state/element_buf.rs
  crates/holochain/src/core/state/validation_receipts_db.rs
  crates/holochain/src/fixt.rs
  crates/holochain/tests/websocket.rs
  crates/keystore/Cargo.toml
  crates/keystore/src/error.rs
  crates/keystore/src/keystore_actor.rs
  crates/keystore/src/lair_keystore.rs
  crates/keystore/src/lib.rs
  crates/keystore/src/test_keystore.rs
  crates/state/src/test_utils.rs
  crates/zome_types/src/test_utils.rs
Labels: please-two-approvals

#360 HolochainP2pCell mock
  Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/test.rs
  crates/holochain/src/conductor/compat.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/core/ribosome.rs
  crates/holochain/src/core/ribosome/host_fn/call_remote.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/state/metadata.rs
  crates/holochain/src/core/sys_validate/present.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain_p2p/Cargo.toml
  crates/holochain_p2p/src/lib.rs
  crates/holochain_p2p/src/mock.rs
  crates/types/Cargo.toml
Labels: please-one-approval

#364 [D-01143] Trigger race fix
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/core/queue_consumer.rs
  crates/holochain/src/core/queue_consumer/app_validation_consumer.rs
  crates/holochain/src/core/queue_consumer/integrate_dht_ops_consumer.rs
  crates/holochain/src/core/queue_consumer/produce_dht_ops_consumer.rs
  crates/holochain/src/core/queue_consumer/publish_dht_ops_consumer.rs
  crates/holochain/src/core/queue_consumer/sys_validation_consumer.rs
  crates/holochain/src/core/state/chain_sequence.rs
Labels: please-one-approval

#368 [TK-04864, TK-04865] Kitsune Transport Channels
  Cargo.lock
  crates/kitsune_p2p/transport_quic/src/connection.rs
  crates/kitsune_p2p/transport_quic/src/test.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/lib.rs
  crates/kitsune_p2p/types/src/transport.rs
  crates/kitsune_p2p/types/src/transport_mem.rs
Labels: please-one-approval

#370 [TK-02498 TK-02499] kitsune proxy wire protocol
  Cargo.lock
  Cargo.toml
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/proxy/src/lib.rs
  crates/kitsune_p2p/proxy/src/wire.rs
Labels: please-two-approvals

#373 [TK-04948] Kitsune Proxy URL Utility
  Cargo.lock
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/proxy/src/lib.rs
  crates/kitsune_p2p/proxy/src/proxy_url.rs
  crates/kitsune_p2p/proxy/src/wire.rs
Labels: please-one-approval

#380 Fix flaky tests
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain/src/test_utils.rs
Labels: please-one-approval

#377 [TK-05022] make retrieve raw and add all dbs to cascade
  crates/holochain/src/core/state/cascade.rs
Labels: please-one-approval

#379 [TK-05023] Integration waits for holding deps
  crates/holochain/src/core/workflow/error.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: please-one-approval

#381 [TK-05024][TK-05025] drop counterfeit and hold to incoming
  crates/holochain/src/core/queue_consumer/sys_validation_consumer.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/sys_validate/error.rs
  crates/holochain/src/core/sys_validate/present.rs
  crates/holochain/src/core/sys_validate/tests.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow/test.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/types.rs
  crates/state/src/env.rs
  crates/types/src/dht_op.rs
Labels: please-one-approval

#385 [TK-05021] Check for chain rollback
  Cargo.lock
  crates/holo_hash/src/hash.rs
  crates/holo_hash/src/hash_ext.rs
  crates/holochain/Cargo.toml
  crates/holochain/src/core/state/metadata.rs
  crates/holochain/src/core/state/metadata/chain_test.rs
  crates/holochain/src/core/state/metadata/keys.rs
  crates/holochain/src/core/state/metadata/keys/misc.rs
  crates/holochain/src/core/state/metadata/mock.rs
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/sys_validate/present.rs
  crates/holochain/src/core/sys_validate/tests.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/disintegrate.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/chain_test.rs
  crates/holochain/src/test_utils.rs
Labels: merge base pr first, please-one-approval

#386 [TK-05026] The Great Simplification
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/state/element_buf.rs
  crates/holochain/src/core/state/metadata.rs
  crates/holochain/src/core/state/validation_db.rs
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/sys_validate/present.rs
  crates/holochain/src/core/sys_validate/tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/produce_dht_ops_workflow/dht_op_light.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/types.rs
  crates/holochain_p2p/src/mock.rs
  crates/state/src/key/prefix.rs
Labels: merge base pr first, please-one-approval
