Repository holochain/holochain, pull requests merged in 2020-11, with the labels that each got.

#450 [D-01159] Patch tokio safe block on
  Cargo.lock
  Cargo.toml
  crates/holochain/src/core/ribosome/host_fn/hash_entry.rs
Labels: please-one-approval

#437 Adds the hash of the create link to links
  CHANGELOG-UNRELEASED.md
  crates/holochain/src/core/ribosome/host_fn/delete_link.rs
  crates/holochain/src/core/state/cascade/network_tests.rs
  crates/holochain/src/core/state/metadata/keys.rs
  crates/test_utils/wasm/wasm_workspace/link/src/lib.rs
  crates/zome_types/src/link.rs
Labels: please-one-approval, tiny

#455 [TK-05724] Generate AgentInfoSigned on kitsune join & store in agent_store
  Cargo.lock
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/test.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/core/ribosome.rs
  crates/holochain/src/core/ribosome/guest_callback/validate.rs
  crates/holochain/src/core/state/cascade/network_tests.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/tests/websocket.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_agent.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_event.rs
Labels: please-one-approval

#465 Don't wait for closing network
  crates/holochain/src/conductor/cell/test.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/core/ribosome.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/tests/cascade.rs
  crates/holochain_p2p/src/lib.rs
  crates/holochain_p2p/src/test.rs
Labels: bug, please-one-approval

#453 Call
  CHANGELOG-UNRELEASED.md
  crates/hdk/src/error.rs
  crates/hdk/src/host_fn/call.rs
  crates/hdk/src/prelude.rs
  crates/holochain/src/conductor/api/api_cell.rs
  crates/holochain/src/conductor/api/mock.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/core/ribosome.rs
  crates/holochain/src/core/ribosome/error.rs
  crates/holochain/src/core/ribosome/host_fn/call.rs
  crates/holochain/src/core/ribosome/host_fn/create.rs
  crates/holochain/src/core/workflow/app_validation_workflow/network_call_tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/core/workflow/call_zome_workflow/validation_test.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/chain_test.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain/src/fixt.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/src/test_utils/conductor_setup.rs
  crates/holochain/src/test_utils/host_fn_api.rs
  crates/holochain/tests/gossip_test.rs
  crates/test_utils/wasm/wasm_workspace/create_entry/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/whoami/src/lib.rs
  crates/types/src/cell.rs
  crates/zome_types/src/call.rs
  crates/zome_types/src/cell.rs
  crates/zome_types/src/lib.rs
  crates/zome_types/src/zome_io.rs
Labels: please-one-approval

#444 [B-03467] Get agent activity host fn
  Cargo.lock
  Cargo.toml
  crates/hdk/Cargo.toml
  crates/hdk/src/host_fn.rs
  crates/hdk/src/host_fn/get_agent_activity.rs
  crates/hdk/src/prelude.rs
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/authority.rs
  crates/holochain/src/core/ribosome/host_fn.rs
  crates/holochain/src/core/ribosome/host_fn/get_agent_activity.rs
  crates/holochain/src/core/ribosome/wasm_ribosome.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/state/metadata.rs
  crates/holochain/src/core/state/metadata/chain_test.rs
  crates/holochain/src/core/state/metadata/keys.rs
  crates/holochain/src/core/state/metadata/mock.rs
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/app_validation_workflow/network_call_tests.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/disintegrate.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/test_utils/host_fn_api.rs
  crates/holochain_p2p/src/lib.rs
  crates/holochain_p2p/src/types/event.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/create_entry/src/lib.rs
  crates/test_utils/wasm_common/src/common.rs
  crates/types/src/activity.rs
  crates/types/src/chain.rs
  crates/types/src/lib.rs
  crates/zome_types/src/lib.rs
  crates/zome_types/src/query.rs
  crates/zome_types/src/validate.rs
  crates/zome_types/src/warrant.rs
  crates/zome_types/src/zome_io.rs
Labels: please-two-approvals

#459 Use a Vec of 39 bytes for HoloHash serialization
  CHANGELOG-UNRELEASED.md
  crates/dna_util/src/lib.rs
  crates/holo_hash/README.md
  crates/holo_hash/src/encode.rs
  crates/holo_hash/src/encode_raw.rs
  crates/holo_hash/src/error.rs
  crates/holo_hash/src/fixt.rs
  crates/holo_hash/src/hash.rs
  crates/holo_hash/src/hash_ext.rs
  crates/holo_hash/src/hash_type.rs
  crates/holo_hash/src/hash_type/composite.rs
  crates/holo_hash/src/hash_type/primitive.rs
  crates/holo_hash/src/hashable_content.rs
  crates/holo_hash/src/ser.rs
  crates/holo_hash/src/tests.rs
  crates/holochain/src/core/ribosome/host_fn/get_links.rs
  crates/holochain/src/core/ribosome/host_fn/hash_entry.rs
  crates/holochain/src/core/ribosome/wasm_ribosome.rs
  crates/holochain/src/core/state/chain_sequence.rs
  crates/holochain/src/core/state/dht_op_integration.rs
  crates/holochain/src/core/state/metadata/keys.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/produce_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain_p2p/src/fixt.rs
  crates/holochain_p2p/src/test.rs
  crates/holochain_p2p/src/types.rs
  crates/keystore/src/agent_pubkey_ext.rs
  crates/keystore/src/keystore_actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_agent.rs
  crates/kitsune_p2p/kitsune_p2p/src/types.rs
  crates/state/src/buffer/cas/buf_async.rs
  crates/state/src/buffer/cas/buf_sync.rs
  crates/state/src/key.rs
  crates/state/src/key/prefix.rs
  crates/test_utils/wasm/wasm_workspace/post_commit_fail/src/lib.rs
  crates/types/src/dna.rs
  crates/types/src/dna/error.rs
  crates/types/src/test_utils.rs
  crates/zome_types/src/entry.rs
  crates/zome_types/src/test_utils.rs
Labels: please-one-approval

#466 TK-05758 TK-05863 push to bootstrap
  Cargo.lock
  crates/fixt/src/bytes.rs
  crates/fixt/src/prelude.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/error.rs
  crates/holochain/src/conductor/p2p_store.rs
  crates/holochain_p2p/Cargo.toml
  crates/holochain_p2p/src/lib.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/fixt.rs
  crates/kitsune_p2p/kitsune_p2p/src/lib.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/bootstrap.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/types.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/agent_store.rs
  crates/state/src/error.rs
  crates/test_utils/wasm/wasm_workspace/capability/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/crud/src/countree.rs
  crates/test_utils/wasm/wasm_workspace/foo/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/imports/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/multiple_calls/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/sign/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/update_entry/src/lib.rs
  test/default.nix
Labels: please-one-approval

#456 [TK-05725] Kitsune Peer Gossip
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/gossip_test.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/src/test_utils/conductor_setup.rs
  crates/holochain/tests/gossip_test.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/types/event.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_agent.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/agent_store.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/event.rs
Labels: please-one-approval

#462 [B-03501] get details returns rejected
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/authority.rs
  crates/holochain/src/conductor/cell/error.rs
  crates/holochain/src/core/ribosome/host_fn/capability_grants.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/state/cascade/network_tests.rs
  crates/holochain/src/core/state/metadata.rs
  crates/holochain/src/core/state/metadata/keys.rs
  crates/holochain/src/core/state/metadata/keys/misc.rs
  crates/holochain/src/core/state/metadata/mock.rs
  crates/holochain/src/core/state/metadata/status.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/test_ideas.rs
  crates/holochain_p2p/src/test.rs
  crates/types/src/element.rs
  crates/types/src/header.rs
  crates/types/src/header/error.rs
  crates/zome_types/src/metadata.rs
  crates/zome_types/src/validate.rs
Labels: please-one-approval

#457 [TK-05808] Kitsune Use Transports
  Cargo.lock
  crates/holochain/src/test_utils.rs
  crates/holochain_p2p/Cargo.toml
  crates/holochain_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_agent.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/wire.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/codec.rs
Labels: please-one-approval

#471 Adds a test that ensures that HoloHash serializes to a raw byte array
  crates/holo_hash/src/hash.rs
  crates/holo_hash/src/ser.rs
Labels: please-one-approval, tiny

#472 [TK-05873] Kitsune gossip transports
  crates/holochain/src/test_utils.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/types.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/agent_store.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/wire.rs
Labels: please-one-approval

#476 TK-05986 TK-05987 2020 11 11 bootstrap config
  crates/holochain/src/conductor/config.rs
  crates/kitsune_p2p/kitsune_p2p/src/config.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/bootstrap.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  test/default.nix
Labels: please-one-approval

#473 [TK-05803 TK-05805] Kitsune Peer Discovery for rpc_single (multi request/notify to follow)
  crates/holochain_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/bootstrap.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/wire.rs
Labels: please-one-approval

#480 Clarify doc for AppInfo
  crates/holochain/src/conductor/api/api_external/app_interface.rs
Labels: tiny

#483 TK-05988 fix bad sig
  crates/holochain/src/conductor/cell/gossip_test.rs
  crates/holochain/src/conductor/handle.rs
  crates/kitsune_p2p/kitsune_p2p/src/config.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/bootstrap.rs
Labels: please-one-approval

#484 TK-05775 2020 11 15 bootstrap docs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/bootstrap.rs
Labels: please-one-approval

#485 bump thiserror
  crates/dna_util/Cargo.toml
  crates/holochain/Cargo.toml
  crates/holochain_p2p/Cargo.toml
  crates/keystore/Cargo.toml
  crates/observability/Cargo.toml
  crates/state/Cargo.toml
  crates/zome_types/Cargo.toml
Labels: please-one-approval

#482 [TK-05788 TK-05804 TK-05806 TK-05807] Kitsune Peer Discover Multi
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/p2p_store.rs
  crates/holochain_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/bootstrap.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/types.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/wire.rs
  crates/kitsune_p2p/proxy/src/wire.rs
  crates/kitsune_p2p/types/src/codec.rs
Labels: please-one-approval

#492 Disable mac builds which always fail
  .circleci/config.yml
Labels: please-two-approvals

#495 [TK-06119] add cert gen / use from file to kitsune proxy binary
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-proxy/main.rs
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-proxy/opt.rs
Labels: please-one-approval

#481 Get links scaling bug
  Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/gossip_test.rs
  crates/holochain/src/conductor/cell/test.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/entry_def_store.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/core/ribosome.rs
  crates/holochain/src/core/ribosome/host_fn/call.rs
  crates/holochain/src/core/ribosome/wasm_ribosome.rs
  crates/holochain/src/core/state/cascade/authored_test.rs
  crates/holochain/src/core/sys_validate/tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/network_call_tests.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow/test.rs
  crates/holochain/src/lib.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/src/test_utils/conductor_setup.rs
  crates/holochain/src/test_utils/host_fn_api.rs
  crates/holochain/tests/agent_scaling.rs
  crates/holochain/tests/ser_regression.rs
  crates/holochain/tests/speed_tests.rs
  crates/state/Cargo.toml
  crates/state/src/db.rs
  crates/state/src/env.rs
  crates/state/src/lib.rs
  crates/state/src/test_utils.rs
Labels: please-one-approval

#498 Put host fns directly on CallData
  crates/holochain/src/core/state/cascade/authored_test.rs
  crates/holochain/src/core/state/cascade/network_tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/network_call_tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/call_zome_workflow/call_zome_workspace_lock.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain/src/test_utils/conductor_setup.rs
  crates/holochain/src/test_utils/host_fn_api.rs
  crates/holochain/tests/agent_scaling.rs
  crates/state/src/env.rs
Labels: please-one-approval

#474 [B-03577] tracing across channels and process boundaries
  Cargo.lock
  Cargo.toml
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/tests/speed_tests.rs
  crates/holochain_p2p/Cargo.toml
  crates/keystore/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util.rs
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/types/Cargo.toml
  crates/observability/Cargo.toml
  crates/observability/README.md
  crates/observability/src/flames.rs
  crates/observability/src/fmt.rs
  crates/observability/src/lib.rs
  crates/types/Cargo.toml
Labels: please-one-approval

#486 TK-06037 bump upstream wasmer and remove host_externs!
  Cargo.lock
  crates/hdk/Cargo.toml
  crates/hdk/src/entry/create_entry.rs
  crates/hdk/src/host_fn/create.rs
  crates/hdk/src/host_fn/create_link.rs
  crates/hdk/src/host_fn/delete.rs
  crates/hdk/src/host_fn/delete_link.rs
  crates/hdk/src/host_fn/hash_entry.rs
  crates/hdk/src/host_fn/sign.rs
  crates/hdk/src/host_fn/update.rs
  crates/hdk/src/host_fn/verify_signature.rs
  crates/holochain/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: please-one-approval

#487 TK-06058 make debug infallible in hdk
  crates/hdk/README.md
  crates/hdk/src/host_fn/debug.rs
  crates/test_utils/wasm/wasm_workspace/debug/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/multiple_calls/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/ser_regression/src/lib.rs
Labels: please-one-approval

#490 [TK-06141][TK-06089] inject agent info and local network tests
  .gitignore
  crates/hdk/src/error.rs
  crates/hdk/src/host_fn/call.rs
  crates/hdk/src/host_fn/call_remote.rs
  crates/holochain/src/conductor/api/api_external/app_interface.rs
  crates/holochain/src/conductor/p2p_store.rs
  crates/holochain/src/core/ribosome.rs
  crates/holochain/src/core/ribosome/host_fn/call_remote.rs
  crates/holochain/src/lib.rs
  crates/holochain/src/local_network_tests.rs
  crates/holochain_p2p/src/types.rs
  crates/test_utils/wasm/wasm_workspace/create_entry/src/lib.rs
  crates/zome_types/src/zome_io.rs
Labels: please-one-approval

#497 It is an error to install the same app id twice
  CHANGELOG-UNRELEASED.md
  Cargo.lock
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
  crates/holochain/src/conductor/api/api_external/app_interface.rs
  crates/holochain/src/conductor/api/api_external/signal_subscription.rs
  crates/holochain/src/conductor/compat.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/error.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/conductor/state.rs
  crates/holochain/tests/websocket.rs
  crates/types/src/app.rs
Labels: please-one-approval

#502 TK-06149 hdk references
  Cargo.lock
  crates/hdk/Cargo.toml
  crates/hdk/README.md
  crates/hdk/src/host_fn.rs
  crates/hdk/src/host_fn/agent_info.rs
  crates/hdk/src/host_fn/call.rs
  crates/hdk/src/host_fn/call_remote.rs
  crates/hdk/src/host_fn/create.rs
  crates/hdk/src/host_fn/create_link.rs
  crates/hdk/src/host_fn/debug.rs
  crates/hdk/src/host_fn/delete.rs
  crates/hdk/src/host_fn/delete_link.rs
  crates/hdk/src/host_fn/emit_signal.rs
  crates/hdk/src/host_fn/get.rs
  crates/hdk/src/host_fn/get_agent_activity.rs
  crates/hdk/src/host_fn/get_details.rs
  crates/hdk/src/host_fn/get_link_details.rs
  crates/hdk/src/host_fn/get_links.rs
  crates/hdk/src/host_fn/hash_entry.rs
  crates/hdk/src/host_fn/query.rs
  crates/hdk/src/host_fn/random_bytes.rs
  crates/hdk/src/host_fn/sign.rs
  crates/hdk/src/host_fn/sys_time.rs
  crates/hdk/src/host_fn/update.rs
  crates/hdk/src/host_fn/verify_signature.rs
  crates/hdk/src/host_fn/zome_info.rs
  crates/hdk/src/prelude.rs
  crates/holochain/Cargo.toml
  crates/holochain/src/core/ribosome/host_fn/debug.rs
  crates/holochain/src/core/ribosome/host_fn/sign.rs
  crates/holochain/src/core/ribosome/host_fn/verify_signature.rs
  crates/keystore/src/agent_pubkey_ext.rs
  crates/keystore/src/keystore_actor.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/imports/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/imports/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/imports/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/sign/src/lib.rs
  crates/zome_types/src/signature.rs
  crates/zome_types/src/zome_io.rs
Labels: please-one-approval

#505 Update nix command to use --no-default-features
  crates/hdk/src/guest_callback/entry_defs.rs
  default.nix
Labels: please-one-approval, tiny

#489 TK-06029 mod based extern mapping
  Cargo.lock
  crates/fixt/Cargo.toml
  crates/fixt/test/Cargo.toml
  crates/hdk/Cargo.toml
  crates/hdk/src/lib.rs
  crates/hdk/src/map_extern.rs
  crates/hdk_derive/Cargo.toml
  crates/hdk_derive/src/lib.rs
  crates/holochain/src/core/ribosome/wasm_ribosome.rs
  crates/holochain/src/local_network_tests.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/test_utils/wasm/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/create_entry/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/hdk_extern/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/hdk_extern/src/lib.rs
Labels: please-two-approvals

#504 Remove everything to do with legacy tryorama config
  Cargo.lock
  Cargo.toml
  crates/diagnostics/Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain/src/bin/holochain/main.rs
  crates/holochain/src/conductor.rs
  crates/holochain/src/conductor/compat.rs
  crates/holochain/src/conductor/config.rs
  crates/legacy/Cargo.toml
  crates/legacy/src/config.rs
  crates/legacy/src/lib.rs
  test/default.nix
Labels: please-one-approval

#506 README change: TOML config file to YAML
  README.md
Labels: documentation, please-one-approval, tiny

#501 [TK-06090] Admin peer peer inject
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/conductor/p2p_store.rs
  crates/zome_types/src/zome_io.rs
Labels: please-one-approval
