Repository holochain/holochain, pull requests merged in 2020-10, with the labels that each got.

#383 Test that Responses only go to the WS connection that made the Request
  crates/holochain/tests/websocket.rs
Labels: please-one-approval

#393 Small updates
  crates/hdk/src/host_fn/emit_signal.rs
  crates/holochain/src/core/ribosome.rs
Labels: please-one-approval

#391 2020 09 28 peer db
  Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor.rs
  crates/holochain/src/conductor/p2p_store.rs
  crates/holochain_p2p/src/lib.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/fixt.rs
  crates/kitsune_p2p/kitsune_p2p/src/lib.rs
  crates/kitsune_p2p/kitsune_p2p/src/types.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/agent_store.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/state/src/buffer/kv/kv_store.rs
  crates/state/src/db.rs
  crates/state/src/env.rs
  crates/state/src/test_utils.rs
  crates/websocket/Cargo.toml
Labels: please-two-approvals

#390 get_details and get_link_details return SignedHeaderHashed and ZomeInfo includes ZomeId
  CHANGELOG-UNRELEASED.md
  crates/holochain/src/core/ribosome/host_fn/get_link_details.rs
  crates/holochain/src/core/ribosome/host_fn/zome_info.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/state/cascade/network_tests.rs
  crates/holochain/src/test_utils/host_fn_api.rs
  crates/zome_types/src/link.rs
  crates/zome_types/src/metadata.rs
  crates/zome_types/src/zome_info.rs
Labels: please-one-approval

#395 Fix binary heaps
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
Labels: please-one-approval, tiny

#388 [TK-05156] entry_def_id style callback and sorted app validation
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/entry_def_store.rs
  crates/holochain/src/core/ribosome/guest_callback/validate.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/app_validation_workflow/error.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain/src/fixt.rs
  crates/holochain/src/test_utils/host_fn_api.rs
  crates/test_utils/wasm/wasm_workspace/create_entry/src/lib.rs
Labels: changes resolved, merge base pr first, please-one-approval

#344 [TK-04399] Validation Package ground work
  CHANGELOG-UNRELEASED.md
  crates/hdk/src/hash_path/path.rs
  crates/hdk/src/prelude.rs
  crates/hdk_derive/src/lib.rs
  crates/holochain/src/conductor/cell/validation_package.rs
  crates/holochain/src/conductor/entry_def_store.rs
  crates/holochain/src/core/ribosome/guest_callback/entry_defs.rs
  crates/holochain/src/core/ribosome/guest_callback/validate.rs
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/fixt.rs
  crates/test_utils/wasm/wasm_workspace/create_entry/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/validate/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/validate_invalid/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/validate_link/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/validate_valid/src/lib.rs
  crates/types/src/fixt.rs
  crates/zome_types/src/entry_def.rs
  crates/zome_types/src/fixt.rs
  crates/zome_types/src/validate.rs
Labels: merge base pr first, please-one-approval

#392 [B-03149] direct sys validation
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/core/state/element_buf.rs
  crates/holochain/src/core/state/metadata.rs
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/sys_validate/error.rs
  crates/holochain/src/core/sys_validate/tests.rs
  crates/holochain/src/core/validation.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/core/workflow/call_zome_workflow/validation_test.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/lib.rs
  crates/holochain/src/test_utils.rs
  crates/state/src/buffer/cas/buf_sync.rs
  crates/state/src/buffer/kv/buf.rs
  crates/state/src/buffer/kvv/buf.rs
  crates/test_utils/wasm/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/update_entry/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/update_entry/src/lib.rs
Labels: please-two-approvals

#396 [TK-05206] Write the direct zome call cache
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
Labels: merge base pr first, please-one-approval

#394 [TK-05217] add authored prefix
  crates/holochain/src/core/ribosome/host_fn/create.rs
  crates/holochain/src/core/ribosome/host_fn/create_link.rs
  crates/holochain/src/core/ribosome/host_fn/delete.rs
  crates/holochain/src/core/ribosome/host_fn/delete_link.rs
  crates/holochain/src/core/ribosome/host_fn/get_details.rs
  crates/holochain/src/core/ribosome/host_fn/update.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/state/cascade/authored_test.rs
  crates/holochain/src/core/state/cascade/network_tests.rs
  crates/holochain/src/core/state/element_buf.rs
  crates/holochain/src/core/state/metadata.rs
  crates/holochain/src/core/state/source_chain/source_chain_buffer.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/src/test_utils/conductor_setup.rs
  crates/holochain/tests/cascade.rs
  crates/state/src/key/prefix.rs
Labels: please-one-approval

#399 [TK-05226] Get validation package
  crates/fixt/src/bytes.rs
  crates/fixt/src/prelude.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/error.rs
  crates/holochain/src/conductor/cell/validation_package.rs
  crates/holochain/src/conductor/entry_def_store.rs
  crates/holochain/src/core/ribosome/guest_callback/validation_package.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/app_validation_workflow/error.rs
  crates/holochain/src/core/workflow/app_validation_workflow/network_call_tests.rs
  crates/holochain_p2p/src/lib.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/types/actor.rs
  crates/holochain_p2p/src/types/event.rs
  crates/holochain_p2p/src/types/wire.rs
  crates/kitsune_p2p/kitsune_p2p/src/fixt.rs
  crates/test_utils/wasm/wasm_workspace/create_entry/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/validation_package_success/src/lib.rs
  crates/types/src/validate.rs
  crates/zome_types/src/header.rs
  crates/zome_types/src/query.rs
  crates/zome_types/src/validate.rs
Labels: please-one-approval

#400 [TK-05277] Kitsune transport api updates / prep for proxy
  Cargo.lock
  crates/keystore/Cargo.toml
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/transport_quic/src/connection.rs
  crates/kitsune_p2p/transport_quic/src/lib.rs
  crates/kitsune_p2p/transport_quic/src/listener.rs
  crates/kitsune_p2p/transport_quic/src/test.rs
  crates/kitsune_p2p/types/src/transport.rs
  crates/kitsune_p2p/types/src/transport_mem.rs
Labels: please-one-approval

#401 [TK-05279] Update kitsune utilities prep for proxy
  crates/kitsune_p2p/proxy/src/lib.rs
  crates/kitsune_p2p/proxy/src/proxy_url.rs
  crates/kitsune_p2p/proxy/src/wire.rs
  crates/kitsune_p2p/types/src/auto_stream_select.rs
  crates/kitsune_p2p/types/src/lib.rs
Labels: merge base pr first, please-one-approval

#405 [TK-05280] Proxy Config + TLS Encryption
  Cargo.lock
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/proxy/src/config.rs
  crates/kitsune_p2p/proxy/src/lib.rs
  crates/kitsune_p2p/proxy/src/tls_cli.rs
  crates/kitsune_p2p/proxy/src/tls_srv.rs
  crates/kitsune_p2p/proxy/src/tls_tests.rs
Labels: merge base pr first, please-one-approval

#416 Create LMDB env dir if does not exist at startup
  README.md
  crates/holochain/src/bin/holochain/main.rs
  crates/holochain/src/conductor/interactive.rs
Labels: tiny

#410 2020 10 05 kitsune store event
  Cargo.lock
  crates/fixt/src/bytes.rs
  crates/fixt/src/prelude.rs
  crates/holo_hash/src/fixt.rs
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/entry_def_store.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/conductor/p2p_store.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/tests/ser_regression.rs
  crates/holochain/tests/speed_tests.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/types/event.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/fixt.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/agent_store.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/event.rs
  crates/state/src/db.rs
Labels: please-one-approval

#414 custom val package
  crates/hdk_derive/src/lib.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/validation_package.rs
  crates/holochain/src/core/ribosome.rs
  crates/holochain/src/core/ribosome/guest_callback/validation_package.rs
  crates/holochain/src/core/ribosome/host_fn/agent_info.rs
  crates/holochain/src/core/ribosome/host_fn/create.rs
  crates/holochain/src/core/ribosome/host_fn/create_link.rs
  crates/holochain/src/core/ribosome/host_fn/get.rs
  crates/holochain/src/core/ribosome/host_fn/get_links.rs
  crates/holochain/src/core/ribosome/host_fn/zome_info.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/state/metadata.rs
  crates/holochain/src/core/state/metadata/keys.rs
  crates/holochain/src/core/state/metadata/mock.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/app_validation_workflow/network_call_tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/types.rs
  crates/holochain/src/fixt.rs
  crates/test_utils/wasm/wasm_workspace/multiple_calls/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/validation_package_success/src/lib.rs
  crates/zome_types/src/validate.rs
Labels: WIP, merge base pr first

#417 Make fixturator use a seeded rng to enable solving flaky tests
  Cargo.lock
  crates/fixt/Cargo.toml
  crates/fixt/src/bool.rs
  crates/fixt/src/bytes.rs
  crates/fixt/src/lib.rs
  crates/fixt/src/number.rs
  crates/fixt/src/rng.rs
  crates/fixt/src/serialized_bytes.rs
  crates/fixt/src/string.rs
  crates/holochain/Cargo.toml
  crates/holochain/src/core/ribosome/guest_callback/entry_defs.rs
  crates/holochain/src/core/ribosome/guest_callback/init.rs
  crates/holochain/src/core/ribosome/guest_callback/migrate_agent.rs
  crates/holochain/src/core/ribosome/guest_callback/post_commit.rs
  crates/holochain/src/core/ribosome/guest_callback/validate.rs
  crates/holochain/src/core/ribosome/guest_callback/validate_link.rs
  crates/holochain/src/core/ribosome/guest_callback/validation_package.rs
  crates/kitsune_p2p/kitsune_p2p/src/fixt.rs
  crates/state/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/types/src/fixt.rs
Labels: please-two-approvals

#374 [TK-05281] Kitsune Functional Proxy Tunnel
  crates/kitsune_p2p/proxy/src/inner_listen.rs
  crates/kitsune_p2p/proxy/src/lib.rs
  crates/kitsune_p2p/proxy/src/wire_read.rs
  crates/kitsune_p2p/proxy/src/wire_write.rs
  crates/kitsune_p2p/proxy/tests/proxy_integration.rs
Labels: please-one-approval

#404 [TK-05245] Get agent activity
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/authority.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/workflow/app_validation_workflow/network_call_tests.rs
  crates/holochain/src/test_utils/conductor_setup.rs
  crates/holochain_p2p/src/lib.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/types/actor.rs
  crates/holochain_p2p/src/types/event.rs
  crates/holochain_p2p/src/types/wire.rs
  crates/types/src/chain.rs
  crates/types/src/lib.rs
  crates/types/src/test_utils.rs
  crates/types/src/validate.rs
  crates/zome_types/src/query.rs
  crates/zome_types/src/validate.rs
Labels: please-one-approval

#415 [TK-05355] kitsune proxy binary + dump status cli utility
  Cargo.lock
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-proxy/main.rs
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-proxy/opt.rs
  crates/kitsune_p2p/proxy/src/bin/proxy-cli.rs
  crates/kitsune_p2p/proxy/src/config.rs
  crates/kitsune_p2p/proxy/src/inner_listen.rs
  crates/kitsune_p2p/proxy/src/tls_cli.rs
  crates/kitsune_p2p/proxy/src/tls_srv.rs
  crates/kitsune_p2p/proxy/src/tls_tests.rs
  crates/kitsune_p2p/proxy/src/wire_read.rs
  crates/kitsune_p2p/proxy/src/wire_write.rs
  crates/kitsune_p2p/proxy/tests/srv_cli_dump_test.rs
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/transport_quic/src/config.rs
  crates/kitsune_p2p/transport_quic/src/lib.rs
  crates/kitsune_p2p/transport_quic/src/listener.rs
  crates/kitsune_p2p/transport_quic/src/test.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/auto_stream_select.rs
  crates/kitsune_p2p/types/src/lib.rs
  crates/kitsune_p2p/types/src/transport.rs
  crates/kitsune_p2p/types/src/transport_mem.rs
Labels: please-one-approval

#426 add verify_signature access to validation
  crates/holochain/src/core/ribosome/guest_callback/validate.rs
Labels: please-one-approval, tiny

#428 [B-03293] updates send to element authority
  CHANGELOG-UNRELEASED.md
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/state/cascade/network_tests.rs
  crates/holochain/src/core/state/metadata.rs
  crates/holochain/src/core/validation.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/disintegrate.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/produce_dht_ops_workflow/dht_op_light.rs
  crates/holochain/src/core/workflow/produce_dht_ops_workflow/dht_op_light/tests.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain_p2p/src/test.rs
  crates/types/src/dht_op.rs
  crates/types/src/element.rs
  crates/types/src/header.rs
  crates/zome_types/src/metadata.rs
Labels: please-one-approval

#407 get_agent_activity now in the cascade with parallel entry gets
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/authority.rs
  crates/holochain/src/core/ribosome/host_fn/create.rs
  crates/holochain/src/core/ribosome/host_fn/create_link.rs
  crates/holochain/src/core/ribosome/host_fn/delete.rs
  crates/holochain/src/core/ribosome/host_fn/delete_link.rs
  crates/holochain/src/core/ribosome/host_fn/update.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/state/cascade/error.rs
  crates/holochain/src/core/state/cascade/network_tests.rs
  crates/holochain/src/core/state/element_buf.rs
  crates/holochain/src/core/state/metadata.rs
  crates/holochain/src/core/state/metadata/keys.rs
  crates/holochain/src/core/state/metadata/keys/misc.rs
  crates/holochain/src/core/state/metadata/mock.rs
  crates/holochain/src/core/state/source_chain/source_chain_buffer.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/app_validation_workflow/network_call_tests.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow/test.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/produce_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/produce_dht_ops_workflow/dht_op_light/tests.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/test_utils.rs
  crates/holochain_p2p/src/types/actor.rs
  crates/holochain_p2p/src/types/event.rs
  crates/state/src/buffer/cas/buf_sync.rs
  crates/types/src/chain.rs
  crates/types/src/dht_op.rs
  crates/types/src/element.rs
  crates/types/src/entry.rs
  crates/types/src/header.rs
  crates/zome_types/src/query.rs
Labels: please-one-approval

#427 Fix endianess and retry gets
  crates/holochain/src/conductor/cell/authority.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/state/metadata/chain_test.rs
  crates/holochain/src/core/state/metadata/keys.rs
  crates/holochain/src/core/workflow/app_validation_workflow/network_call_tests.rs
  crates/holochain_p2p/src/types/actor.rs
Labels: please-one-approval

#431 test chain status
  crates/holochain/src/core/state/metadata.rs
  crates/holochain/src/core/state/metadata/activity.rs
Labels: please-one-approval

#439 Update build_tutorial.md
  docs/build_tutorial.md
Labels: documentation, please-one-approval

#433 Audit of ignored tests, unignored where possible
  crates/hdk/src/host_fn/sys_time.rs
  crates/holo_hash/src/tests.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/core/ribosome/host_fn/create.rs
  crates/holochain/src/core/state/cascade/network_tests.rs
  crates/holochain/src/core/state/metadata/sys_meta.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/chain_test.rs
  crates/holochain/tests/speed_tests.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/test.rs
  crates/holochain_p2p/src/types/actor.rs
  crates/state/src/buffer/kv/buf/iter_tests.rs
  crates/websocket/tests/integration.rs
Labels: please-one-approval

#408 [TK-05243][TK-05242] authority can serve validation package
  crates/hdk_derive/src/lib.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/validation_package.rs
  crates/holochain/src/core/ribosome.rs
  crates/holochain/src/core/ribosome/guest_callback/validation_package.rs
  crates/holochain/src/core/ribosome/host_fn/create.rs
  crates/holochain/src/core/state/cascade.rs
  crates/holochain/src/core/state/metadata.rs
  crates/holochain/src/core/state/metadata/keys.rs
  crates/holochain/src/core/state/metadata/mock.rs
  crates/holochain/src/core/state/validation_db.rs
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/app_validation_workflow/error.rs
  crates/holochain/src/core/workflow/app_validation_workflow/network_call_tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/types.rs
  crates/holochain/src/core/workflow/app_validation_workflow/validation_package.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow/test.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/chain_test.rs
  crates/holochain/src/fixt.rs
  crates/test_utils/wasm/wasm_workspace/multiple_calls/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/validation_package_success/src/lib.rs
  crates/zome_types/src/validate.rs
Labels: please-two-approvals

#424 [TK-05381] Kitsune Transport Integration
  Cargo.lock
  crates/holochain/src/conductor/cell/test.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/config.rs
  crates/holochain/src/conductor/config/network_config.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/test_utils.rs
  crates/holochain_p2p/src/spawn.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/config.rs
  crates/kitsune_p2p/kitsune_p2p/src/lib.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/types.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/actor.rs
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-proxy/main.rs
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-proxy/opt.rs
  crates/kitsune_p2p/proxy/src/bin/proxy-cli.rs
  crates/kitsune_p2p/proxy/src/inner_listen.rs
  crates/kitsune_p2p/proxy/src/tls_srv.rs
  crates/kitsune_p2p/proxy/src/tls_tests.rs
  crates/kitsune_p2p/proxy/tests/proxy_integration.rs
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/transport_quic/src/config.rs
  crates/kitsune_p2p/transport_quic/src/listener.rs
  crates/kitsune_p2p/transport_quic/src/test.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/lib.rs
  crates/kitsune_p2p/types/src/transport.rs
  crates/kitsune_p2p/types/src/transport_mem.rs
  crates/kitsune_p2p/types/src/transport_pool.rs
Labels: please-one-approval

#430 [TK-05546] kitsune wire protocol
  Cargo.lock
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/types.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/wire.rs
  crates/kitsune_p2p/proxy/src/inner_listen.rs
  crates/kitsune_p2p/proxy/src/tls_cli.rs
  crates/kitsune_p2p/proxy/src/tls_srv.rs
  crates/kitsune_p2p/proxy/src/wire.rs
  crates/kitsune_p2p/proxy/src/wire_read.rs
  crates/kitsune_p2p/proxy/src/wire_write.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/examples/codec.rs
  crates/kitsune_p2p/types/src/codec.rs
  crates/kitsune_p2p/types/src/dht_arc.rs
  crates/kitsune_p2p/types/src/lib.rs
Labels: please-one-approval

#436 [TK-05573] switch to yaml for conductor config
  Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain/src/bin/holochain/main.rs
  crates/holochain/src/conductor/config.rs
  crates/holochain/src/conductor/error.rs
  crates/holochain/src/conductor/interactive.rs
  crates/holochain/src/conductor/paths.rs
  crates/holochain/tests/test_cli.rs
  crates/holochain/tests/websocket.rs
Labels: please-one-approval

#441 Fix fixt to work on rust latest rust
  Cargo.lock
  crates/fixt/Cargo.toml
  crates/fixt/src/bool.rs
  crates/fixt/src/bytes.rs
  crates/fixt/src/lib.rs
  crates/fixt/src/number.rs
  crates/fixt/src/prelude.rs
  crates/fixt/src/serialized_bytes.rs
  crates/fixt/src/string.rs
  crates/fixt/test/Cargo.toml
  crates/hdk_derive/Cargo.toml
  crates/holo_hash/src/fixt.rs
  crates/holochain/src/core/ribosome.rs
  crates/holochain/src/core/ribosome/guest_callback/validate.rs
  crates/holochain/src/fixt.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/types/src/fixt.rs
  crates/zome_types/src/fixt.rs
Labels: please-one-approval

#440 Improve AdminInterfaceApi enum types and AppInterfaceApi enum types and add lots of docs for it
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
  crates/holochain/src/conductor/api/api_external/app_interface.rs
  crates/holochain/src/conductor/api/error.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/core/ribosome.rs
  crates/holochain/tests/websocket.rs
  crates/types/src/app.rs
Labels: merge base pr first, please-one-approval

#442 [TK-05643] Kitsune Test Harness
  Cargo.lock
  crates/holochain/src/conductor/p2p_store.rs
  crates/holochain_p2p/src/fixt.rs
  crates/holochain_p2p/src/lib.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/config.rs
  crates/kitsune_p2p/kitsune_p2p/src/lib.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_agent.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_event.rs
Labels: please-one-approval

#443 update docs/core_testing.md which has Rust version reference
  docs/core_testing.md
Labels: documentation, please-one-approval, tiny

#451 [B-03294] add reference to original header for store entry updates
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
Labels: please-one-approval, tiny

#452 [B-03385] check status before going from light to op
  crates/holochain/src/conductor/cell.rs
Labels: please-one-approval, tiny
