Repository holochain/holochain, pull requests merged in 2021-08, with the labels that each got.

#432 reveal two function cap grant issue via test case
  crates/test_utils/wasm/wasm_workspace/capability/src/lib.rs
Labels: bug, deferred, please-one-approval

#883 [D-01305][B-03948] release-automation milestone 2
  Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain_keystore/Cargo.toml
  crates/holochain_p2p/Cargo.toml
  crates/kitsune_p2p/bootstrap/Cargo.toml
  crates/kitsune_p2p/dht_arc/Cargo.toml
  crates/kitsune_p2p/direct/Cargo.toml
  crates/kitsune_p2p/direct_api/Cargo.toml
  crates/kitsune_p2p/direct_test/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/types/Cargo.toml
  crates/release-automation/README.md
  crates/release-automation/src/common.rs
  crates/release-automation/src/crate_.rs
  crates/release-automation/src/crate_selection/mod.rs
  crates/release-automation/src/main.rs
  crates/release-automation/src/release.rs
  crates/release-automation/src/tests/cli.rs
  crates/release-automation/src/tests/mod.rs
  crates/release-automation/src/tests/workspace_mocker.rs
  nix/pkgs/core.nix
  nix/pkgs/default.nix
Labels: please-one-approval

#899 nix-hc-binary-wrapper: support for running from a different directory
  default.nix
  nix/pkgs/default.nix
Labels: please-one-approval, tiny

#901 Make bandwidth throttle shared
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/bandwidth.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
Labels: please-one-approval

#781 Use no default-features for zome_types in hdk
  crates/hdk/Cargo.toml
  crates/hdk_derive/Cargo.toml
  crates/holo_hash/Cargo.toml
  crates/holochain_zome_types/src/dna_def.rs
  crates/holochain_zome_types/src/zome.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/agent_info/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/crd/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/hash_entry/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/random_bytes/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/sign/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/sys_time/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/zome_info/Cargo.toml
Labels: please-one-approval, tiny

#902 Record metrics at the correct times.
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip.rs
Labels: please-one-approval

#906 Sharded tests pt 1: Scenario Definitions
  crates/kitsune_p2p/dht_arc/src/dht_arc.rs
  crates/kitsune_p2p/dht_arc/src/dht_arc/dht_arc_set.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/tests.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/tests/handler_builder.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/tests/sharded_scenario.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/tests/sharded_scenario_local.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/tests/test_local_sync.rs
Labels: please-two-approvals

#770 Add .to_hash() and .into_hashed() for any HashableContent
  Cargo.lock
  crates/holo_hash/Cargo.toml
  crates/holo_hash/src/hash_ext.rs
  crates/holo_hash/src/lib.rs
  crates/holo_hash/src/tests.rs
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/chain_test.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain/src/fixt.rs
  crates/holochain/tests/network_tests.rs
  crates/holochain_types/src/dht_op.rs
  crates/holochain_types/src/dht_op/facts.rs
  crates/holochain_types/src/dna/dna_bundle.rs
  crates/holochain_types/src/element.rs
  crates/holochain_types/src/test_utils.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: please-one-approval, tiny

#915 Fixes for publish
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow/publish_query.rs
  crates/holochain/tests/multi_conductor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
Labels: please-two-approvals

#911 Make validation receipts work again
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow/publish_query.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow/tests.rs
  crates/holochain_sqlite/src/sql/cell/schema.sql
  crates/holochain_state/src/mutations.rs
Labels: please-one-approval

#903 Countersigning workflow
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/test.rs
  crates/holochain/src/core/queue_consumer.rs
  crates/holochain/src/core/queue_consumer/countersigning_consumer.rs
  crates/holochain/src/core/workflow.rs
  crates/holochain/src/core/workflow/countersigning_workflow.rs
  crates/holochain/src/core/workflow/error.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain_cascade/src/test_utils.rs
  crates/holochain_p2p/src/lib.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/test.rs
  crates/holochain_p2p/src/types/actor.rs
  crates/holochain_p2p/src/types/event.rs
  crates/holochain_p2p/src/types/wire.rs
  crates/holochain_state/src/source_chain.rs
  crates/holochain_zome_types/src/countersigning.rs
Labels: please-one-approval

#908 Countersigning Authority Response
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain_p2p/src/lib.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/test.rs
  crates/holochain_p2p/src/types/actor.rs
  crates/holochain_p2p/src/types/event.rs
  crates/holochain_p2p/src/types/wire.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space/rpc_multi_logic/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/wire.rs
Labels: please-two-approvals

#923 Countersigning success
  crates/holochain/src/conductor/api/api_external/app_interface.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/core/ribosome.rs
  crates/holochain/src/core/ribosome/host_fn/accept_countersigning_preflight_request.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/core/workflow/countersigning_workflow.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow/publish_query.rs
  crates/holochain_conductor_api/src/admin_interface.rs
  crates/holochain_sqlite/src/sql/cell/schema.sql
  crates/holochain_state/src/chain_lock.rs
  crates/holochain_state/src/mutations.rs
  crates/holochain_state/src/scratch.rs
  crates/holochain_state/src/source_chain.rs
  crates/holochain_state/src/source_chain/error.rs
  crates/holochain_zome_types/src/countersigning.rs
  crates/holochain_zome_types/src/zome_io.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/create_entry/src/lib.rs
Labels: please-two-approvals

#926 Countersigning signal
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/core/workflow/countersigning_workflow.rs
  crates/holochain/src/core/workflow/error.rs
  crates/holochain_types/src/signal.rs
Labels: please-one-approval, tiny

#920 increase timestamp by 1 and enforce monotonicity
  crates/holochain/CHANGELOG.md
  crates/holochain/src/core/sys_validate.rs
  crates/holochain_state/src/source_chain.rs
  crates/holochain_state/src/source_chain/error.rs
Labels: please-one-approval, tiny

#919 remove redundant clones
  crates/holochain/src/core/ribosome/host_fn/create.rs
  crates/holochain/src/core/ribosome/host_fn/update.rs
  crates/holochain_zome_types/src/entry.rs
Labels: please-one-approval, tiny

#881 [D-01299] holochain: add test, bench, example, and solution for parallel dna install
  Cargo.lock
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain/benches/bench.rs
  crates/holochain/benches/websocket.rs
  crates/holochain/examples/websocket_install_dna.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/tests/test_utils.rs
  crates/holochain/tests/websocket.rs
  crates/holochain_types/src/test_utils.rs
  crates/holochain_util/src/tokio_helper.rs
  nix/pkgs/default.nix
  nix/shells.nix
Labels: please-one-approval

#912 [TK-10138] use encryption-enabled lair version && pass passphrase (from config for now)
  Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/tests/test_utils.rs
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_conductor_api/src/config/conductor.rs
  crates/holochain_conductor_api/src/config/conductor/passphrase_service_config.rs
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_keystore/Cargo.toml
  crates/holochain_keystore/src/lair_keystore.rs
  crates/kitsune_p2p/direct/Cargo.toml
  crates/kitsune_p2p/direct/src/handle_ws.rs
  crates/kitsune_p2p/direct/src/lib.rs
  crates/kitsune_p2p/direct/src/persist_mem.rs
  crates/kitsune_p2p/direct/src/test.rs
  crates/kitsune_p2p/direct/src/types/kdentry.rs
  crates/kitsune_p2p/direct/src/types/kdhash.rs
  crates/kitsune_p2p/direct/src/v1.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/types/Cargo.toml
  crates/release-automation/Cargo.toml
Labels: please-one-approval

#927 backing out of cs session
  crates/hdk/CHANGELOG.md
  crates/hdk/src/entry.rs
  crates/holochain/src/core/ribosome/guest_callback/validate.rs
  crates/holochain/src/core/ribosome/host_fn/accept_countersigning_preflight_request.rs
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/core/workflow/countersigning_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain_state/src/chain_lock.rs
  crates/holochain_state/src/source_chain.rs
  crates/holochain_zome_types/src/countersigning.rs
  crates/test_utils/wasm/wasm_workspace/countersigning/src/lib.rs
Labels: please-one-approval

#928 extended tests
  crates/holochain/src/core/ribosome/host_fn/accept_countersigning_preflight_request.rs
  crates/test_utils/wasm/wasm_workspace/countersigning/src/lib.rs
Labels: please-one-approval, tiny

#934 Refactor and test metrics / choosing the next node
  Cargo.lock
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/accept.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/initiate.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/metrics.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/next_target.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/store.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/gossip.rs
Labels: please-two-approvals

#943 Remove feature flag and add dynamic arcs to tuning params
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/types/src/config.rs
Labels: tiny
