Repository holochain/holochain, pull requests merged in 2021-07, with the labels that each got.

#854 Instance cache 2
  Cargo.lock
  crates/hdk/Cargo.toml
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain/src/core/ribosome/real_ribosome.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: please-one-approval

#786 [B-03946] release-automation: milestone 1 part 2
  Cargo.lock
  Cargo.toml
  crates/holochain_keystore/src/error.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/release-automation/Cargo.lock
  crates/release-automation/Cargo.toml
  crates/release-automation/README.md
  crates/release-automation/src/changelog.rs
  crates/release-automation/src/check.rs
  crates/release-automation/src/common.rs
  crates/release-automation/src/crate_selection/mod.rs
  crates/release-automation/src/crate_selection/tests/mod.rs
  crates/release-automation/src/main.rs
  crates/release-automation/src/release.rs
  crates/release-automation/src/tests/cli.rs
  crates/release-automation/src/tests/mod.rs
  crates/release-automation/src/tests/workspace_mocker.rs
  nix/pkgs/core.nix
Labels: please-one-approval

#850 format/lint for .sql files
  Cargo.lock
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_sqlite/build.rs
  crates/holochain_sqlite/src/sql/cell/fetch_op_hashes_continuous.sql
  crates/holochain_sqlite/src/sql/cell/fetch_op_hashes_full.sql
  crates/holochain_sqlite/src/sql/cell/fetch_op_hashes_single.sql
  crates/holochain_sqlite/src/sql/cell/fetch_op_hashes_wrap.sql
  crates/holochain_sqlite/src/sql/cell/fetch_op_hashes_wrapped_v1.sql
  crates/holochain_sqlite/src/sql/cell/fetch_op_hashes_wrapped_v2.sql
  crates/holochain_sqlite/src/sql/cell/schema.sql
  crates/holochain_sqlite/src/sql/cell/update_integrate_ops.sql
  crates/holochain_sqlite/src/sql/conductor/schema.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/gossip_query.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/insert.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/prune.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/query_near_basis.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/schema.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/select.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/select_all.sql
  crates/holochain_sqlite/src/sql/p2p_metrics/insert.sql
  crates/holochain_sqlite/src/sql/p2p_metrics/query_last_sync.sql
  crates/holochain_sqlite/src/sql/p2p_metrics/query_oldest.sql
  crates/holochain_sqlite/src/sql/p2p_metrics/schema.sql
  crates/holochain_sqlite/src/sql/wasm/schema.sql
Labels: please-one-approval

#745 Fix mac hc call problem
  crates/hc_sandbox/src/calls.rs
Labels: please-one-approval

#835 [B-04327] "Leave" network on app deactivate
  Cargo.lock
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/manager/mod.rs
  crates/holochain/src/core/workflow/error.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow.rs
  crates/holochain_sqlite/src/db/p2p_agent_store.rs
  crates/holochain_sqlite/src/db/p2p_agent_store/p2p_test.rs
  crates/holochain_sqlite/src/sql/p2p_agent_store/insert.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/query_near_basis.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/schema.sql
  crates/kitsune_p2p/bootstrap/src/lib.rs
  crates/kitsune_p2p/bootstrap/src/random.rs
  crates/kitsune_p2p/bootstrap/src/store.rs
  crates/kitsune_p2p/direct/src/handle_ws.rs
  crates/kitsune_p2p/direct/src/types/handle.rs
  crates/kitsune_p2p/direct/src/v1.rs
  crates/kitsune_p2p/direct_api/src/kdapi.rs
  crates/kitsune_p2p/direct_test/Cargo.toml
  crates/kitsune_p2p/direct_test/src/bin/consistency-stress.rs
  crates/kitsune_p2p/direct_test/src/consistency_stress.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom/step_3_initiate_inner.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/gossip.rs
Labels: please-one-approval

#867 No concurrent init
  crates/holochain/CHANGELOG.md
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/error.rs
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain/src/sweettest/sweet_app.rs
  crates/holochain/src/test_utils/test_conductor/test_handle.rs
Labels: please-one-approval, tiny

#875 Various improvements, some of which actually fix a test
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain/src/conductor/entry_def_store.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/conductor/manager/mod.rs
  crates/holochain/src/conductor/state.rs
  crates/holochain/src/sweettest/sweet_conductor.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/tests/ser_regression.rs
  crates/holochain/tests/speed_tests.rs
  crates/holochain/tests/websocket.rs
  crates/holochain_types/src/app.rs
Labels: please-one-approval

#870 [B-04408] New Publish Based on Neighborhood Delegate Broadcast
  crates/holochain_conductor_api/src/config/conductor.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/test.rs
  crates/kitsune_p2p/direct/src/types/kdhash.rs
  crates/kitsune_p2p/direct/src/v1.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/wire.rs
  crates/kitsune_p2p/types/src/config.rs
Labels: please-one-approval

#877 Preliminary `contrafact::Fact` definitions for various Holochain types
  Cargo.lock
  Cargo.toml
  crates/fixt/Cargo.toml
  crates/hc_bundle/Cargo.toml
  crates/hdk/Cargo.toml
  crates/holo_hash/Cargo.toml
  crates/holo_hash/src/hash.rs
  crates/holo_hash/src/hash_b64.rs
  crates/holo_hash/src/hash_type/primitive.rs
  crates/holo_hash/src/hashed.rs
  crates/holochain/Cargo.toml
  crates/holochain_cascade/Cargo.toml
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_keystore/Cargo.toml
  crates/holochain_p2p/Cargo.toml
  crates/holochain_sqlite/Cargo.lock
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_state/Cargo.toml
  crates/holochain_types/Cargo.toml
  crates/holochain_types/src/dht_op.rs
  crates/holochain_types/src/dht_op/facts.rs
  crates/holochain_types/src/header.rs
  crates/holochain_types/src/header/facts.rs
  crates/holochain_websocket/Cargo.toml
  crates/holochain_zome_types/Cargo.toml
  crates/holochain_zome_types/src/capability/claim.rs
  crates/holochain_zome_types/src/capability/grant.rs
  crates/holochain_zome_types/src/capability/secret.rs
  crates/holochain_zome_types/src/countersigning.rs
  crates/holochain_zome_types/src/element.rs
  crates/holochain_zome_types/src/element/facts.rs
  crates/holochain_zome_types/src/entry.rs
  crates/holochain_zome_types/src/entry/app_entry_bytes.rs
  crates/holochain_zome_types/src/entry_def.rs
  crates/holochain_zome_types/src/header.rs
  crates/holochain_zome_types/src/header/facts.rs
  crates/holochain_zome_types/src/lib.rs
  crates/holochain_zome_types/src/link.rs
  crates/holochain_zome_types/src/signature.rs
  crates/holochain_zome_types/src/timestamp.rs
  crates/holochain_zome_types/src/zome.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.toml
Labels: please-one-approval

#885 Revert most recent develop versions and apply them only to changed crates
  Cargo.lock
  crates/kitsune_p2p/dht_arc/Cargo.toml
  crates/kitsune_p2p/direct_api/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/mdns/Cargo.toml
  crates/kitsune_p2p/types/Cargo.toml
Labels: please-one-approval

#733 Use subtle-encoding for secure primitive Debug
  Cargo.lock
  crates/holochain_zome_types/Cargo.toml
  crates/holochain_zome_types/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: tiny

#893 merge release-20210722.172107 back into develop
  CHANGELOG.md
  Cargo.lock
  crates/fixt/CHANGELOG.md
  crates/fixt/Cargo.toml
  crates/fixt/test/Cargo.toml
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/Cargo.toml
  crates/hc_sandbox/CHANGELOG.md
  crates/hc_sandbox/Cargo.toml
  crates/hdk/CHANGELOG.md
  crates/hdk/Cargo.toml
  crates/hdk_derive/CHANGELOG.md
  crates/hdk_derive/Cargo.toml
  crates/holo_hash/CHANGELOG.md
  crates/holo_hash/Cargo.toml
  crates/holo_hash/src/hashed.rs
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_cascade/Cargo.toml
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_keystore/Cargo.toml
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_p2p/Cargo.toml
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_state/CHANGELOG.md
  crates/holochain_state/Cargo.toml
  crates/holochain_types/CHANGELOG.md
  crates/holochain_types/Cargo.toml
  crates/holochain_util/CHANGELOG.md
  crates/holochain_util/Cargo.toml
  crates/holochain_websocket/CHANGELOG.md
  crates/holochain_websocket/Cargo.toml
  crates/holochain_zome_types/CHANGELOG.md
  crates/holochain_zome_types/Cargo.toml
  crates/kitsune_p2p/bootstrap/Cargo.toml
  crates/kitsune_p2p/direct/Cargo.toml
  crates/kitsune_p2p/direct_test/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/proxy/CHANGELOG.md
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/transport_quic/CHANGELOG.md
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/types/CHANGELOG.md
  crates/kitsune_p2p/types/Cargo.toml
  crates/mr_bundle/CHANGELOG.md
  crates/mr_bundle/Cargo.toml
  crates/mr_bundle/src/util.rs
  crates/release-automation/Cargo.toml
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm_common/CHANGELOG.md
  crates/test_utils/wasm_common/Cargo.toml
Labels: please-one-approval

#876 [B-04409] New Sharded Get
  crates/holochain_conductor_api/src/config/conductor.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space/rpc_multi_logic.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/actor.rs
  crates/kitsune_p2p/types/src/config.rs
  crates/kitsune_p2p/types/src/lib.rs
  crates/kitsune_p2p/types/src/reverse_semaphore.rs
  crates/kitsune_p2p/types/src/task_agg.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/share.rs
Labels: please-one-approval

#884 sharded get - mock additions
  Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain_cascade/Cargo.toml
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_keystore/Cargo.toml
  crates/holochain_p2p/Cargo.toml
  crates/holochain_state/Cargo.toml
  crates/holochain_types/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space/rpc_multi_logic.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space/rpc_multi_logic/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_agent.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/event.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/lib.rs
  crates/kitsune_p2p/types/src/reverse_semaphore.rs
  crates/kitsune_p2p/types/src/timeout.rs
  crates/kitsune_p2p/types/src/transport_pool.rs
  crates/kitsune_p2p/types/src/tx2/framed.rs
  crates/kitsune_p2p/types/src/tx2/tx2_adapter.rs
  crates/kitsune_p2p/types/src/tx2/tx2_api.rs
  crates/kitsune_p2p/types/src/tx2/tx2_pool_promote.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/latency.rs
Labels: please-one-approval

#892 Check if agent is authority and set dht arcs.
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain_p2p/src/lib.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/test.rs
  crates/holochain_p2p/src/types/actor.rs
  crates/holochain_p2p/src/types/event.rs
  crates/holochain_sqlite/src/db/p2p_agent_store.rs
  crates/holochain_sqlite/src/db/p2p_agent_store/p2p_test.rs
  crates/kitsune_p2p/dht_arc/src/dht_arc.rs
  crates/kitsune_p2p/direct/src/persist_mem.rs
  crates/kitsune_p2p/direct/src/types/persist.rs
  crates/kitsune_p2p/direct/src/v1.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_agent.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/event.rs
  crates/kitsune_p2p/types/src/agent_info.rs
  shell.nix
Labels: please-one-approval
