Repository holochain/holochain, pull requests merged in 2021-06, with the labels that each got.

#803 Sb gossip index 2
  crates/holochain/Cargo.toml
  crates/holochain/benches/consistency.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain_cascade/src/lib.rs
  crates/holochain_sqlite/src/db/p2p.rs
  crates/holochain_sqlite/src/sql.rs
  crates/holochain_sqlite/src/sql/cell/fetch_op_hashes_full.sql
  crates/holochain_sqlite/src/sql/cell/fetch_op_hashes_single.sql
  crates/holochain_sqlite/src/sql/cell/fetch_op_hashes_wrap.sql
  crates/holochain_sqlite/src/sql/cell/schema.sql
  crates/holochain_state/src/mutations.rs
  crates/holochain_state/src/query/chain_head.rs
  crates/holochain_state/src/query/tests.rs
  crates/holochain_state/src/source_chain.rs
  crates/holochain_zome_types/src/timestamp.rs
  crates/test_utils/wasm/wasm_workspace/anchor/src/lib.rs
  crates/test_utils/wasm_common/src/lib.rs
Labels: please-one-approval

#804 Author skip self publish
  Cargo.lock
  Cargo.toml
  crates/holochain/benches/consistency.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow/publish_query.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow/tests.rs
  crates/holochain_cascade/src/authority/get_element_query.rs
  crates/holochain_cascade/src/authority/get_entry_ops_query.rs
  crates/holochain_cascade/src/test_utils/element_test_data.rs
  crates/holochain_cascade/src/test_utils/entry_test_data.rs
  crates/holochain_state/src/source_chain.rs
Labels: please-one-approval

#819 Metrics Fixes
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain_sqlite/src/db/p2p_metrics.rs
  crates/holochain_sqlite/src/sql/cell/fetch_op_hashes_full.sql
  crates/holochain_sqlite/src/sql/cell/fetch_op_hashes_single.sql
  crates/holochain_sqlite/src/sql/cell/fetch_op_hashes_wrap.sql
  crates/holochain_state/src/test_utils.rs
Labels: please-one-approval

#815 Kitsune arcsets pt 0: Preliminaries
  crates/holochain/src/conductor.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/p2p_agent_store.rs
  crates/holochain/src/local_network_tests.rs
  crates/holochain/src/sweettest/sweet_conductor_batch.rs
  crates/holochain/src/test_utils.rs
  crates/holochain_conductor_api/src/state_dump.rs
  crates/holochain_sqlite/src/db.rs
  crates/holochain_sqlite/src/db/p2p_agent_store.rs
  crates/holochain_sqlite/src/db/p2p_agent_store/p2p_test.rs
  crates/holochain_sqlite/src/schema.rs
  crates/holochain_sqlite/src/sql.rs
  crates/holochain_sqlite/src/sql/p2p_agent_store/gossip_query.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/insert.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/prune.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/schema.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/select.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/select_all.sql
  crates/holochain_sqlite/src/sql/p2p_state/prune.sql
  crates/holochain_sqlite/src/sql/p2p_state/select_all.sql
  crates/holochain_sqlite/src/table.rs
  crates/holochain_sqlite/src/test_utils.rs
  crates/holochain_state/src/test_utils.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom/step_1_check_inner.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom/step_2_local_sync_inner.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom/step_3_initiate_inner.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom/step_4_com_loop_inner.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/event.rs
Labels: please-one-approval

#817 [TK-09573] fix agent_info && move to kitsune_p2p_types
  Cargo.lock
  crates/hc_sandbox/src/calls.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/conductor/p2p_agent_store.rs
  crates/holochain/src/local_network_tests.rs
  crates/holochain_conductor_api/src/state_dump.rs
  crates/holochain_sqlite/src/db/p2p_agent_store.rs
  crates/holochain_sqlite/src/db/p2p_agent_store/p2p_test.rs
  crates/kitsune_p2p/direct/src/types/kdagent.rs
  crates/kitsune_p2p/kitsune_p2p/src/fixt.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom/step_3_initiate_inner.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom/step_4_com_loop_inner.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/bootstrap.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/types.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/agent_store.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/agent_info.rs
  crates/kitsune_p2p/types/src/bin_types.rs
  crates/kitsune_p2p/types/src/lib.rs
Labels: please-one-approval

#823 [TK-09615] batch process incoming publish/dht_ops
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow/test.rs
  crates/holochain_sqlite/src/sql/cell/schema.sql
  crates/holochain_types/src/env.rs
Labels: please-one-approval

#830 Bootstrap server
  Cargo.lock
  Cargo.toml
  crates/kitsune_p2p/bootstrap/Cargo.toml
  crates/kitsune_p2p/bootstrap/benches/bench.rs
  crates/kitsune_p2p/bootstrap/src/clear.rs
  crates/kitsune_p2p/bootstrap/src/lib.rs
  crates/kitsune_p2p/bootstrap/src/main.rs
  crates/kitsune_p2p/bootstrap/src/now.rs
  crates/kitsune_p2p/bootstrap/src/put.rs
  crates/kitsune_p2p/bootstrap/src/random.rs
  crates/kitsune_p2p/bootstrap/src/store.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/bootstrap.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/types/src/bootstrap.rs
  crates/kitsune_p2p/types/src/lib.rs
Labels: please-one-approval

#837 Bugfix: Use ProcCountMicros instead of Instant
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom/step_1_check_inner.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom/step_3_initiate_inner.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom/step_4_com_loop_inner.rs
  crates/kitsune_p2p/types/src/lib.rs
Labels: please-one-approval

#832 List Apps
  crates/hc_sandbox/src/calls.rs
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain_conductor_api/src/admin_interface.rs
Labels: please-one-approval

#838 Add a single reusable thread as the pool for r2d2
  Cargo.lock
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_sqlite/src/conn.rs
Labels: please-one-approval, tiny

#825 release preparation fixes
  crates/hc/Cargo.toml
  crates/hc_bundle/Cargo.toml
  crates/hc_sandbox/Cargo.toml
  crates/holochain_keystore/Cargo.toml
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_types/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/mr_bundle/Cargo.toml
Labels: please-one-approval

#827 [TK-09295] Bootstrap Queries as loop at space level
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
Labels: please-one-approval

#833 Kitsune arcsets pt. 2: Arc set logic + query for gossip by arcset intersection
  Cargo.lock
  Cargo.toml
  crates/holochain/src/conductor/cell/gossip_test.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/conductor/p2p_agent_store.rs
  crates/holochain_sqlite/src/db/p2p_agent_store.rs
  crates/holochain_sqlite/src/db/p2p_agent_store/p2p_test.rs
  crates/holochain_sqlite/src/sql/p2p_agent_store/gossip_query.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/schema.sql
  crates/kitsune_p2p/dht_arc/.gitignore
  crates/kitsune_p2p/dht_arc/CHANGELOG.md
  crates/kitsune_p2p/dht_arc/Cargo.lock
  crates/kitsune_p2p/dht_arc/Cargo.toml
  crates/kitsune_p2p/dht_arc/README.md
  crates/kitsune_p2p/dht_arc/src/dht_arc.rs
  crates/kitsune_p2p/dht_arc/src/dht_arc/dht_arc_bucket.rs
  crates/kitsune_p2p/dht_arc/src/dht_arc/dht_arc_set.rs
  crates/kitsune_p2p/dht_arc/src/dht_arc/gaps.rs
  crates/kitsune_p2p/dht_arc/src/dht_arc/tests.rs
  crates/kitsune_p2p/dht_arc/src/lib.rs
  crates/kitsune_p2p/dht_arc/src/test/ascii.rs
  crates/kitsune_p2p/dht_arc/src/test/intersection.rs
  crates/kitsune_p2p/dht_arc/src/test/mod.rs
  crates/kitsune_p2p/dht_arc/src/test/union.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/lib.rs
Labels: please-two-approvals

#848 Cache up to 20 instances
  crates/holochain/src/core/ribosome/host_fn.rs
  crates/holochain/src/core/ribosome/host_fn/agent_info.rs
  crates/holochain/src/core/ribosome/host_fn/call.rs
  crates/holochain/src/core/ribosome/host_fn/call_remote.rs
  crates/holochain/src/core/ribosome/host_fn/create.rs
  crates/holochain/src/core/ribosome/host_fn/create_link.rs
  crates/holochain/src/core/ribosome/host_fn/create_x25519_keypair.rs
  crates/holochain/src/core/ribosome/host_fn/delete.rs
  crates/holochain/src/core/ribosome/host_fn/delete_link.rs
  crates/holochain/src/core/ribosome/host_fn/emit_signal.rs
  crates/holochain/src/core/ribosome/host_fn/get.rs
  crates/holochain/src/core/ribosome/host_fn/get_agent_activity.rs
  crates/holochain/src/core/ribosome/host_fn/get_details.rs
  crates/holochain/src/core/ribosome/host_fn/get_link_details.rs
  crates/holochain/src/core/ribosome/host_fn/get_links.rs
  crates/holochain/src/core/ribosome/host_fn/query.rs
  crates/holochain/src/core/ribosome/host_fn/random_bytes.rs
  crates/holochain/src/core/ribosome/host_fn/remote_signal.rs
  crates/holochain/src/core/ribosome/host_fn/sign.rs
  crates/holochain/src/core/ribosome/host_fn/sign_ephemeral.rs
  crates/holochain/src/core/ribosome/host_fn/sys_time.rs
  crates/holochain/src/core/ribosome/host_fn/trace.rs
  crates/holochain/src/core/ribosome/host_fn/unreachable.rs
  crates/holochain/src/core/ribosome/host_fn/update.rs
  crates/holochain/src/core/ribosome/host_fn/verify_signature.rs
  crates/holochain/src/core/ribosome/host_fn/x_25519_x_salsa20_poly1305_decrypt.rs
  crates/holochain/src/core/ribosome/host_fn/x_25519_x_salsa20_poly1305_encrypt.rs
  crates/holochain/src/core/ribosome/host_fn/x_salsa20_poly1305_decrypt.rs
  crates/holochain/src/core/ribosome/host_fn/x_salsa20_poly1305_encrypt.rs
  crates/holochain/src/core/ribosome/host_fn/zome_info.rs
  crates/holochain/src/core/ribosome/real_ribosome.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain_zome_types/src/zome_io.rs
Labels: please-two-approvals

#841 Only update a single agent info on join
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
Labels: please-one-approval

#794 [B-03960] Peer Query
  Cargo.lock
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/p2p_agent_store.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/types/event.rs
  crates/holochain_sqlite/src/db/p2p_agent_store.rs
  crates/holochain_sqlite/src/db/p2p_agent_store/p2p_test.rs
  crates/holochain_sqlite/src/sql.rs
  crates/holochain_sqlite/src/sql/p2p_agent_store/query_near_basis.sql
  crates/kitsune_p2p/dht_arc/Cargo.toml
  crates/kitsune_p2p/direct/src/persist_mem.rs
  crates/kitsune_p2p/direct/src/types/kdagent.rs
  crates/kitsune_p2p/direct/src/types/persist.rs
  crates/kitsune_p2p/direct/src/v1.rs
  crates/kitsune_p2p/direct_api/Cargo.toml
  crates/kitsune_p2p/direct_api/src/kdagent.rs
  crates/kitsune_p2p/direct_test/src/lib.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/harness_agent.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/event.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/metrics.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/wire.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/lib.rs
  crates/kitsune_p2p/types/src/timeout.rs
Labels: please-one-approval

#844 [TK-09744] kitsune direct stress testing
  Cargo.lock
  crates/kitsune_p2p/bootstrap/Cargo.toml
  crates/kitsune_p2p/bootstrap/src/lib.rs
  crates/kitsune_p2p/bootstrap/src/main.rs
  crates/kitsune_p2p/direct/Cargo.toml
  crates/kitsune_p2p/direct/src/bin/kd/cmd_bootstrap.rs
  crates/kitsune_p2p/direct/src/bin/kd/cmd_node.rs
  crates/kitsune_p2p/direct/src/bin/kd/cmd_proxy.rs
  crates/kitsune_p2p/direct/src/bin/kd/main.rs
  crates/kitsune_p2p/direct/src/test.rs
  crates/kitsune_p2p/direct/src/v1.rs
  crates/kitsune_p2p/direct_test/Cargo.toml
  crates/kitsune_p2p/direct_test/src/bin/consistency-stress.rs
  crates/kitsune_p2p/direct_test/src/bin/direct-test-local-periodic.rs
  crates/kitsune_p2p/direct_test/src/consistency_stress.rs
  crates/kitsune_p2p/direct_test/src/direct_test_local_periodic.rs
  crates/kitsune_p2p/direct_test/src/lib.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/tx_url.rs
Labels: please-one-approval

#847 Various fixes to make sql faster
  crates/holochain/src/conductor/cell/gossip_test.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain_sqlite/src/sql/cell/schema.sql
  crates/holochain_sqlite/src/sql/cell/update_integrate_ops.sql
  crates/holochain_state/src/mutations.rs
  crates/holochain_state/src/query/chain_head.rs
  crates/holochain_state/src/source_chain.rs
Labels: please-one-approval

#863 compile but don't run benchmarks in CI
  crates/kitsune_p2p/bootstrap/benches/bench.rs
  nix/pkgs/core.nix
Labels: please-one-approval
