Repository holochain/holochain, pull requests merged in 2021-04, with the labels that each got.

#704 [TK-07999 TK-08000 TK-08001] tx2 backend + mem transport
  crates/kitsune_p2p/types/src/tx2.rs
  crates/kitsune_p2p/types/src/tx2/framed.rs
  crates/kitsune_p2p/types/src/tx2/mem.rs
  crates/kitsune_p2p/types/src/tx2/tx2_backend.rs
Labels: please-one-approval

#705 [TK-08009] tx2 frontend + tx2 promote
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/bootstrap.rs
  crates/kitsune_p2p/types/src/lib.rs
  crates/kitsune_p2p/types/src/tx2.rs
  crates/kitsune_p2p/types/src/tx2/tx2_frontend.rs
  crates/kitsune_p2p/types/src/tx2/tx2_promote.rs
Labels: please-one-approval

#706 [TK-08010 TK-08011] tx2 proxy
  Cargo.lock
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/proxy/benches/thru.rs
  crates/kitsune_p2p/proxy/src/lib.rs
  crates/kitsune_p2p/proxy/src/proxy_url.rs
  crates/kitsune_p2p/proxy/src/tx2.rs
  crates/kitsune_p2p/types/src/tx2/tx2_backend.rs
Labels: please-one-approval

#714 [TK-08013 TK-08014] tx2 quic backend && proxy benchmark
  Cargo.lock
  crates/kitsune_p2p/proxy/benches/thru.rs
  crates/kitsune_p2p/proxy/src/config.rs
  crates/kitsune_p2p/transport_quic/src/lib.rs
  crates/kitsune_p2p/transport_quic/src/tx2.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/lib.rs
  crates/kitsune_p2p/types/src/tls.rs
  crates/kitsune_p2p/types/src/transport.rs
  crates/kitsune_p2p/types/src/tx2.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/tx_url.rs
Labels: please-one-approval

#720 [TK-08012] proxy binary && debugging
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-proxy/main.rs
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-tx2-proxy.rs
  crates/kitsune_p2p/proxy/src/bin/proxy-tx2-cli.rs
  crates/kitsune_p2p/proxy/src/tx2.rs
  crates/kitsune_p2p/transport_quic/src/tx2.rs
  crates/kitsune_p2p/types/src/tx2/mem.rs
  crates/kitsune_p2p/types/src/tx2/tx2_backend.rs
  crates/kitsune_p2p/types/src/tx2/tx2_frontend.rs
  crates/kitsune_p2p/types/src/tx2/tx2_promote.rs
Labels: please-one-approval

#721 [TK-08002 TK-08017] req/res handling in tx2_api
  Cargo.lock
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/benches/api_thru.rs
  crates/kitsune_p2p/types/src/tx2.rs
  crates/kitsune_p2p/types/src/tx2/tx2_api.rs
  crates/kitsune_p2p/types/src/tx2/tx2_frontend.rs
Labels: please-one-approval

#730 [TK-08548 TK-08683] tx2 pooling logic
  Cargo.lock
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain_conductor_api/src/config/conductor.rs
  crates/kitsune_p2p/kitsune_p2p/src/config.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/proxy/benches/old_proxy_thru.rs
  crates/kitsune_p2p/proxy/benches/thru.rs
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-proxy/main.rs
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-tx2-proxy.rs
  crates/kitsune_p2p/proxy/src/bin/proxy-cli.rs
  crates/kitsune_p2p/proxy/src/bin/proxy-stress.rs
  crates/kitsune_p2p/proxy/src/bin/proxy-tx2-cli.rs
  crates/kitsune_p2p/proxy/src/config.rs
  crates/kitsune_p2p/proxy/src/inner_listen.rs
  crates/kitsune_p2p/proxy/src/tls_tests.rs
  crates/kitsune_p2p/proxy/src/tx2.rs
  crates/kitsune_p2p/proxy/tests/no_proxy.rs
  crates/kitsune_p2p/proxy/tests/proxy_integration.rs
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/transport_quic/src/tx2.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/benches/api_thru.rs
  crates/kitsune_p2p/types/src/config.rs
  crates/kitsune_p2p/types/src/lib.rs
  crates/kitsune_p2p/types/src/tls.rs
  crates/kitsune_p2p/types/src/tx2.rs
  crates/kitsune_p2p/types/src/tx2/mem.rs
  crates/kitsune_p2p/types/src/tx2/tx2_adapter.rs
  crates/kitsune_p2p/types/src/tx2/tx2_api.rs
  crates/kitsune_p2p/types/src/tx2/tx2_frontend.rs
  crates/kitsune_p2p/types/src/tx2/tx2_pool.rs
  crates/kitsune_p2p/types/src/tx2/tx2_pool_promote.rs
  crates/kitsune_p2p/types/src/tx2/tx2_promote.rs
Labels: please-one-approval

#734 CapGrants use BTreeSet
  crates/hdk/src/prelude.rs
  crates/holochain/src/core/ribosome/host_fn/remote_signal.rs
  crates/holochain_state/src/source_chain.rs
  crates/holochain_zome_types/src/capability/grant.rs
  crates/holochain_zome_types/src/fixt.rs
  crates/test_utils/wasm/wasm_workspace/capability/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/create_entry/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/emit_signal/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/foo/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/whoami/src/lib.rs
Labels: please-one-approval

#739 adds systemd ready notification to main conductor process
  Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain/src/bin/holochain/main.rs
Labels: please-one-approval, tiny, usability

#742 Removes optional flag from kitsune_p2p_types
  crates/holochain/Cargo.toml
Labels: build issue, please-one-approval

#735 [TK-08547] Tx2 Error Handling
  Cargo.lock
  crates/fixt/Cargo.toml
  crates/fixt/test/Cargo.toml
  crates/hdk/Cargo.toml
  crates/hdk_derive/Cargo.toml
  crates/holochain/src/bin/holochain/main.rs
  crates/holochain_p2p/src/test.rs
  crates/holochain_zome_types/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/wire.rs
  crates/kitsune_p2p/proxy/benches/thru.rs
  crates/kitsune_p2p/proxy/examples/cli-chat.rs
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-tx2-proxy.rs
  crates/kitsune_p2p/proxy/src/bin/proxy-tx2-cli.rs
  crates/kitsune_p2p/proxy/src/inner_listen.rs
  crates/kitsune_p2p/proxy/src/tx2.rs
  crates/kitsune_p2p/proxy/tests/tx2_con_up_down.rs
  crates/kitsune_p2p/transport_quic/src/tx2.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/codec.rs
  crates/kitsune_p2p/types/src/config.rs
  crates/kitsune_p2p/types/src/lib.rs
  crates/kitsune_p2p/types/src/metrics.rs
  crates/kitsune_p2p/types/src/tx2/framed.rs
  crates/kitsune_p2p/types/src/tx2/mem.rs
  crates/kitsune_p2p/types/src/tx2/tx2_adapter.rs
  crates/kitsune_p2p/types/src/tx2/tx2_api.rs
  crates/kitsune_p2p/types/src/tx2/tx2_pool.rs
  crates/kitsune_p2p/types/src/tx2/tx2_pool_promote.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/active.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/logic_chan.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/mem_chan.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/notify_all.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/pool_buf.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/resource_bucket.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/t_chan.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: please-one-approval

#731 [TK-08015] Tx2 Kitsune Integration
  Cargo.lock
  crates/fixt/Cargo.toml
  crates/fixt/test/Cargo.toml
  crates/hdk/Cargo.toml
  crates/hdk_derive/Cargo.toml
  crates/holochain/src/bin/holochain/main.rs
  crates/holochain_p2p/src/test.rs
  crates/holochain_zome_types/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/config.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/types.rs
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/proxy/benches/thru.rs
  crates/kitsune_p2p/proxy/examples/cli-chat.rs
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-tx2-proxy.rs
  crates/kitsune_p2p/proxy/src/bin/proxy-tx2-cli.rs
  crates/kitsune_p2p/proxy/src/inner_listen.rs
  crates/kitsune_p2p/proxy/src/tx2.rs
  crates/kitsune_p2p/proxy/tests/tx2_con_up_down.rs
  crates/kitsune_p2p/transport_quic/src/tx2.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/benches/api_thru.rs
  crates/kitsune_p2p/types/src/codec.rs
  crates/kitsune_p2p/types/src/config.rs
  crates/kitsune_p2p/types/src/lib.rs
  crates/kitsune_p2p/types/src/metrics.rs
  crates/kitsune_p2p/types/src/tx2/framed.rs
  crates/kitsune_p2p/types/src/tx2/mem.rs
  crates/kitsune_p2p/types/src/tx2/tx2_adapter.rs
  crates/kitsune_p2p/types/src/tx2/tx2_api.rs
  crates/kitsune_p2p/types/src/tx2/tx2_pool.rs
  crates/kitsune_p2p/types/src/tx2/tx2_pool_promote.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/active.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/logic_chan.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/mem_chan.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/notify_all.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/pool_buf.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/resource_bucket.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/t_chan.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/tx_url.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: NO-MERGE (dependency), please-one-approval
