Repository holochain/holochain, pull requests merged in 2021-05, with the labels that each got.

#754 Synchronous Genesis
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/error.rs
  crates/holochain/src/conductor/cell/test.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/conductor/manager/mod.rs
  crates/holochain/src/core/ribosome.rs
  crates/holochain/src/core/ribosome/guest_callback.rs
  crates/holochain/src/core/ribosome/guest_callback/genesis_self_check.rs
  crates/holochain/src/core/ribosome/host_fn/capability_grants.rs
  crates/holochain/src/core/ribosome/host_fn/remote_signal.rs
  crates/holochain/src/core/ribosome/real_ribosome.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/error.rs
  crates/holochain/src/core/workflow/genesis_workflow.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow/tests.rs
  crates/holochain/src/test_utils/sweetest/sweet_conductor.rs
  crates/holochain/tests/agent_scaling.rs
  crates/holochain/tests/inline_zome_spec.rs
  crates/holochain/tests/multi_conductor.rs
  crates/holochain/tests/websocket.rs
  crates/holochain_types/src/app.rs
  crates/holochain_types/src/dna/zome/inline_zome/error.rs
  crates/holochain_types/src/test_utils.rs
  crates/holochain_zome_types/src/genesis.rs
  crates/holochain_zome_types/src/lib.rs
  crates/holochain_zome_types/src/prelude.rs
  crates/test_utils/wasm/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/genesis_self_check_invalid/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/genesis_self_check_invalid/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/genesis_self_check_valid/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/genesis_self_check_valid/src/lib.rs
Labels: please-two-approvals

#708 deepkey tweaks
  crates/fixt/src/bytes.rs
  crates/fixt/src/lib.rs
  crates/hdk/Cargo.toml
  crates/holo_hash/Cargo.toml
  crates/holo_hash/src/fixt.rs
  crates/holo_hash/src/hashed.rs
  crates/holochain/src/fixt.rs
  crates/holochain_types/src/fixt.rs
  crates/holochain_zome_types/Cargo.toml
  crates/holochain_zome_types/src/element.rs
  crates/holochain_zome_types/src/fixt.rs
  crates/holochain_zome_types/src/lib.rs
  crates/holochain_zome_types/src/link.rs
  crates/holochain_zome_types/src/validate.rs
Labels: please-one-approval

#768 Don't crash on cell-specific errors, only deactivate app
  crates/holochain/src/conductor/manager/mod.rs
Labels: please-one-approval

#765 [B-04157] Indexable SQL p2p_store
  Cargo.lock
  crates/holochain/src/conductor/api/error.rs
  crates/holochain/src/conductor/cell/gossip_test.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/conductor/p2p_store.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/local_network_tests.rs
  crates/holochain/src/sweettest/sweet_conductor_batch.rs
  crates/holochain/src/test_utils.rs
  crates/holochain_p2p/src/lib.rs
  crates/holochain_p2p/src/types.rs
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_sqlite/src/db.rs
  crates/holochain_sqlite/src/db/p2p.rs
  crates/holochain_sqlite/src/db/p2p/p2p_test.rs
  crates/holochain_sqlite/src/lib.rs
  crates/holochain_sqlite/src/schema.rs
  crates/holochain_sqlite/src/schema/p2p/initial.sql
  crates/holochain_sqlite/src/sql.rs
  crates/holochain_sqlite/src/sql/cell/schema.sql
  crates/holochain_sqlite/src/sql/cell/update_integrate_ops.sql
  crates/holochain_sqlite/src/sql/conductor/schema.sql
  crates/holochain_sqlite/src/sql/p2p/gossip_query.sql
  crates/holochain_sqlite/src/sql/p2p/insert.sql
  crates/holochain_sqlite/src/sql/p2p/prune.sql
  crates/holochain_sqlite/src/sql/p2p/schema.sql
  crates/holochain_sqlite/src/sql/p2p/select.sql
  crates/holochain_sqlite/src/sql/p2p/select_all.sql
  crates/holochain_sqlite/src/sql/wasm/schema.sql
  crates/holochain_sqlite/src/table.rs
  crates/holochain_sqlite/src/test_utils.rs
  crates/holochain_state/Cargo.toml
  crates/holochain_state/src/agent_info.rs
  crates/holochain_state/src/lib.rs
  crates/holochain_state/src/mutations.rs
  crates/holochain_state/src/test_utils.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/fixt.rs
  crates/kitsune_p2p/kitsune_p2p/src/types.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/agent_store.rs
Labels: please-one-approval

#780 Move DnaDef et al to zome_types, with feature flag
  Cargo.lock
  crates/holochain/benches/bench.rs
  crates/holochain/src/conductor/api/error.rs
  crates/holochain/src/conductor/entry_def_store.rs
  crates/holochain/src/conductor/error.rs
  crates/holochain/src/core/ribosome/error.rs
  crates/holochain/src/core/ribosome/guest_callback.rs
  crates/holochain/src/core/ribosome/guest_callback/entry_defs.rs
  crates/holochain/src/core/ribosome/guest_callback/init.rs
  crates/holochain/src/core/ribosome/guest_callback/migrate_agent.rs
  crates/holochain/src/core/ribosome/guest_callback/post_commit.rs
  crates/holochain/src/core/ribosome/guest_callback/validate.rs
  crates/holochain/src/core/ribosome/guest_callback/validate_link.rs
  crates/holochain/src/core/ribosome/guest_callback/validation_package.rs
  crates/holochain/src/core/ribosome/host_fn/call.rs
  crates/holochain/src/core/ribosome/host_fn/create.rs
  crates/holochain/src/core/ribosome/host_fn/remote_signal.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/initialize_zomes_workflow.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow/tests.rs
  crates/holochain/src/fixt.rs
  crates/holochain/src/sweettest/sweet_dna.rs
  crates/holochain/tests/inline_zome_spec.rs
  crates/holochain/tests/multi_conductor.rs
  crates/holochain/tests/websocket.rs
  crates/holochain_types/src/access.rs
  crates/holochain_types/src/app.rs
  crates/holochain_types/src/app/app_bundle/tests.rs
  crates/holochain_types/src/app/app_manifest.rs
  crates/holochain_types/src/app/app_manifest/app_manifest_v1.rs
  crates/holochain_types/src/dna.rs
  crates/holochain_types/src/dna/dna_bundle.rs
  crates/holochain_types/src/dna/dna_file.rs
  crates/holochain_types/src/dna/dna_manifest.rs
  crates/holochain_types/src/dna/error.rs
  crates/holochain_types/src/dna/zome.rs
  crates/holochain_types/src/fixt.rs
  crates/holochain_types/src/lib.rs
  crates/holochain_types/src/prelude.rs
  crates/holochain_types/src/properties.rs
  crates/holochain_types/src/test_utils.rs
  crates/holochain_zome_types/Cargo.toml
  crates/holochain_zome_types/src/dna_def.rs
  crates/holochain_zome_types/src/fixt.rs
  crates/holochain_zome_types/src/lib.rs
  crates/holochain_zome_types/src/prelude.rs
  crates/holochain_zome_types/src/zome.rs
  crates/holochain_zome_types/src/zome/error.rs
  crates/holochain_zome_types/src/zome/inline_zome.rs
  crates/holochain_zome_types/src/zome/inline_zome/error.rs
  crates/test_utils/wasm/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: please-one-approval

#785 Fix bug where failed init still allowed commits
  crates/holochain/src/conductor.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain/src/core/ribosome/guest_callback/init.rs
  crates/holochain/src/core/workflow/initialize_zomes_workflow.rs
  crates/holochain_zome_types/src/zome_io.rs
Labels: please-one-approval, tiny

#752 [B-04190] Simple Bloom Gossip
  Cargo.lock
  Cargo.toml
  crates/holochain/src/conductor/p2p_store.rs
  crates/kitsune_p2p/direct/Cargo.toml
  crates/kitsune_p2p/direct/src/lib.rs
  crates/kitsune_p2p/direct/src/persist_mem.rs
  crates/kitsune_p2p/direct/src/types.rs
  crates/kitsune_p2p/direct/src/types/direct.rs
  crates/kitsune_p2p/direct/src/types/kdagent.rs
  crates/kitsune_p2p/direct/src/types/kdentry.rs
  crates/kitsune_p2p/direct/src/types/kdhash.rs
  crates/kitsune_p2p/direct/src/types/persist.rs
  crates/kitsune_p2p/direct/src/v1.rs
  crates/kitsune_p2p/direct_test/Cargo.toml
  crates/kitsune_p2p/direct_test/src/bin/direct-test-local-periodic.rs
  crates/kitsune_p2p/direct_test/src/lib.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom/step_2_local_sync_inner.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom/step_3_initiate_inner.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom/step_4_com_loop_inner.rs
  crates/kitsune_p2p/kitsune_p2p/src/lib.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/types.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/metrics.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/wire.rs
  crates/kitsune_p2p/types/src/config.rs
  crates/kitsune_p2p/types/src/tx2/tx2_api.rs
Labels: please-one-approval
