Repository holochain/holochain, pull requests merged in 2021-01, with the labels that each got.

#577 [TK-06964] convert constants to tuning_params in config
  Cargo.lock
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_conductor_api/src/config/conductor.rs
  crates/kitsune_p2p/kitsune_p2p/src/config.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/bootstrap.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
Labels: please-one-approval

#578 [TK-06456] add wait for ops to inline zome
  crates/holochain/src/test_utils/cool/cool_cell.rs
  crates/holochain/tests/inline_zome_sketch.rs
  crates/holochain/tests/multi_conductor.rs
Labels: please-one-approval, tiny

#579 [TK-06910] check for op count consistency
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/wire.rs
Labels: please-one-approval

#580 [TK-06987] Limit amount of publishes for an op
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
Labels: please-one-approval, tiny

#582 Add RegisterDna to conductor api and allow InstallApp to take a hash
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
  crates/holochain/src/fixt.rs
  crates/holochain/tests/websocket.rs
  crates/holochain_conductor_api/src/admin_interface.rs
  crates/holochain_types/src/app.rs
  crates/holochain_types/src/dna.rs
Labels: please-two-approvals

#583 Adds automatic consistency to tests
  crates/holochain/src/test_utils.rs
  crates/holochain/src/test_utils/cool/cool_conductor.rs
  crates/holochain/tests/agent_scaling.rs
Labels: please-one-approval

#586 Fix bug with gets
  .gitignore
  crates/holochain/tests/inline_zome_sketch.rs
  crates/holochain_cascade/src/lib.rs
Labels: bug

#584 [TK-06988] Adds network stats to kitsune
  Cargo.lock
  Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/test.rs
  crates/kitsune_p2p/kitsune_p2p/src/types.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/metrics.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/transport.rs
Labels: please-one-approval

#590 Fix bug in RegisterDna where uuid and props only honored in Hash dna source
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
Labels: please-one-approval

#587 [TK-07046][TK-07047] hc
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/hc/Cargo.toml
  crates/hc/README.md
  crates/hc/examples/setup_5_properties.rs
  crates/hc/src/bin/hc.rs
  crates/hc/src/calls.rs
  crates/hc/src/cmds.rs
  crates/hc/src/config.rs
  crates/hc/src/dna.rs
  crates/hc/src/generate.rs
  crates/hc/src/lib.rs
  crates/hc/src/ports.rs
  crates/hc/src/run.rs
  crates/hc/src/save.rs
  crates/hc/src/setups.rs
  crates/hc/tests/cli.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain_conductor_api/Cargo.toml
Labels: please-two-approvals

#602 [TK-07330] don't error out on req_proxy errors
  crates/kitsune_p2p/proxy/src/inner_listen.rs
  crates/kitsune_p2p/proxy/tests/no_proxy.rs
Labels: please-one-approval

#612 [TK-07459] Proxy Metrics
  Cargo.lock
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-proxy/main.rs
  crates/kitsune_p2p/proxy/src/bin/proxy-cli.rs
  crates/kitsune_p2p/proxy/src/bin/proxy-stress.rs
  crates/kitsune_p2p/proxy/src/inner_listen.rs
  crates/kitsune_p2p/proxy/src/lib.rs
  crates/kitsune_p2p/proxy/src/tls_cli.rs
  crates/kitsune_p2p/proxy/src/tls_srv.rs
  crates/kitsune_p2p/proxy/src/tls_tests.rs
  crates/kitsune_p2p/proxy/src/wire_read.rs
  crates/kitsune_p2p/proxy/src/wire_write.rs
  crates/kitsune_p2p/transport_quic/src/lib.rs
  crates/kitsune_p2p/transport_quic/src/listener.rs
  crates/kitsune_p2p/transport_quic/src/test.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/async_lazy.rs
  crates/kitsune_p2p/types/src/lib.rs
  crates/kitsune_p2p/types/src/metrics.rs
  crates/kitsune_p2p/types/src/transport_mem.rs
  crates/kitsune_p2p/types/src/transport_pool.rs
Labels: please-one-approval
