Repository holochain/holochain, pull requests merged in 2021-03, with the labels that each got.

#596 [B-03724] Ghost Websocket
  Cargo.lock
  crates/hc_bundle/Cargo.toml
  crates/hc_sandbox/src/calls.rs
  crates/hc_sandbox/src/lib.rs
  crates/hc_sandbox/src/ports.rs
  crates/hc_sandbox/tests/cli.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/interface/error.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/tests/speed_tests.rs
  crates/holochain/tests/test_utils.rs
  crates/holochain/tests/websocket.rs
  crates/holochain_websocket/Cargo.toml
  crates/holochain_websocket/README.md
  crates/holochain_websocket/benches/bench.rs
  crates/holochain_websocket/examples/docs.rs
  crates/holochain_websocket/examples/echo.rs
  crates/holochain_websocket/examples/echo_client.rs
  crates/holochain_websocket/examples/echo_server.rs
  crates/holochain_websocket/examples/nodejs_echo_client/.gitignore
  crates/holochain_websocket/examples/nodejs_echo_client/nodejs_echo_client.js
  crates/holochain_websocket/examples/nodejs_echo_client/package-lock.json
  crates/holochain_websocket/src/error.rs
  crates/holochain_websocket/src/lib.rs
  crates/holochain_websocket/src/task_dispatch_incoming.rs
  crates/holochain_websocket/src/task_socket_sink.rs
  crates/holochain_websocket/src/task_socket_stream.rs
  crates/holochain_websocket/src/util.rs
  crates/holochain_websocket/src/websocket.rs
  crates/holochain_websocket/src/websocket_listener.rs
  crates/holochain_websocket/src/websocket_receiver.rs
  crates/holochain_websocket/src/websocket_sender.rs
  crates/holochain_websocket/tests/integration.rs
Labels: please-two-approvals

#675 hc can now handle bundles
  Cargo.lock
  crates/hc/src/lib.rs
  crates/hc_bundle/src/cli.rs
  crates/hc_bundle/src/packing.rs
  crates/hc_bundle/tests/fixtures/my-app/happ.yaml
  crates/hc_bundle/tests/test_cli.rs
  crates/hc_sandbox/Cargo.toml
  crates/hc_sandbox/examples/setup_5.rs
  crates/hc_sandbox/examples/setup_5_properties.rs
  crates/hc_sandbox/src/bundles.rs
  crates/hc_sandbox/src/calls.rs
  crates/hc_sandbox/src/cli.rs
  crates/hc_sandbox/src/lib.rs
  crates/hc_sandbox/src/run.rs
  crates/hc_sandbox/src/sandbox.rs
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/error.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/conductor/state.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/src/test_utils/sweetest/sweet_conductor.rs
  crates/holochain/tests/ser_regression.rs
  crates/holochain/tests/speed_tests.rs
  crates/holochain_conductor_api/src/admin_interface.rs
  crates/holochain_conductor_api/src/config/interface.rs
  crates/holochain_types/src/dna/dna_manifest.rs
Labels: please-one-approval

#686 Check before doing genesis
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/core/workflow/genesis_workflow.rs
  crates/holochain/src/test_utils.rs
Labels: hot fix

#620 expose additional tuning params
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain_conductor_api/src/config/conductor.rs
  crates/kitsune_p2p/kitsune_p2p/src/config.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-proxy/main.rs
  crates/kitsune_p2p/proxy/src/bin/proxy-cli.rs
  crates/kitsune_p2p/proxy/src/bin/proxy-stress.rs
  crates/kitsune_p2p/proxy/src/config.rs
  crates/kitsune_p2p/proxy/src/inner_listen.rs
  crates/kitsune_p2p/proxy/src/tls_tests.rs
  crates/kitsune_p2p/proxy/tests/no_proxy.rs
  crates/kitsune_p2p/proxy/tests/proxy_integration.rs
  crates/kitsune_p2p/types/src/config.rs
  crates/kitsune_p2p/types/src/lib.rs
Labels: please-one-approval

#688 fix multiple port 0 app interfaces
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/state.rs
Labels: hot fix

#690 [TK-08313] fix hc indecies and benches
  crates/hc_sandbox/src/ports.rs
  crates/hc_sandbox/src/save.rs
  crates/holochain/benches/bench.rs
  crates/holochain_websocket/benches/bench.rs
Labels: please-one-approval, tiny

#691 Make publish not fail on failed send
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
Labels: hot fix

#694 [D-01205] fix flaky tests
  Cargo.lock
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/handle.rs
  crates/holochain/src/conductor/state.rs
  crates/holochain/src/core/ribosome/host_fn/create.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/local_network_tests.rs
  crates/holochain/src/test_utils/sweetest/sweet_conductor.rs
  crates/holochain/tests/inline_zome_spec.rs
  crates/holochain/tests/multi_conductor.rs
  crates/holochain_state/src/metadata/links_test.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/test_utils/wasm/build.rs
  nix/pkgs/core.nix
Labels: please-one-approval

#684 [B-01122] Validation Receipts
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/cell/error.rs
  crates/holochain/src/core/queue_consumer.rs
  crates/holochain/src/core/queue_consumer/integrate_dht_ops_consumer.rs
  crates/holochain/src/core/queue_consumer/validation_receipt_consumer.rs
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/workflow.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/error.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow/test.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/chain_test.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow/tests.rs
  crates/holochain_state/src/dht_op_integration.rs
  crates/holochain_state/src/validation_db.rs
  crates/holochain_state/src/validation_receipts_db.rs
Labels: please-one-approval

#666 [B-03964] Arc length targeting
  Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/p2p_store.rs
  crates/holochain/tests/dht_arc.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/agent_store.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/dht_arc.rs
  crates/kitsune_p2p/types/src/dht_arc/gaps.rs
  crates/kitsune_p2p/types/src/dht_arc/tests.rs
Labels: please-two-approvals

#696 Fix feature flag
  crates/holochain/Cargo.toml
Labels: hot fix

#643 Adds more testing diagnostics
  crates/holochain/src/local_network_tests.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/src/test_utils/sweetest/sweet_conductor.rs
  crates/holochain/src/test_utils/sweetest/sweet_dna.rs
  crates/holochain/tests/multi_conductor.rs
  crates/holochain_zome_types/src/signal.rs
Labels: please-one-approval

#703 additional tx2 utils updates
  crates/kitsune_p2p/types/src/tx2/tx2_utils.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/active.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/logic_chan.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/mem_chan.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/notify_all.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/t_chan.rs
Labels: please-one-approval

#698 More convenient wait_for_any-based macros
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/core/ribosome/host_fn/remote_signal.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow/tests.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/src/test_utils/wait_for_any.rs
Labels: please-one-approval

#709 better async_lazy
  crates/kitsune_p2p/types/src/async_lazy.rs
Labels: please-one-approval

#695 [B-04064] fail early when workflows exit
  crates/holochain/src/bin/holochain/main.rs
  crates/holochain/src/conductor/cell/test.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/conductor/manager/error.rs
  crates/holochain/src/conductor/manager/mod.rs
  crates/holochain/src/core/queue_consumer.rs
  crates/holochain/src/core/ribosome/host_fn/call_remote.rs
  crates/holochain/src/core/ribosome/host_fn/create.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/call_zome_workflow/validation_test.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/chain_test.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain/src/local_network_tests.rs
  crates/holochain/src/test_utils/conductor_setup.rs
  crates/holochain/src/test_utils/sweetest/sweet_conductor.rs
  crates/holochain/tests/network_tests.rs
  crates/holochain/tests/ser_regression.rs
  crates/holochain/tests/speed_tests.rs
Labels: please-one-approval

#715 Fix bug in integration workflow
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
Labels: hot fix

#712 fix command line messages
  crates/hc_sandbox/src/bundles.rs
Labels: please-one-approval

#722 [TK-08588] Old proxy benchmark
  Cargo.lock
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/proxy/benches/old_proxy_thru.rs
Labels: please-one-approval
