Repository holochain/holochain, pull requests merged in 2022-07, with the labels that each got.

#1468 Merge release-20220701.181019 back into develop
  CHANGELOG.md
  Cargo.lock
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/Cargo.toml
  crates/hc_sandbox/CHANGELOG.md
  crates/hc_sandbox/Cargo.toml
  crates/hdk/CHANGELOG.md
  crates/hdk/Cargo.toml
  crates/hdk_derive/CHANGELOG.md
  crates/hdk_derive/Cargo.toml
  crates/holo_hash/CHANGELOG.md
  crates/holo_hash/Cargo.toml
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_cascade/Cargo.toml
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_deterministic_integrity/CHANGELOG.md
  crates/holochain_deterministic_integrity/Cargo.toml
  crates/holochain_integrity_types/CHANGELOG.md
  crates/holochain_integrity_types/Cargo.toml
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_keystore/Cargo.toml
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_p2p/Cargo.toml
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_state/CHANGELOG.md
  crates/holochain_state/Cargo.toml
  crates/holochain_types/CHANGELOG.md
  crates/holochain_types/Cargo.toml
  crates/holochain_zome_types/CHANGELOG.md
  crates/holochain_zome_types/Cargo.toml
  crates/kitsune_p2p/bootstrap/Cargo.toml
  crates/kitsune_p2p/dht/CHANGELOG.md
  crates/kitsune_p2p/dht/Cargo.toml
  crates/kitsune_p2p/dht_arc/CHANGELOG.md
  crates/kitsune_p2p/dht_arc/Cargo.toml
  crates/kitsune_p2p/direct/Cargo.toml
  crates/kitsune_p2p/direct_api/Cargo.toml
  crates/kitsune_p2p/direct_test/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/proxy/CHANGELOG.md
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/timestamp/CHANGELOG.md
  crates/kitsune_p2p/timestamp/Cargo.toml
  crates/kitsune_p2p/transport_quic/CHANGELOG.md
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/types/CHANGELOG.md
  crates/kitsune_p2p/types/Cargo.toml
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm/Cargo.toml
  crates/test_utils/wasm_common/CHANGELOG.md
  crates/test_utils/wasm_common/Cargo.toml
Labels: release, autoupdate:opt-in

#1443 Docs/hdi
  crates/hdk/CHANGELOG.md
  crates/hdk/src/lib.rs
  crates/holochain_deterministic_integrity/CHANGELOG.md
  crates/holochain_deterministic_integrity/src/lib.rs
  crates/holochain_integrity_types/src/lib.rs
  crates/holochain_types/src/dna/dna_manifest/dna_manifest_v1.rs
Labels: documentation

#1474 Merge release-20220706.013407 back into develop
  CHANGELOG.md
  Cargo.lock
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/Cargo.toml
  crates/hc_sandbox/CHANGELOG.md
  crates/hc_sandbox/Cargo.toml
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_cascade/Cargo.toml
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_p2p/Cargo.toml
  crates/holochain_state/CHANGELOG.md
  crates/holochain_state/Cargo.toml
  crates/holochain_types/CHANGELOG.md
  crates/holochain_types/Cargo.toml
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm/Cargo.toml
Labels: release, autoupdate:opt-in

#1482 Merge release-20220710.155915 back into develop
  CHANGELOG.md
  Cargo.lock
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/Cargo.toml
  crates/hc_sandbox/CHANGELOG.md
  crates/hc_sandbox/Cargo.toml
  crates/hdk/CHANGELOG.md
  crates/hdk/Cargo.toml
  crates/hdk/README.md
  crates/hdk_derive/CHANGELOG.md
  crates/hdk_derive/Cargo.toml
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_cascade/Cargo.toml
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_deterministic_integrity/CHANGELOG.md
  crates/holochain_deterministic_integrity/Cargo.toml
  crates/holochain_integrity_types/CHANGELOG.md
  crates/holochain_integrity_types/Cargo.toml
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_keystore/Cargo.toml
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_p2p/Cargo.toml
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_state/CHANGELOG.md
  crates/holochain_state/Cargo.toml
  crates/holochain_types/CHANGELOG.md
  crates/holochain_types/Cargo.toml
  crates/holochain_zome_types/CHANGELOG.md
  crates/holochain_zome_types/Cargo.toml
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm/Cargo.toml
  crates/test_utils/wasm_common/CHANGELOG.md
  crates/test_utils/wasm_common/Cargo.toml
Labels: release, autoupdate:opt-in

#1487 Merge release-20220713.013021 back into develop
  CHANGELOG.md
  Cargo.lock
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/Cargo.toml
  crates/hc_sandbox/CHANGELOG.md
  crates/hc_sandbox/Cargo.toml
  crates/hdi/CHANGELOG.md
  crates/hdi/Cargo.toml
  crates/hdk/CHANGELOG.md
  crates/hdk/Cargo.toml
  crates/hdk/README.md
  crates/hdk_derive/CHANGELOG.md
  crates/hdk_derive/Cargo.toml
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_cascade/Cargo.toml
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_keystore/Cargo.toml
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_p2p/Cargo.toml
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_state/CHANGELOG.md
  crates/holochain_state/Cargo.toml
  crates/holochain_types/CHANGELOG.md
  crates/holochain_types/Cargo.toml
  crates/holochain_zome_types/CHANGELOG.md
  crates/holochain_zome_types/Cargo.toml
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm/Cargo.toml
  crates/test_utils/wasm_common/CHANGELOG.md
  crates/test_utils/wasm_common/Cargo.toml
Labels: release, autoupdate:opt-in

#1500 update(github-actions): bump cachix and its action
  .github/workflows/release-prepare.yml
  .github/workflows/release.yml
Labels: autorebase:opt-in
