Repository holochain/holochain, pull requests merged in 2022-12, with the labels that each got.

#1691 fix(release): clarify branch argument descriptions
  .github/workflows/release.yml
Labels: autorebase:opt-in

#1709 Merge release-20221209.233622 back into develop-0.1
  CHANGELOG.md
  Cargo.lock
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/Cargo.toml
Labels: release, autoupdate:opt-in

#1711 Merge release-20221210.021647 back into develop-0.1
  CHANGELOG.md
  Cargo.lock
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/Cargo.toml
Labels: release, autoupdate:opt-in

#1712 Merge release-20221210.030408 back into develop-0.1
  CHANGELOG.md
  Cargo.lock
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
Labels: release, autoupdate:opt-in

#1713 Merge release-20221210.032037 back into develop-0.1
  CHANGELOG.md
  Cargo.lock
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
Labels: release, autoupdate:opt-in

#1714 Merge release-20221210.033526 back into develop-0.1
  CHANGELOG.md
  Cargo.lock
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
Labels: release, autoupdate:opt-in

#1549 addressing API serialization inconsistency
  crates/holochain_websocket/src/lib.rs
Labels: protected
