Repository holochain/holochain, pull requests merged in 2022-06, with the labels that each got.

#1401 Merge release-20220601.012853 back into develop
  CHANGELOG.md
  Cargo.lock
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/Cargo.toml
  crates/hc_sandbox/CHANGELOG.md
  crates/hc_sandbox/Cargo.toml
  crates/hdk/CHANGELOG.md
  crates/hdk/Cargo.toml
  crates/hdk_derive/CHANGELOG.md
  crates/hdk_derive/Cargo.toml
  crates/holo_hash/CHANGELOG.md
  crates/holo_hash/Cargo.toml
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_cascade/Cargo.toml
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_deterministic_integrity/CHANGELOG.md
  crates/holochain_deterministic_integrity/Cargo.toml
  crates/holochain_integrity_types/CHANGELOG.md
  crates/holochain_integrity_types/Cargo.toml
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_keystore/Cargo.toml
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_p2p/Cargo.toml
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_state/CHANGELOG.md
  crates/holochain_state/Cargo.toml
  crates/holochain_types/CHANGELOG.md
  crates/holochain_types/Cargo.toml
  crates/holochain_websocket/CHANGELOG.md
  crates/holochain_websocket/Cargo.toml
  crates/holochain_zome_types/CHANGELOG.md
  crates/holochain_zome_types/Cargo.toml
  crates/kitsune_p2p/direct/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm/Cargo.toml
  crates/test_utils/wasm_common/CHANGELOG.md
  crates/test_utils/wasm_common/Cargo.toml
Labels: release, autoupdate:opt-in

#1408 ci(circleci): run slow and standard tests only with nextest
  .circleci/config.yml
Labels: autorebase:opt-in

#1411 Merge release-20220608.011447 back into develop
  CHANGELOG.md
  Cargo.lock
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/Cargo.toml
  crates/hc_sandbox/CHANGELOG.md
  crates/hc_sandbox/Cargo.toml
  crates/hdk/CHANGELOG.md
  crates/hdk/Cargo.toml
  crates/hdk/README.md
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_cascade/Cargo.toml
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_keystore/Cargo.toml
  crates/holochain_keystore/README.md
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_p2p/Cargo.toml
  crates/holochain_state/CHANGELOG.md
  crates/holochain_state/Cargo.toml
  crates/holochain_types/CHANGELOG.md
  crates/holochain_types/Cargo.toml
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm/Cargo.toml
  crates/test_utils/wasm_common/CHANGELOG.md
  crates/test_utils/wasm_common/Cargo.toml
Labels: release, autoupdate:opt-in

#1403 docs(repo-readme): refer to developer.holochain.org for dev tool setup
  CHANGELOG.md
  README.md
Labels: documentation

#1418 Docs/bring out init fn
  README.md
  crates/hdk/CHANGELOG.md
  crates/hdk/src/lib.rs
  crates/holochain_conductor_api/src/admin_interface.rs
  crates/holochain_zome_types/CHANGELOG.md
  crates/holochain_zome_types/src/init.rs
Labels: documentation

#1428 ci(release): add arg to skip integration testsuite
  .github/workflows/release.yml
Labels: autorebase:opt-in

#1436 chore(CHANGELOGs): backfill for #1386
  crates/hdk/CHANGELOG.md
  crates/holochain/CHANGELOG.md
  crates/holochain_deterministic_integrity/CHANGELOG.md
  crates/holochain_zome_types/CHANGELOG.md
Labels: autorebase:opt-in

#1439 Merge release-20220616.084359 back into develop
  CHANGELOG.md
  Cargo.lock
  crates/fixt/CHANGELOG.md
  crates/fixt/Cargo.toml
  crates/fixt/test/Cargo.toml
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/Cargo.toml
  crates/hc_sandbox/CHANGELOG.md
  crates/hc_sandbox/Cargo.toml
  crates/hdk/CHANGELOG.md
  crates/hdk/Cargo.toml
  crates/hdk/README.md
  crates/hdk_derive/CHANGELOG.md
  crates/hdk_derive/Cargo.toml
  crates/holo_hash/CHANGELOG.md
  crates/holo_hash/Cargo.toml
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_cascade/Cargo.toml
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_deterministic_integrity/CHANGELOG.md
  crates/holochain_deterministic_integrity/Cargo.toml
  crates/holochain_integrity_types/CHANGELOG.md
  crates/holochain_integrity_types/Cargo.toml
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_keystore/Cargo.toml
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_p2p/Cargo.toml
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_state/CHANGELOG.md
  crates/holochain_state/Cargo.toml
  crates/holochain_types/CHANGELOG.md
  crates/holochain_types/Cargo.toml
  crates/holochain_zome_types/CHANGELOG.md
  crates/holochain_zome_types/Cargo.toml
  crates/kitsune_p2p/bootstrap/Cargo.toml
  crates/kitsune_p2p/direct/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/mr_bundle/CHANGELOG.md
  crates/mr_bundle/Cargo.toml
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm/Cargo.toml
  crates/test_utils/wasm_common/CHANGELOG.md
  crates/test_utils/wasm_common/Cargo.toml
Labels: release, autoupdate:opt-in

#1438 ci(release): ignore cachix errors
  .github/workflows/release-prepare.yml
  .github/workflows/release.yml
Labels: autorebase:opt-in

#1455 fix(test): adjust sys_validate to changes
  crates/holochain/src/core/sys_validate.rs
Labels: autorebase:opt-in

#1456 Merge release-20220622.133046 back into develop
  CHANGELOG.md
  Cargo.lock
  crates/fixt/CHANGELOG.md
  crates/fixt/Cargo.toml
  crates/fixt/test/Cargo.toml
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/Cargo.toml
  crates/hc_sandbox/CHANGELOG.md
  crates/hc_sandbox/Cargo.toml
  crates/hdk/CHANGELOG.md
  crates/hdk/Cargo.toml
  crates/hdk_derive/CHANGELOG.md
  crates/hdk_derive/Cargo.toml
  crates/holo_hash/CHANGELOG.md
  crates/holo_hash/Cargo.toml
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_cascade/Cargo.toml
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_deterministic_integrity/CHANGELOG.md
  crates/holochain_deterministic_integrity/Cargo.toml
  crates/holochain_integrity_types/CHANGELOG.md
  crates/holochain_integrity_types/Cargo.toml
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_keystore/Cargo.toml
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_p2p/Cargo.toml
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_state/CHANGELOG.md
  crates/holochain_state/Cargo.toml
  crates/holochain_types/CHANGELOG.md
  crates/holochain_types/Cargo.toml
  crates/holochain_zome_types/CHANGELOG.md
  crates/holochain_zome_types/Cargo.toml
  crates/kitsune_p2p/bootstrap/Cargo.toml
  crates/kitsune_p2p/dht_arc/CHANGELOG.md
  crates/kitsune_p2p/dht_arc/Cargo.toml
  crates/kitsune_p2p/direct/Cargo.toml
  crates/kitsune_p2p/direct_api/Cargo.toml
  crates/kitsune_p2p/direct_test/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/proxy/CHANGELOG.md
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/timestamp/CHANGELOG.md
  crates/kitsune_p2p/timestamp/Cargo.toml
  crates/kitsune_p2p/transport_quic/CHANGELOG.md
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/types/CHANGELOG.md
  crates/kitsune_p2p/types/Cargo.toml
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm/Cargo.toml
  crates/test_utils/wasm_common/CHANGELOG.md
  crates/test_utils/wasm_common/Cargo.toml
Labels: release, autoupdate:opt-in

#1465 Merge release-20220629.012044 back into develop
  CHANGELOG.md
  Cargo.lock
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/Cargo.toml
  crates/hc_sandbox/CHANGELOG.md
  crates/hc_sandbox/Cargo.toml
  crates/hdk/CHANGELOG.md
  crates/hdk/Cargo.toml
  crates/hdk_derive/CHANGELOG.md
  crates/hdk_derive/Cargo.toml
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_cascade/Cargo.toml
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_deterministic_integrity/CHANGELOG.md
  crates/holochain_deterministic_integrity/Cargo.toml
  crates/holochain_integrity_types/CHANGELOG.md
  crates/holochain_integrity_types/Cargo.toml
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_keystore/Cargo.toml
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_p2p/Cargo.toml
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_state/CHANGELOG.md
  crates/holochain_state/Cargo.toml
  crates/holochain_types/CHANGELOG.md
  crates/holochain_types/Cargo.toml
  crates/holochain_zome_types/CHANGELOG.md
  crates/holochain_zome_types/Cargo.toml
  crates/kitsune_p2p/bootstrap/Cargo.toml
  crates/kitsune_p2p/direct/Cargo.toml
  crates/kitsune_p2p/direct_test/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/proxy/CHANGELOG.md
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/transport_quic/CHANGELOG.md
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/types/CHANGELOG.md
  crates/kitsune_p2p/types/Cargo.toml
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm/Cargo.toml
  crates/test_utils/wasm_common/CHANGELOG.md
  crates/test_utils/wasm_common/Cargo.toml
Labels: release, autoupdate:opt-in
