Repository holochain/holochain, pull requests merged in 2023-09, with the labels that each got.

#2732 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2735 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2736 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2738 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2699 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2744 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2745 Reduce the impact of the chc API changes
  crates/holochain/Cargo.toml
Labels: ShouldBackport/0.2

#2750 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2754 fix(github/workflows/release-prepare): use args seperator
  .github/workflows/release-prepare.yml
Labels: ShouldBackport/0.1, ShouldBackport/0.2

#2756 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2760 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2755 fix(github/workflows/release-prepare): remove redudant readme generation, fix cargo-sweep (again)
  .github/workflows/release-prepare.yml
Labels: ShouldBackport/0.1, ShouldBackport/0.2

#2767 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2768 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2770 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2772 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2774 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2778 Fix warnings for `cargo check`
  crates/holochain/tests/graft_records_onto_source_chain.rs
Labels: ShouldBackport/0.2

#2763 Remove unused regions
  crates/kitsune_p2p/fetch/src/lib.rs
  crates/kitsune_p2p/fetch/src/pool.rs
  crates/kitsune_p2p/fetch/src/test_utils.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/fetch/fetch_task.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/meta_net_task.rs
Labels: autorebase:opt-in, ShouldBackport/0.2

#2748 feat(tests/holonix): hc-sandbox create and run
  crates/hc_sandbox/src/cli.rs
  holonix/test/hc-sandbox.bats
  nix/modules/holonix-integration-test.nix
Labels: ShouldBackport/0.1, ShouldBackport/0.2

#2779 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2776 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2765 Remove unused deps and upgrade others
  Cargo.lock
  crates/kitsune_p2p/block/Cargo.toml
  crates/kitsune_p2p/bootstrap/Cargo.toml
  crates/kitsune_p2p/dht/Cargo.toml
  crates/kitsune_p2p/dht_arc/Cargo.toml
  crates/kitsune_p2p/fetch/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/mdns/Cargo.toml
  crates/kitsune_p2p/mdns/src/lib.rs
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/kitsune_p2p/proxy/src/proxy_url.rs
  crates/kitsune_p2p/timestamp/Cargo.toml
  crates/kitsune_p2p/transport_quic/Cargo.toml
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#2785 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2781 Add patch release example
  docs/release/release.md
Labels: autorebase:opt-in

#2791 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2790 update source 'versions/0_1' on branch 'develop'
  flake.lock
  versions/0_1/flake.lock
Labels: autorebase:opt-in

#2798 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2799 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2800 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2804 Add prompt to rustDev shell
  nix/modules/devShells.nix
Labels: autorebase:opt-in

#2807 update source 'versions/0_2' on branch 'develop'
  versions/0_2/flake.lock
Labels: autorebase:opt-in

#2808 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2806 update source 'versions/0_1' on branch 'develop'
  flake.lock
  versions/0_1/flake.lock
Labels: autorebase:opt-in

#2809 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2811 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2814 update source 'versions/0_2' on branch 'develop'
  versions/0_2/flake.lock
Labels: autorebase:opt-in

#2821 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2815 update source 'versions/0_1' on branch 'develop'
  flake.lock
  versions/0_1/flake.lock
Labels: autorebase:opt-in

#2824 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2823 Update weekly to 0.3.0-beta-dev.18
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#2826 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2775 Add new signal tests using rendezvous
  crates/holochain/tests/integration.rs
  crates/holochain/tests/signals/mod.rs
Labels: autorebase:opt-in

#2830 update source 'versions/0_1' on branch 'develop'
  flake.lock
  versions/0_1/flake.lock
Labels: autorebase:opt-in

#2831 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2834 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2837 Prevent silent exit on cannot call
  crates/hc_sandbox/src/calls.rs
Labels: autorebase:opt-in

#2836 Update doc for the force option on the sandbox
  crates/hc_sandbox/src/cli.rs
Labels: autorebase:opt-in

#2841 update source 'versions/0_2' on branch 'develop'
  versions/0_2/flake.lock
Labels: autorebase:opt-in

#2827 fix(send-signal): send error after conductor restart
  crates/holochain/CHANGELOG.md
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/interface.rs
  crates/holochain/tests/send_signal.rs
  crates/holochain_conductor_api/src/admin_interface.rs
  crates/holochain_conductor_api/src/app_interface.rs
Labels: ShouldBackport/0.1, ShouldBackport/0.2

#2840 Extract and test pending validation receipts query
  crates/holochain/src/core/workflow/validation_receipt_workflow.rs
  crates/holochain_state/src/validation_receipts.rs
Labels: autorebase:opt-in, ShouldBackport/0.2

#2842 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2833 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2846 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2853 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2860 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2861 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2864 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in
