Repository holochain/holochain, pull requests merged in 2023-06, with the labels that each got.

#2448 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2449 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2451 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2453 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2456 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2457 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2458 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2459 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2465 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2472 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2473 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2478 Prepare for release of 0.1.5
  .github/workflows/release-prepare.yml
  crates/fixt/CHANGELOG.md
  crates/fixt/test/CHANGELOG.md
  crates/hc/CHANGELOG.md
  crates/hc_bundle/CHANGELOG.md
  crates/hc_sandbox/CHANGELOG.md
  crates/hdi/CHANGELOG.md
  crates/hdk/CHANGELOG.md
  crates/hdk_derive/CHANGELOG.md
  crates/holo_hash/CHANGELOG.md
  crates/holochain/CHANGELOG.md
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_integrity_types/CHANGELOG.md
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_state/CHANGELOG.md
  crates/holochain_types/CHANGELOG.md
  crates/holochain_util/CHANGELOG.md
  crates/holochain_websocket/CHANGELOG.md
  crates/holochain_zome_types/CHANGELOG.md
  crates/kitsune_p2p/bootstrap/CHANGELOG.md
  crates/kitsune_p2p/dht/CHANGELOG.md
  crates/kitsune_p2p/dht_arc/CHANGELOG.md
  crates/kitsune_p2p/fetch/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/mdns/CHANGELOG.md
  crates/kitsune_p2p/proxy/CHANGELOG.md
  crates/kitsune_p2p/timestamp/CHANGELOG.md
  crates/kitsune_p2p/transport_quic/CHANGELOG.md
  crates/kitsune_p2p/types/CHANGELOG.md
  crates/mock_hdi/CHANGELOG.md
  crates/mr_bundle/CHANGELOG.md
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm_common/CHANGELOG.md
Labels: autorebase:opt-in

#2461 Fix connection limiting in the admin websocket
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/tests/websocket/mod.rs
Labels: autorebase:opt-in, ShouldBackport/0.2

#2483 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2485 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2482 Update 0_1 to 0.1.5
  versions/0_1/flake.lock
  versions/0_1/flake.nix
Labels: autorebase:opt-in

#2450 Flamegraph in memory
  crates/holochain/tests/speed_tests/mod.rs
  crates/holochain_trace/src/flames.rs
  crates/holochain_trace/src/lib.rs
  crates/holochain_trace/src/writer.rs
Labels: autorebase:opt-in

#2487 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2488 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2489 update source 'versions/0_1' on branch 'develop'
  flake.lock
  versions/0_1/flake.lock
Labels: autorebase:opt-in

#2490 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2491 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2492 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2494 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2495 update source 'versions/0_1' on branch 'develop'
  flake.lock
  versions/0_1/flake.lock
Labels: autorebase:opt-in

#2496 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2468 Backport to 0.2 bump tx5
  Cargo.lock
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
Labels: autorebase:opt-in

#2499 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2500 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2501 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2504 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2505 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2507 Allow use of loopback
  crates/holochain/src/sweettest/sweet_conductor_config_rendezvous.rs
Labels: autorebase:opt-in

#2419 Retry network join on startup
  Cargo.lock
  crates/holochain/src/conductor/cell/gossip_test.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/tests.rs
Labels: autorebase:opt-in, autorebase:non-rebaseable, ShouldBackport/0.1, ShouldBackport/0.2

#2508 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2509 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2511 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2512 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2515 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2516 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2493 Log more context during validation
  crates/holochain/src/core/queue_consumer.rs
  crates/holochain/src/core/ribosome/real_ribosome.rs
Labels: autorebase:opt-in, ShouldBackport/0.2

#2518 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2523 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2522 Give up waiting if it takes too long to get a db permit
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/kitsune_host_impl.rs
  crates/holochain/src/conductor/p2p_agent_store.rs
  crates/holochain_cascade/src/lib.rs
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_sqlite/src/db.rs
  crates/holochain_sqlite/src/db/p2p_agent_store/p2p_test.rs
  crates/holochain_sqlite/src/db/p2p_metrics/p2p_metrics_test.rs
  crates/holochain_sqlite/src/error.rs
Labels: autorebase:opt-in

#2524 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2525 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2452 Add websocket test for heavy use
  crates/holochain_websocket/Cargo.toml
  crates/holochain_websocket/tests/integration.rs
Labels: autorebase:opt-in

#2526 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2282 [DOCS] HDK callbacks should accept an argument which can be deserialized
  crates/hdk/README.md
Labels: autorebase:opt-in

#2529 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2530 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2527 Holochain performance fixes
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain_cascade/Cargo.toml
  crates/holochain_p2p/Cargo.toml
  crates/holochain_websocket/src/websocket.rs
  crates/holochain_websocket/src/websocket_receiver.rs
  crates/holochain_websocket/src/websocket_sender.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/initiate.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/next_target.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/tests/test_two_nodes.rs
  crates/kitsune_p2p/kitsune_p2p/src/test_util/switchboard/tests.rs
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/tx2/tx2_utils/t_chan.rs
Labels: autorebase:opt-in

#2536 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in
