Repository holochain/holochain, pull requests merged in 2023-01, with the labels that each got.

#1782 Added author to link
  crates/holochain_cascade/src/test_utils/entry_test_data.rs
  crates/holochain_state/src/query/link.rs
  crates/holochain_state/src/query/test_data.rs
  crates/holochain_state/src/query/tests/links_test.rs
  crates/holochain_zome_types/CHANGELOG.md
  crates/holochain_zome_types/src/fixt.rs
  crates/holochain_zome_types/src/link.rs
Labels: NO-MERGE (dependency)

#1800 update holochain-nixpkgs on develop
  nix/sources.json
Labels: release

#1801 update holochain-nixpkgs on develop
  holonix/VERSIONS.md
  nix/sources.json
Labels: release

#1802 update holochain-nixpkgs on develop
  nix/sources.json
Labels: release

#1804 update holochain-nixpkgs on develop
  holonix/VERSIONS.md
  nix/sources.json
Labels: release

#1806 update holochain-nixpkgs on develop
  nix/sources.json
Labels: release

#1808 update holochain-nixpkgs on develop
  nix/sources.json
Labels: release

#1810 update holochain-nixpkgs on develop
  nix/sources.json
Labels: release

#1812 update holochain-nixpkgs on develop
  holonix/VERSIONS.md
  nix/sources.json
Labels: release

#1813 update holochain-nixpkgs on develop
  holonix/VERSIONS.md
  nix/sources.json
Labels: release

#1814 update holochain-nixpkgs on develop
  holonix/VERSIONS.md
  nix/sources.json
Labels: release

#1821 update holochain-nixpkgs on develop
  holonix/VERSIONS.md
  nix/sources.json
Labels: release

#1822 feat(nix): fix nextest derivation for macos
  nix/modules/holochain.nix
  nix/modules/srcCleaned.nix
Labels: autorebase:opt-in

#1830 update holochain-nixpkgs on develop
  nix/sources.json
Labels: release

#1832 update holochain-nixpkgs on develop
  holonix/VERSIONS.md
  nix/sources.json
Labels: release

#1833 update holochain-nixpkgs on develop
  nix/sources.json
Labels: release

#1823 feat(CHANGELOGs): facilitate bump to next minor pre-release
  crates/fixt/CHANGELOG.md
  crates/fixt/test/CHANGELOG.md
  crates/hc/CHANGELOG.md
  crates/hc_bundle/CHANGELOG.md
  crates/hc_sandbox/CHANGELOG.md
  crates/hdi/CHANGELOG.md
  crates/hdk/CHANGELOG.md
  crates/hdk_derive/CHANGELOG.md
  crates/holo_hash/CHANGELOG.md
  crates/holochain/CHANGELOG.md
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_integrity_types/CHANGELOG.md
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_state/CHANGELOG.md
  crates/holochain_types/CHANGELOG.md
  crates/holochain_util/CHANGELOG.md
  crates/holochain_websocket/CHANGELOG.md
  crates/holochain_zome_types/CHANGELOG.md
  crates/kitsune_p2p/bootstrap/CHANGELOG.md
  crates/kitsune_p2p/dht/CHANGELOG.md
  crates/kitsune_p2p/dht_arc/CHANGELOG.md
  crates/kitsune_p2p/fetch/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/mdns/CHANGELOG.md
  crates/kitsune_p2p/proxy/CHANGELOG.md
  crates/kitsune_p2p/timestamp/CHANGELOG.md
  crates/kitsune_p2p/transport_quic/CHANGELOG.md
  crates/kitsune_p2p/types/CHANGELOG.md
  crates/mock_hdi/CHANGELOG.md
  crates/mr_bundle/CHANGELOG.md
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm_common/CHANGELOG.md
Labels: autorebase:opt-in

#1836 update holochain-nixpkgs on develop
  holonix/VERSIONS.md
  nix/sources.json
Labels: release

#1805 Delete authored data from db on cell cleanup after app uninstall
  crates/holochain/CHANGELOG.md
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_sqlite/build.rs
  crates/holochain_sqlite/src/db.rs
  crates/holochain_sqlite/src/schema.rs
  crates/holochain_sqlite/src/schema/tables.rs
  crates/holochain_sqlite/src/sql.rs
  crates/holochain_sqlite/src/sql/cell/schema/0.sql
  crates/holochain_sqlite/src/sql/cell/schema/1-up.sql
  crates/holochain_sqlite/src/sql/cell/schema/1.sql
  crates/holochain_sqlite/src/sql/conductor/schema/0.sql
  crates/holochain_sqlite/src/sql/p2p_agent_store/schema/0.sql
  crates/holochain_sqlite/src/sql/p2p_metrics/schema/0.sql
  crates/holochain_sqlite/src/sql/wasm/schema/0.sql
Labels: NO-MERGE (dependency), ShouldBackport
