Repository holochain/holochain, pull requests merged in 2023-03, with the labels that each got.

#2025 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2031 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2032 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2036 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2037 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2040 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2042 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2043 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2018 specify ?net= flag to bootstrap based on tx5 feature
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/bootstrap.rs
Labels: NO-MERGE (dependency)

#2046 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2028 feat(tests/holonix-tests-integration): trim src and capture test output
  nix/modules/holonix-integration-test.nix
  nix/modules/srcCleaned.nix
Labels: autorebase:opt-in, autorebase:non-rebaseable

#2047 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2050 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2052 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2055 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2057 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2060 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2061 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2065 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2068 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2069 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2070 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2072 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2071 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2074 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2076 chore: change all version suffix to beta-rc
  .github/workflows/release-prepare.yml
  crates/fixt/CHANGELOG.md
  crates/fixt/test/CHANGELOG.md
  crates/hc/CHANGELOG.md
  crates/hc_bundle/CHANGELOG.md
  crates/hc_sandbox/CHANGELOG.md
  crates/hdi/CHANGELOG.md
  crates/hdk/CHANGELOG.md
  crates/hdk_derive/CHANGELOG.md
  crates/holo_hash/CHANGELOG.md
  crates/holochain/CHANGELOG.md
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_integrity_types/CHANGELOG.md
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_state/CHANGELOG.md
  crates/holochain_types/CHANGELOG.md
  crates/holochain_util/CHANGELOG.md
  crates/holochain_websocket/CHANGELOG.md
  crates/holochain_zome_types/CHANGELOG.md
  crates/kitsune_p2p/bin_data/CHANGELOG.md
  crates/kitsune_p2p/block/CHANGELOG.md
  crates/kitsune_p2p/bootstrap/CHANGELOG.md
  crates/kitsune_p2p/dht/CHANGELOG.md
  crates/kitsune_p2p/dht_arc/CHANGELOG.md
  crates/kitsune_p2p/fetch/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/mdns/CHANGELOG.md
  crates/kitsune_p2p/proxy/CHANGELOG.md
  crates/kitsune_p2p/timestamp/CHANGELOG.md
  crates/kitsune_p2p/transport_quic/CHANGELOG.md
  crates/kitsune_p2p/types/CHANGELOG.md
  crates/mock_hdi/CHANGELOG.md
  crates/mr_bundle/CHANGELOG.md
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm_common/CHANGELOG.md
Labels: autorebase:opt-in

#2081 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2090 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2094 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2096 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2092 Differentate between CellMissing and CellDisabled, and other fixes
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/graft_records_onto_source_chain.rs
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain/src/conductor/error.rs
  crates/holochain/src/conductor/manager/mod.rs
  crates/holochain/src/core/ribosome/host_fn/schedule.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow.rs
  crates/holochain/src/sweettest/sweet_conductor.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/src/test_utils/conductor_setup.rs
  crates/holochain/src/test_utils/consistency.rs
  crates/holochain/src/test_utils/host_fn_caller.rs
  crates/holochain/tests/authored_test/mod.rs
  crates/holochain/tests/inline_zome_spec/mod.rs
  crates/holochain/tests/multi_conductor/mod.rs
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_conductor_api/src/admin_interface.rs
  crates/holochain_sqlite/src/sql/cell/schedule/delete_all_ephemeral.sql
  crates/holochain_state/src/mutations.rs
Labels: ShouldBackport

#2103 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2104 chore: re-enable the weekly release schedule
  .github/workflows/release.yml
Labels: autorebase:opt-in

#2097 refactor(zome-call): optimize cap grant verification
  crates/holochain_integrity_types/src/capability/grant.rs
  crates/holochain_state/CHANGELOG.md
  crates/holochain_state/src/mutations.rs
  crates/holochain_state/src/source_chain.rs
  crates/holochain_types/src/sql.rs
Labels: ShouldBackport

#2099 Take `name` out of DnaDefHash
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain/src/conductor/tests/app_info.rs
  crates/holochain/src/sweettest/sweet_app.rs
  crates/holochain_zome_types/CHANGELOG.md
  crates/holochain_zome_types/src/dna_def.rs
Labels: ShouldBackport

#2108 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2109 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2110 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2111 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2112 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2115 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2117 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2121 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2122 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2124 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2128 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2127 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#1976 fix(nix/modules/launcher): add wrapGAppsHook
  containers/ubuntu-podman/Containerfile
  containers/ubuntu-podman/run.sh
  nix/modules/launcher.nix
  scripts/test-hc-launch.sh
Labels: autorebase:opt-in

#2129 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2130 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2132 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2133 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2135 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2137 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2140 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2154 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2142 Fix documentation typos
  crates/holo_hash/README.md
Labels: please-one-approval

#2158 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2159 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2149 fix(release-automation): consider dependency state of all matched crates
  crates/release-automation/src/lib/crate_selection/mod.rs
  crates/release-automation/src/lib/crate_selection/tests/mod.rs
  crates/release-automation/src/lib/release.rs
  crates/release-automation/src/lib/tests/cli.rs
  crates/release-automation/src/lib/tests/workspace_mocker.rs
Labels: ShouldForwardPort

#2161 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in
