Repository holochain/holochain, pull requests merged in 2023-11, with the labels that each got.

#2995 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3000 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3004 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3010 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3011 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3014 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3015 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3020 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2952 Add more metrics for Holochain
  Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/builder.rs
  crates/holochain/src/conductor/metrics.rs
  crates/holochain/src/core.rs
  crates/holochain/src/core/metrics.rs
  crates/holochain/src/core/queue_consumer.rs
  crates/holochain_cascade/Cargo.toml
  crates/holochain_cascade/src/lib.rs
  crates/holochain_cascade/src/metrics.rs
  crates/holochain_metrics/src/dashboards/conductor.json
  crates/holochain_metrics/src/dashboards/database.json
  crates/holochain_metrics/src/lib.rs
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_sqlite/src/db/access.rs
  crates/holochain_sqlite/src/db/guard.rs
  crates/holochain_sqlite/src/db/kind.rs
  crates/holochain_sqlite/src/db/metrics.rs
  crates/holochain_sqlite/src/db/mod.rs
Labels: ShouldBackport/0.2

#3022 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3024 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3026 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3030 update source 'versions/0_2_rc' on branch 'develop'
  versions/0_2_rc/flake.lock
Labels: autorebase:opt-in

#3033 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3032 Fix flaky three way historical gossip test
  crates/hc_demo_cli/src/demo.rs
  crates/holochain/src/conductor/p2p_agent_store.rs
  crates/holochain/src/core/ribosome/host_fn/must_get_action.rs
  crates/holochain/src/core/ribosome/host_fn/must_get_agent_activity.rs
  crates/holochain/src/core/ribosome/host_fn/must_get_entry.rs
  crates/holochain/src/core/ribosome/host_fn/must_get_valid_record.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow/tests.rs
  crates/holochain/src/sweettest/sweet_conductor.rs
  crates/holochain/src/sweettest/sweet_conductor_batch.rs
  crates/holochain/src/sweettest/sweet_conductor_config.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/src/test_utils/hc_stress_test/local_behavior_1.rs
  crates/holochain/src/test_utils/hc_stress_test/local_behavior_2.rs
  crates/holochain/tests/multi_conductor/mod.rs
  crates/holochain/tests/publish/mod.rs
  crates/holochain/tests/send_signal.rs
  crates/holochain/tests/sharded_gossip/mod.rs
  crates/holochain/tests/signals/mod.rs
  crates/holochain/tests/websocket/mod.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/fetch/fetch_task.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/meta_net_task.rs
  crates/kitsune_p2p/types/src/metrics.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: ShouldBackport/0.2

#2689 Remove TxUrl panics
  crates/holochain_sqlite/src/store/p2p_agent_store/p2p_test.rs
  crates/kitsune_p2p/bootstrap/src/random.rs
  crates/kitsune_p2p/bootstrap_client/src/lib.rs
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/src/config.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/next_target.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover/test_search_remotes_covering_basis.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/meta_net.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/proxy/benches/thru.rs
  crates/kitsune_p2p/proxy/examples/cli-chat.rs
  crates/kitsune_p2p/proxy/src/bin/kitsune-p2p-tx2-proxy.rs
  crates/kitsune_p2p/proxy/src/bin/proxy-tx2-cli.rs
  crates/kitsune_p2p/proxy/src/tx2.rs
  crates/kitsune_p2p/transport_quic/src/tx2.rs
  crates/kitsune_p2p/types/benches/api_thru.rs
  crates/kitsune_p2p/types/src/config.rs
  crates/kitsune_p2p/types/src/lib.rs
  crates/kitsune_p2p/types/src/tx2/mem.rs
  crates/kitsune_p2p/types/src/tx2/tx2_adapter.rs
  crates/kitsune_p2p/types/src/tx2/tx2_api.rs
  crates/kitsune_p2p/types/src/tx2/tx2_pool_promote.rs
  crates/kitsune_p2p/types/src/tx2/tx2_utils/tx_url.rs
Labels: ShouldBackport/0.2

#3034 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#678 Add high-level docs for app manifest
  crates/holochain_types/src/app/app_bundle.rs
  crates/holochain_types/src/app/app_manifest.rs
  crates/holochain_types/src/app/app_manifest/app_manifest_v1.rs
Labels: stale

#3038 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2982 Extract batch processing logic from the sys validation workflow
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/validation_batch.rs
  crates/holochain_integrity_types/src/record.rs
Labels: ShouldBackport/0.2

#3042 Add version option to binaries
  crates/hc_bundle/src/cli.rs
  crates/hc_demo_cli/src/demo.rs
  crates/hc_run_local_services/src/lib.rs
  crates/hc_sandbox/src/cli.rs
Labels: ShouldBackport/0.2

#3045 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3049 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3050 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3044 chore(nix/moldOpensslDeps): resolve the src path lazily
  nix/modules/holonix-integration-test.nix
Labels: autoupdate:opt-in

#2967 bump to tx5 version that includes static linking
  Cargo.lock
  crates/hc_run_local_services/Cargo.toml
  crates/holochain/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: ShouldBackport/0.2

#2968 fix(app-validation): retrigger when not all ops were validated
  crates/holochain/CHANGELOG.md
  crates/holochain/src/core/queue_consumer.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow/unit_tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
Labels: ShouldBackport/0.2, TargetRelease/0.2.4

#3054 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3057 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3058 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3023 Sys validation tests for `validate_op`
  crates/holochain/CHANGELOG.md
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/sys_validate/error.rs
  crates/holochain/src/core/sys_validate/tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/validate_op_tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/validation_batch.rs
  crates/holochain_integrity_types/src/record.rs
Labels: ShouldBackport/0.2

#3036 Improvements from investigating zome call timeouts
  crates/holochain_sqlite/src/db/access.rs
  crates/holochain_state/src/host_fn_workspace.rs
  crates/holochain_state/src/query/chain_head.rs
Labels: ShouldBackport/0.2

#3061 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3055 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3060 Rework PeerAgentHistory::current_round
  crates/holochain_diagnostics/src/ui/gossip_dashboard/widgets/gossip_agent_history.rs
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/metrics.rs
Labels: ShouldBackport/0.1, ShouldBackport/0.2

#3067 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3053 fix(app-validation): retrigger when not all ops were validated (#2968)
  crates/holochain/CHANGELOG.md
  crates/holochain/src/core/queue_consumer.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/integrate_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow/unit_tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
Labels: TargetRelease/0.2.4

#3075 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3071 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3079 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3062 Backport #3060 to 0.2
  crates/holochain_diagnostics/src/ui/gossip_dashboard/widgets/gossip_agent_history.rs
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/metrics.rs
Labels: TargetRelease/0.2.4

#3077 fix(source-chain): consider multiple unrestricted cap grants
  crates/holochain_state/CHANGELOG.md
  crates/holochain_state/src/source_chain.rs
Labels: ShouldBackport/0.2, TargetRelease/0.2.4

#3088 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3089 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3093 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in
