Repository holochain/holochain, pull requests merged in 2023-07, with the labels that each got.

#2539 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2540 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2542 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2547 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2549 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2553 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2550 Add weekly version
  .github/workflows/holochain-build-and-test.yml
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#2555 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2557 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2558 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2559 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2561 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2560 Remove other uses of conn_permit
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/kitsune_host_impl.rs
  crates/holochain/src/conductor/p2p_agent_store.rs
  crates/holochain_sqlite/src/db/p2p_agent_store/p2p_test.rs
  crates/holochain_sqlite/src/db/p2p_metrics/p2p_metrics_test.rs
Labels: autorebase:opt-in

#2563 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2566 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2568 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2571 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2574 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2575 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2578 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2585 update source 'versions/0_2' on branch 'pr_version_0_2_update'
  versions/0_2/flake.lock
Labels: autorebase:opt-in

#2588 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2592 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2462 feat(nix/lair): make package args overridable
  nix/modules/lair.nix
Labels: autoupdate:opt-in

#2595 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2476 Filter release tags to current branch
  .github/workflows/release-prepare.yml
  .github/workflows/release.yml
  scripts/ci-gh-release.sh
Labels: ShouldBackport/0.1, ShouldBackport/0.2

#2596 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2598 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2599 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2591 Add more context to InvalidCommit errors on the source chain
  crates/holochain/CHANGELOG.md
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/sys_validate/error.rs
  crates/holochain/src/core/sys_validate/tests.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain_integrity_types/src/action.rs
  crates/holochain_types/src/chain.rs
  crates/holochain_types/src/test_utils/chain.rs
Labels: autorebase:opt-in, ShouldBackport/0.2

#2605 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2601 Bump zome call error level
  crates/holochain/src/core/ribosome/real_ribosome.rs
Labels: ShouldBackport/0.2

#2614 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2617 update source 'versions/0_2' on branch 'develop'
  versions/0_2/flake.lock
Labels: autorebase:opt-in

#2618 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2606 [BACKPORT-0.2] Add more context to InvalidCommit errors on the source chain (#2591)
  crates/holochain/CHANGELOG.md
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/sys_validate/error.rs
  crates/holochain/src/core/sys_validate/tests.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain_integrity_types/src/action.rs
  crates/holochain_types/src/chain.rs
  crates/holochain_types/src/test_utils/chain.rs
Labels: autorebase:opt-in

#2620 Extract and test agent info update task
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space/agent_info_update.rs
Labels: autorebase:opt-in

#2619 [BACKPORT 0.2] Bump zome call error level
  crates/holochain/src/core/ribosome/real_ribosome.rs
Labels: autorebase:opt-in

#2623 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2624 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in
