Repository holochain/holochain, pull requests merged in 2023-12, with the labels that each got.

#3101 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2974 Chore/reduce loglevel of outgoing gossip failure
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip.rs
Labels: ShouldBackport/0.2

#2984 Peer info net stats correlation backport 0.2
  crates/holochain/tests/multi_conductor/mod.rs
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
Labels: TargetRelease/0.2.4

#3106 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3094 Fix clone only running genesis
  crates/holochain/src/conductor/tests/install_app_bundle.rs
  crates/holochain_types/src/app/app_bundle.rs
  crates/test_utils/wasm/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/genesis_self_check_requires_properties/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/genesis_self_check_requires_properties/src/integrity.rs
  crates/test_utils/wasm/wasm_workspace/genesis_self_check_requires_properties/src/lib.rs
Labels: ShouldBackport/0.2

#3105 Reject unknown fields in DNA manfests
  crates/holochain_types/CHANGELOG.md
  crates/holochain_types/src/dna/dna_manifest/dna_manifest_v1.rs
  crates/holochain_types/src/dna/dna_manifest/test.rs
Labels: ShouldBackport/0.2

#3073 Sys validation workflow refactor
  crates/holochain/CHANGELOG.md
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/conductor/graft_records_onto_source_chain.rs
  crates/holochain/src/conductor/space.rs
  crates/holochain/src/core/queue_consumer.rs
  crates/holochain/src/core/queue_consumer/sys_validation_consumer.rs
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/sys_validate/error.rs
  crates/holochain/src/core/sys_validate/tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/initialize_zomes_workflow.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/types.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/validate_op_tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/validation_batch.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs
  crates/holochain/src/sweettest/sweet_conductor_config.rs
  crates/holochain/tests/authored_test/mod.rs
  crates/holochain/tests/multi_conductor/mod.rs
  crates/holochain/tests/sharded_gossip/mod.rs
  crates/holochain_cascade/src/lib.rs
  crates/holochain_conductor_api/src/config/conductor.rs
  crates/holochain_state/src/integrate.rs
Labels: ShouldBackport/0.2

#3109 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3104 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3118 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3116 Hide Timestamp::now() from hdk
  .config/test-args.nix
  crates/hdk/CHANGELOG.md
  crates/hdk/Cargo.toml
  crates/hdk/tests/samples.rs
  crates/hdk/tests/samples/no_timestamp_now.rs
  crates/hdk/tests/samples/no_timestamp_now.stderr
  crates/holochain_integrity_types/Cargo.toml
  crates/holochain_zome_types/Cargo.toml
  crates/kitsune_p2p/block/Cargo.toml
  crates/kitsune_p2p/dht/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/validate_reject_app_types/src/integrity.rs
Labels: ShouldBackport/0.2

#3125 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3126 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3127 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3132 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3135 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3137 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3130 More sys validation tests
  crates/holochain/CHANGELOG.md
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/types.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/validate_op_tests.rs
Labels: ShouldBackport/0.2

#3144 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3134 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3148 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3149 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3150 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3153 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3151 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3155 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3159 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3157 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3163 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in
