Repository holochain/holochain, pull requests merged in 2023-10, with the labels that each got.

#2865 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2866 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2869 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2843 Unit tests for validation receipts
  crates/holochain/src/core/queue_consumer/validation_receipt_consumer.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow/unit_tests.rs
  crates/holochain_zome_types/src/block.rs
Labels: ShouldBackport/0.2

#2855 Make tests run independently per crate
  Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain_cascade/Cargo.toml
  crates/holochain_keystore/src/lib.rs
  crates/holochain_p2p/Cargo.toml
  crates/holochain_p2p/src/lib.rs
  crates/holochain_p2p/src/test.rs
  crates/holochain_state/Cargo.toml
Labels: autorebase:opt-in

#2876 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in, autorebase:non-rebaseable

#2854 feat(nix): minimize rust toolchain size and test hc scaffold integration
  CHANGELOG.md
  holonix/test/scaffolding.bats
  nix/modules/rust.nix
Labels: autoupdate:opt-in

#2886 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in, autorebase:non-rebaseable

#2888 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in, autorebase:non-rebaseable

#2848 Resilience improvements for validation receipts
  crates/holochain/CHANGELOG.md
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow/tests.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow/unit_tests.rs
  crates/holochain/tests/sharded_gossip/mod.rs
  crates/holochain_cascade/src/test_utils.rs
  crates/holochain_p2p/src/lib.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_p2p/src/test.rs
  crates/holochain_p2p/src/types/actor.rs
  crates/holochain_p2p/src/types/event.rs
  crates/holochain_p2p/src/types/mock_network.rs
  crates/holochain_p2p/src/types/wire.rs
  crates/holochain_state/src/mutations.rs
  crates/holochain_state/src/validation_receipts.rs
  crates/holochain_types/src/lib.rs
  crates/holochain_types/src/prelude.rs
  crates/holochain_types/src/validation_receipt.rs
Labels: ShouldBackport/0.2

#2899 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in, autorebase:non-rebaseable

#2910 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in, autorebase:non-rebaseable

#2915 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in, autorebase:non-rebaseable

#2917 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in, autorebase:non-rebaseable

#2918 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in, autorebase:non-rebaseable

#2919 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in, autorebase:non-rebaseable

#2913 Test and fix the `incoming_dht_ops_workflow`
  crates/holochain/CHANGELOG.md
  crates/holochain/src/conductor/space.rs
  crates/holochain/src/core/sys_validate.rs
  crates/holochain/src/core/workflow/countersigning_workflow.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow/incoming_ops_batch.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow/test.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow/tests.rs
Labels: ShouldBackport/0.2

#2926 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2927 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2932 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2931 Stop publishing when enough validation receipts have been received
  crates/holochain/CHANGELOG.md
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow/incoming_ops_batch.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow/tests.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs
  crates/holochain/src/core/workflow/publish_dht_ops_workflow/unit_tests.rs
  crates/holochain/tests/integration.rs
  crates/holochain/tests/publish/mod.rs
Labels: ShouldBackport/0.2

#2938 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2940 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2944 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2950 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2955 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2959 Bump to weekly 0.3-22
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: please-one-approval

#2962 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2954 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2972 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2976 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2977 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2978 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2975 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2981 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2948 adjust bootstrap max_delay from 60 minutes -> 5 minutes
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space/bootstrap_task.rs
  crates/kitsune_p2p/types/src/config.rs
Labels: ShouldBackport/0.2

#2953 augment network stats with holochain agent info correlation
  crates/holochain/tests/multi_conductor/mod.rs
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
Labels: ShouldBackport/0.2

#2986 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2988 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2963 Bump influxive, tx5 and opentelemetry_api
  Cargo.lock
  crates/hc_run_local_services/Cargo.toml
  crates/holochain/Cargo.toml
  crates/holochain_metrics/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/meta_net.rs
Labels: ShouldBackport/0.2
