Repository holochain/holochain, pull requests merged in 2023-04, with the labels that each got.

#2163 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2164 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2165 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2151 fix(github/release*): merge release into target branch before pushing
  .github/workflows/release-prepare.yml
  .github/workflows/release.yml
Labels: ShouldBackport

#2169 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2176 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2184 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2155 Fix bug with get dependants filtered caching its filter
  crates/release-automation/src/lib/crate_selection/mod.rs
  crates/release-automation/src/lib/crate_selection/tests/mod.rs
  crates/release-automation/src/lib/tests/workspace_mocker.rs
Labels: ShouldBackport/0.1

#2190 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2192 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2187 fix(github/workflows/release): increase chances of successful pushing of source branch
  .github/workflows/release.yml
Labels: ShouldBackport/0.1

#2197 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2198 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2200 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2201 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2202 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2204 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2205 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2213 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2214 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2220 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2227 docs(release): update screenshot and mention optional branch selection
  docs/release/release-holochain_1.png
  docs/release/release.md
Labels: autorebase:opt-in

#2230 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2231 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2221 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2235 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2237 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2238 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2239 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2240 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2241 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2242 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2245 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2244 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2246 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2250 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2254 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2256 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2258 update source 'versions/0_1' on branch 'develop'
  flake.lock
  nix/modules/scaffolding.nix
  versions/0_1/flake.lock
Labels: autorebase:opt-in

#2259 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2260 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2261 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2266 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2267 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2268 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2269 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2263 feat(nix/devShells/coreDev): remove holochain binaries
  nix/modules/devShells.nix
  nix/modules/holochain-crate2nix.nix
  nix/modules/holochain.nix
Labels: autorebase:opt-in

#2272 Set default semver increment mode
  .github/workflows/release-prepare.yml
  crates/fixt/CHANGELOG.md
  crates/fixt/test/CHANGELOG.md
  crates/hc/CHANGELOG.md
  crates/hc_bundle/CHANGELOG.md
  crates/hc_sandbox/CHANGELOG.md
  crates/hdi/CHANGELOG.md
  crates/hdk/CHANGELOG.md
  crates/hdk_derive/CHANGELOG.md
  crates/holo_hash/CHANGELOG.md
  crates/holochain/CHANGELOG.md
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_integrity_types/CHANGELOG.md
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_state/CHANGELOG.md
  crates/holochain_types/CHANGELOG.md
  crates/holochain_util/CHANGELOG.md
  crates/holochain_websocket/CHANGELOG.md
  crates/holochain_zome_types/CHANGELOG.md
  crates/kitsune_p2p/bootstrap/CHANGELOG.md
  crates/kitsune_p2p/dht/CHANGELOG.md
  crates/kitsune_p2p/dht_arc/CHANGELOG.md
  crates/kitsune_p2p/fetch/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/mdns/CHANGELOG.md
  crates/kitsune_p2p/proxy/CHANGELOG.md
  crates/kitsune_p2p/timestamp/CHANGELOG.md
  crates/kitsune_p2p/transport_quic/CHANGELOG.md
  crates/kitsune_p2p/types/CHANGELOG.md
  crates/mock_hdi/CHANGELOG.md
  crates/mr_bundle/CHANGELOG.md
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm_common/CHANGELOG.md
Labels: autorebase:opt-in

#2278 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2285 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2284 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2291 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2299 chore: configure 0.2.1-beta-dev.N release series
  .github/workflows/release-prepare.yml
  crates/fixt/CHANGELOG.md
  crates/fixt/test/CHANGELOG.md
  crates/hc/CHANGELOG.md
  crates/hc_bundle/CHANGELOG.md
  crates/hc_sandbox/CHANGELOG.md
  crates/hc_signal_srv/CHANGELOG.md
  crates/hdi/CHANGELOG.md
  crates/hdk/CHANGELOG.md
  crates/hdk_derive/CHANGELOG.md
  crates/holo_hash/CHANGELOG.md
  crates/holochain/CHANGELOG.md
  crates/holochain_cascade/CHANGELOG.md
  crates/holochain_conductor_api/CHANGELOG.md
  crates/holochain_integrity_types/CHANGELOG.md
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_p2p/CHANGELOG.md
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_state/CHANGELOG.md
  crates/holochain_trace/CHANGELOG.md
  crates/holochain_types/CHANGELOG.md
  crates/holochain_util/CHANGELOG.md
  crates/holochain_websocket/CHANGELOG.md
  crates/holochain_zome_types/CHANGELOG.md
  crates/kitsune_p2p/bin_data/CHANGELOG.md
  crates/kitsune_p2p/block/CHANGELOG.md
  crates/kitsune_p2p/bootstrap/CHANGELOG.md
  crates/kitsune_p2p/dht/CHANGELOG.md
  crates/kitsune_p2p/dht_arc/CHANGELOG.md
  crates/kitsune_p2p/fetch/CHANGELOG.md
  crates/kitsune_p2p/kitsune_p2p/CHANGELOG.md
  crates/kitsune_p2p/mdns/CHANGELOG.md
  crates/kitsune_p2p/proxy/CHANGELOG.md
  crates/kitsune_p2p/timestamp/CHANGELOG.md
  crates/kitsune_p2p/transport_quic/CHANGELOG.md
  crates/kitsune_p2p/types/CHANGELOG.md
  crates/mock_hdi/CHANGELOG.md
  crates/mr_bundle/CHANGELOG.md
  crates/test_utils/wasm/CHANGELOG.md
  crates/test_utils/wasm_common/CHANGELOG.md
  nix/modules/release-automation.nix
Labels: release

#2300 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2294 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in
