Repository holochain/holochain, pull requests merged in 2023-05, with the labels that each got.

#2281 Make holochain build without test utils and sweetest easier to consume
  .config/test-args.nix
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/builder.rs
  crates/holochain/src/conductor/p2p_agent_store.rs
  crates/holochain_diagnostics/Cargo.toml
Labels: autorebase:opt-in, ShouldBackport/0.1, ShouldBackport/0.2

#2301 Add a developer setup guide to the contributing guide
  CONTRIBUTING.md
  docs/core_testing.md
  docs/developer_setup.md
Labels: autorebase:opt-in

#2313 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2316 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2310 Fix flaky test `remote_signals`
  crates/holochain/tests/websocket/mod.rs
Labels: autorebase:opt-in, ShouldBackport/0.1, ShouldBackport/0.2

#2312 [BACKPORT 0.1] Make holochain build without test utils and sweetest easier to consume
  .config/test-args.nix
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/builder.rs
  crates/holochain/src/conductor/p2p_agent_store.rs
Labels: autorebase:opt-in

#2323 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2314 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2318 [BACKPORT 0.1] Fix flaky test `remote_signals` (#2310)
  crates/holochain/tests/websocket/mod.rs
Labels: autorebase:opt-in

#2317 [BACKPORT 0.2] Fix flaky test `remote_signals` (#2310)
  crates/holochain/tests/websocket/mod.rs
Labels: autorebase:opt-in

#2311 [BACKPORT 0.2] Make holochain build without test utils and sweetest easier to consum…
  .config/test-args.nix
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/builder.rs
  crates/holochain/src/conductor/p2p_agent_store.rs
  crates/holochain_diagnostics/Cargo.toml
Labels: autorebase:opt-in

#2324 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2325 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2328 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2327 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2331 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2333 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2335 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2338 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2280 Prevent zome calls when the network is not initialised
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/builder.rs
  crates/holochain/src/conductor/error.rs
  crates/holochain/src/core/ribosome/guest_callback/init.rs
Labels: autorebase:opt-in, ShouldBackport/0.2

#2345 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2341 Error earlier when databases do not become consistent
  crates/holochain/src/conductor/tests/network_info.rs
  crates/holochain/src/test_utils.rs
Labels: autorebase:opt-in

#2348 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2349 update source 'versions/0_1' on branch 'develop'
  flake.lock
  versions/0_1/flake.lock
Labels: autorebase:opt-in

#2337 harden lib loading against race conditions
  Cargo.lock
  Cargo.toml
  crates/hc_signal_srv/Cargo.toml
  crates/holochain/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: ShouldBackport/0.2

#2355 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2302 Support multiple action or entry types in query filters
  crates/holochain_state/src/source_chain.rs
  crates/holochain_zome_types/CHANGELOG.md
  crates/holochain_zome_types/src/query.rs
Labels: autorebase:opt-in

#2342 feat(nix): add shell with holochain binaries only
  CHANGELOG.md
  nix/modules/devShells.nix
Labels: autoupdate:opt-in

#2353 `hc signal-srv` is now `hc run-local-services`
  Cargo.lock
  Cargo.toml
  crates/hc/CHANGELOG.md
  crates/hc/Cargo.toml
  crates/hc/src/lib.rs
  crates/hc_run_local_services/CHANGELOG.md
  crates/hc_run_local_services/Cargo.toml
  crates/hc_run_local_services/README.md
  crates/hc_run_local_services/src/bin/hc-run-local-services.rs
  crates/hc_run_local_services/src/lib.rs
  crates/hc_signal_srv/src/lib.rs
Labels: ShouldBackport/0.2

#2358 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2350 [BACKPORT 0.2] Prevent zome calls when the network is not initialised (#2280)
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/builder.rs
  crates/holochain/src/conductor/error.rs
  crates/holochain/src/core/ribosome/guest_callback/init.rs
Labels: autorebase:opt-in

#2364 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2365 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2368 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2367 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2370 update source 'versions/0_2' on branch 'pr_holochain_bump'
  versions/0_2/flake.lock
Labels: autorebase:opt-in

#2373 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2374 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2376 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2375 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2378 update source 'versions/0_2' on branch 'develop'
  versions/0_2/flake.lock
Labels: autorebase:opt-in

#2377 Disable network_stats test on macos
  crates/holochain/tests/websocket/mod.rs
Labels: autorebase:opt-in

#2381 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2382 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2383 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2385 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2387 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2388 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2389 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2391 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2392 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2393 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2394 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2416 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2417 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2395 Correct fn name
  crates/test_utils/wasm/wasm_workspace/capability/src/coordinator.rs
Labels: autorebase:opt-in

#2420 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2411 Fix misleading error when holochain fails to launch
  crates/hc_sandbox/src/run.rs
Labels: autorebase:opt-in

#2429 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2428 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2361 Wait for gossip to start after starting a new conductor
  crates/hc_demo_cli/src/demo.rs
  crates/hc_demo_cli/src/test.rs
  crates/holochain/src/core/ribosome/host_fn/accept_countersigning_preflight_request.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow/tests.rs
  crates/holochain/src/sweettest/sweet_conductor.rs
  crates/holochain/src/sweettest/sweet_conductor_batch.rs
  crates/holochain/src/sweettest/sweet_conductor_config.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/tests/integration.rs
  crates/holochain/tests/sharded_gossip/mod.rs
  crates/holochain/tests/websocket/mod.rs
  crates/holochain_types/src/test_utils.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/initiate.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip/tests/test_two_nodes.rs
  crates/kitsune_p2p/kitsune_p2p/src/metrics.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/bootstrap.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/types/src/config.rs
Labels: autorebase:opt-in

#2431 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2434 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2435 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2437 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2439 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2339 Enable and fix sandbox tests
  crates/hc_sandbox/tests/cli.rs
Labels: autorebase:opt-in

#2440 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2441 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2442 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2447 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in
