Repository holochain/holochain, pull requests merged in 2023-08, with the labels that each got.

#2627 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2629 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2633 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2628 Extract bootstrap task and add tests
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space/bootstrap_task.rs
Labels: autorebase:opt-in, ShouldBackport/0.2

#2635 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2634 Prepare holochain_sqlite for loom testing
  Cargo.lock
  crates/holochain/src/conductor/kitsune_host_impl.rs
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_sqlite/loom_tests.sh
  crates/holochain_sqlite/src/db/access.rs
  crates/holochain_sqlite/src/db/kind.rs
  crates/holochain_sqlite/src/db/mod.rs
  crates/holochain_sqlite/src/functions.rs
  crates/holochain_sqlite/src/lib.rs
  crates/holochain_sqlite/src/prelude.rs
  crates/holochain_sqlite/src/store/p2p_agent_store.rs
  crates/holochain_sqlite/src/store/p2p_agent_store/p2p_test.rs
  crates/holochain_sqlite/src/store/p2p_metrics.rs
  crates/holochain_sqlite/src/store/p2p_metrics/p2p_metrics_test.rs
  crates/holochain_sqlite/tests/loom.rs
  crates/kitsune_p2p/kitsune_p2p/src/host_api.rs
  crates/kitsune_p2p/kitsune_p2p/src/metrics.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/event.rs
  crates/kitsune_p2p/timestamp/Cargo.toml
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/metrics.rs
Labels: autorebase:opt-in

#2632 tx5-metrics
  Cargo.lock
  Cargo.toml
  crates/holochain_metrics/Cargo.toml
  crates/holochain_metrics/src/dashboards/networkstats.json
  crates/holochain_metrics/src/dashboards/tx5.json
  crates/holochain_metrics/src/lib.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/meta_net.rs
Labels: NO-MERGE (dependency)

#2639 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2631 Extract meta net setup and test
  Cargo.lock
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space/agent_info_update.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/test_util/internal_stub.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/test_util/mod.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/test_util/space_internal_stub.rs
Labels: autorebase:opt-in

#2640 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2641 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2642 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2645 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2648 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2649 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2643 Update and extend fetch pool tests
  Cargo.lock
  crates/kitsune_p2p/fetch/CHANGELOG.md
  crates/kitsune_p2p/fetch/Cargo.toml
  crates/kitsune_p2p/fetch/src/pool.rs
  crates/kitsune_p2p/fetch/src/pool/pool_reader.rs
Labels: autorebase:opt-in, ShouldBackport/0.2

#2646 Remove unused fetch result
  Cargo.lock
  crates/kitsune_p2p/fetch/Cargo.toml
  crates/kitsune_p2p/fetch/src/error.rs
  crates/kitsune_p2p/fetch/src/lib.rs
Labels: autorebase:opt-in

#2647 update tx5 to include send buffer limiting work
  Cargo.lock
  Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
Labels: ShouldBackport/0.2

#2654 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2653 backport: fix cap grant lookup query
  crates/holochain_sqlite/src/sql/conductor/select_valid_cap_grant_for_cap_secret.sql
  crates/holochain_sqlite/src/sql/conductor/select_valid_unrestricted_cap_grant.sql
  crates/holochain_state/CHANGELOG.md
  crates/holochain_state/src/source_chain.rs
Labels: autorebase:opt-in

#2657 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2650 [BACKPORT 0.2] Extract bootstrap task
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space/bootstrap_task.rs
Labels: autorebase:opt-in

#2658 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2659 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2661 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2665 update source 'versions/0_1' on branch 'develop'
  flake.lock
  versions/0_1/flake.lock
Labels: autorebase:opt-in

#2666 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2671 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2667 update source 'versions/0_2' on branch 'develop'
  versions/0_2/flake.lock
Labels: autorebase:opt-in

#2655 Add more tests for fetch respond
  crates/kitsune_p2p/fetch/src/respond.rs
Labels: autorebase:opt-in, ShouldBackport/0.2

#2662 [0.1] Update lair version
  Cargo.lock
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain_keystore/CHANGELOG.md
  crates/holochain_keystore/Cargo.toml
  crates/holochain_keystore/src/crude_mock_keystore.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/types/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/agent_info/Cargo.toml
Labels: autorebase:opt-in

#2677 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2594 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#2684 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2686 update source 'crates-io' on branch 'develop'
  Cargo.lock
Labels: autorebase:opt-in

#2688 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#2690 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2695 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#2700 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#2702 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2656 Extract and test fetch pool fetch task
  crates/kitsune_p2p/fetch/src/lib.rs
  crates/kitsune_p2p/fetch/src/pool.rs
  crates/kitsune_p2p/fetch/src/pool/pool_reader.rs
  crates/kitsune_p2p/fetch/src/test_utils.rs
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/fetch.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/fetch/fetch_task.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/fetch/response_config.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/meta_net.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space/bootstrap_task.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/test_util/host_stub.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/test_util/internal_stub.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/test_util/mod.rs
Labels: autorebase:opt-in, ShouldBackport/0.2

#2704 Update weekly to beta-dev.15
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#2708 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2703 Add missing docs in hc sandbox
  crates/hc_sandbox/src/cli.rs
Labels: autorebase:opt-in

#2706 Expose pack and run local
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/src/cli.rs
  crates/hc_bundle/src/lib.rs
  crates/hc_run_local_services/CHANGELOG.md
  crates/hc_run_local_services/src/lib.rs
Labels: ShouldBackport/0.2

#2716 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2717 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2718 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2719 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#2720 feat(nix): add rust helper and pin crate2nix toolchain
  nix/modules/cargo-chef.nix
  nix/modules/cargo-rdme.nix
  nix/modules/holochain-crate2nix.nix
  nix/modules/holochain.nix
  nix/modules/lair.nix
  nix/modules/launcher.nix
  nix/modules/release-automation.nix
  nix/modules/rust.nix
  nix/modules/scaffolding.nix
Labels: autoupdate:opt-in, ShouldBackport/0.1, ShouldBackport/0.2

#2715 feat(github/workflows): nixify prepare scripts, add separate PR workflow that tests unbumped versions
  .github/actions/update/action.yml
  .github/workflows/build.yml
  .github/workflows/holochain-build-and-test.yml
  .github/workflows/pr_tests.yml
  .github/workflows/release-prepare.yml
  .github/workflows/release.yml
  flake.lock
  flake.nix
  nix/modules/holochain-nix-integration-test.nix
  nix/modules/release-automation.nix
  nix/modules/scripts.nix
  scripts/ci-git-config.sh
  scripts/generate_readmes.sh
Labels: ShouldBackport/0.1, ShouldBackport/0.2

#2729 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in
