Repository holochain/holochain, pull requests merged in 2024-11, with the labels that each got.

#4325 Put warrant issuance behind feature unstable-warrants
  .config/test-args.nix
  .github/workflows/test.yml
  Makefile
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/validation_receipt_workflow/tests.rs
  crates/holochain_cascade/Cargo.toml
  crates/holochain_cascade/src/authority/test.rs
  crates/holochain_cascade/tests/tests/get_activity.rs
  crates/holochain_state/Cargo.toml
  crates/holochain_state/src/mutations.rs
Labels: TargetRelease/0.4.0, ShouldBackport/0.4

#4415 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#4423 Update Holochain version in Holonix for weekly
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#4371 Put some hdk functions behind unstable flag
  .config/test-args.nix
  .github/workflows/test.yml
  Cargo.lock
  Makefile
  crates/hc_demo_cli/src/coordinator.wasm.gz
  crates/hc_demo_cli/src/integrity.wasm.gz
  crates/hc_sandbox/tests/cli.rs
  crates/hc_sandbox/tests/fixtures/my-app-deferred/dna/zomes/test_wasm_foo.wasm
  crates/hc_sandbox/tests/fixtures/my-app/dna/zomes/test_wasm_foo.wasm
  crates/hdi/Cargo.toml
  crates/hdi/src/agent.rs
  crates/hdi/src/hdi.rs
  crates/hdi/src/prelude.rs
  crates/hdi/src/test_utils.rs
  crates/hdk/Cargo.toml
  crates/hdk/src/agent.rs
  crates/hdk/src/countersigning.rs
  crates/hdk/src/hdk.rs
  crates/hdk/src/prelude.rs
  crates/hdk/src/time.rs
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain/src/conductor/conductor/tests/agent_lineage.rs
  crates/holochain/src/core/ribosome/host_fn.rs
  crates/holochain/src/core/ribosome/host_fn/block_agent.rs
  crates/holochain/src/core/ribosome/host_fn/get_agent_key_lineage.rs
  crates/holochain/src/core/ribosome/real_ribosome.rs
  crates/holochain/tests/tests/countersigning.rs
  crates/holochain_zome_types/Cargo.toml
  crates/holochain_zome_types/src/zome_io.rs
  crates/mock_hdi/Cargo.toml
  crates/mock_hdi/src/lib.rs
  crates/test_utils/wasm/Cargo.toml
  crates/test_utils/wasm/build.rs
  crates/test_utils/wasm/wasm_workspace/agent_key_lineage/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/capability/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/capability/src/coordinator.rs
  crates/test_utils/wasm/wasm_workspace/clone/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/countersigning/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/create_entry/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/create_entry/src/coordinator.rs
  crates/test_utils/wasm/wasm_workspace/schedule/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/schedule/src/coordinator.rs
Labels: TargetRelease/0.4.0, ShouldBackport/0.4

#4431 Countersigning should always progress from an unknown state
  crates/holochain/CHANGELOG.md
  crates/holochain/src/core/workflow/countersigning_workflow.rs
  crates/holochain/src/core/workflow/countersigning_workflow/tests.rs
  crates/holochain/tests/tests/countersigning.rs
  crates/holochain/tests/tests/countersigning/session_interaction_over_websocket.rs
Labels: ShouldBackport/0.4

#4229 White paper
  .gitignore
  docs/build_tutorial.md
  docs/cell/agent/call_zome_fn.rs
  docs/specs/src/.gitignore
  docs/specs/src/README.md
  docs/specs/src/_hwp_B_additional_specs.md
  docs/specs/src/_hwp_C_countersigning_spec.md
  docs/specs/src/_hwp_D_rate_limiting_spec.md
  docs/specs/src/build.sh
  docs/specs/src/create_link_ops.svg
  docs/specs/src/create_ops.svg
  docs/specs/src/delete_link_ops.svg
  docs/specs/src/delete_ops.svg
  docs/specs/src/diagram-1.0.0/LICENSE
  docs/specs/src/diagram-1.0.0/Makefile
  docs/specs/src/diagram-1.0.0/README.md
  docs/specs/src/diagram-1.0.0/_extensions/diagram/_extension.yaml
  docs/specs/src/diagram-1.0.0/_extensions/diagram/diagram.lua
  docs/specs/src/diagram-1.0.0/diagram.lua
  docs/specs/src/holochain-players-of-ludos.md
  docs/specs/src/holochain-white-paper-alpha.tex
  docs/specs/src/hwp_1_intro.md
  docs/specs/src/hwp_2_overview.md
  docs/specs/src/hwp_3_correctness.md
  docs/specs/src/hwp_4_formal.md
  docs/specs/src/hwp_5_conclusion.md
  docs/specs/src/hwp_A_implementation_spec.md
  docs/specs/src/pandoc-template.latex
  docs/specs/src/update_ops.svg
  docs/specs/src/workflows.png
  docs/template.rs
Labels: documentation

#4432 chore: Update Nix inputs
  flake.lock
  flake.nix
  nix/modules/go.nix
  nix/modules/rust.nix
Labels: autorebase:opt-in

#4439 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4438 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4443 fix: url format panic
  crates/kitsune_p2p/types/src/tx_utils/proxy_url.rs
Labels: ShouldBackport/0.4

#4460 Update Holochain version in Holonix for weekly
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#4456 bump tx5 and sbd versions
  Cargo.lock
  crates/hc_run_local_services/Cargo.toml
  crates/hc_service_check/Cargo.toml
  crates/holochain/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
Labels: ShouldBackport/0.3, ShouldBackport/0.4

#4475 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4476 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4487 Change UseExisting enum variant format
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/tests/install_app_bundle.rs
  crates/holochain_types/src/app.rs
Labels: ShouldBackport/0.4

#4491 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4492 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4498 Update Holochain version in Holonix for 0_4_rc
  versions/0_4_rc/flake.lock
  versions/0_4_rc/flake.nix
Labels: autorebase:opt-in

#4499 Update Holochain version in Holonix for weekly
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#4502 Upgrade Lair and sysinfo
  Cargo.lock
  crates/holochain/Cargo.toml
  crates/holochain_keystore/Cargo.toml
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/metrics.rs
Labels: ShouldBackport/0.4

#4504 Update Holochain version in Holonix for 0_4_rc
  versions/0_4_rc/flake.lock
  versions/0_4_rc/flake.nix
Labels: autorebase:opt-in

#4506 Update Holochain version in Holonix for 0_3_rc
  versions/0_3_rc/flake.lock
  versions/0_3_rc/flake.nix
Labels: autorebase:opt-in
