Repository holochain/holochain, pull requests merged in 2024-12, with the labels that each got.

#4510 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4511 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4512 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#4515 Update Holochain version in Holonix for 0_3
  flake.lock
  versions/0_3/flake.lock
  versions/0_3/flake.nix
Labels: autorebase:opt-in

#4517 Update Holochain version in Holonix for 0_4_rc
  versions/0_4_rc/flake.lock
Labels: autorebase:opt-in

#4525 Update Holochain version in Holonix for 0_3
  flake.lock
  versions/0_3/flake.lock
Labels: autorebase:opt-in

#4528 Update Holochain version in Holonix for 0_3
  flake.lock
Labels: autorebase:opt-in

#4530 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4531 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#4533 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#4532 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4535 Update Holochain version in Holonix for weekly
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#4550 Fix `holochain_cli_sandbox` doc warnings
  crates/hc_sandbox/src/calls.rs
  crates/hc_sandbox/src/cli.rs
  crates/hc_sandbox/src/config.rs
Labels: autorebase:opt-in

#4553 docs(holochain): fix doc comment links
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/manager/mod.rs
Labels: autorebase:opt-in

#4552 docs: fix doc comment link to render fn
  crates/holochain_terminal/src/tui.rs
Labels: autorebase:opt-in

#4558 state doc fix
  crates/holochain_state/src/mutations.rs
  crates/holochain_state/src/validation_receipts.rs
Labels: autorebase:opt-in

#4557 chc doc fix
  crates/holochain_chc/src/lib.rs
Labels: autorebase:opt-in

#4560 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4561 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4562 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#4563 docs(holochain-types): fix warnings
  crates/holochain_types/src/app.rs
  crates/holochain_types/src/app/app_manifest/app_manifest_v1.rs
  crates/holochain_types/src/countersigning.rs
Labels: autorebase:opt-in

#4559 ci(test): reject warnings from cargo doc
  Makefile
Labels: autorebase:opt-in

#4571 build(holo-hash): update proptest-derive
  Cargo.lock
Labels: autorebase:opt-in

#4565 docs: add release test log
  RELEASE_TEST_LOG.md
Labels: autorebase:opt-in, autorebase:non-rebaseable

#4566 Update Holochain version in Holonix for weekly
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#4573 Prevent duplicate calls to `init`
  crates/holochain/CHANGELOG.md
  crates/holochain/src/conductor/cell.rs
  crates/holochain/tests/tests/init.rs
  crates/test_utils/wasm/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/init_single/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/init_single/src/integrity.rs
  crates/test_utils/wasm/wasm_workspace/init_single/src/lib.rs
Labels: ShouldBackport/0.3, ShouldBackport/0.4

#4576 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4577 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4578 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#4584 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#4586 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#4585 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4583 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in
