Repository holochain/holochain, pull requests merged in 2024-07, with the labels that each got.

#4055 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#4053 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4054 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#4061 Update Holochain version in Holonix for weekly
  crates/hc/Cargo.toml
  crates/hc_sandbox/Cargo.toml
  crates/holochain_types/Cargo.toml
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#4073 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#4072 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3985 Keep ignore_genesis_failure regardless of features
  crates/hc_sandbox/examples/setup_5.rs
  crates/hc_sandbox/src/calls.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/tests.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/conductor/tests/install_app_bundle.rs
  crates/holochain/src/sweettest/sweet_app_installation.rs
  crates/holochain/tests/tests/test_utils/mod.rs
  crates/holochain_types/src/app.rs
Labels: permanent

#4076 Update Holochain version in Holonix for weekly
  crates/fixt/test/Cargo.toml
  crates/hc/Cargo.toml
  crates/hc_sandbox/Cargo.toml
  crates/holochain_keystore/Cargo.toml
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_types/Cargo.toml
  crates/kitsune_p2p/bootstrap/Cargo.toml
  crates/kitsune_p2p/bootstrap_client/Cargo.toml
  crates/kitsune_p2p/kitsune_p2p/Cargo.toml
  crates/kitsune_p2p/proxy/Cargo.toml
  crates/test_utils/wasm/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/migrate_initial/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/migrate_new/Cargo.toml
  crates/test_utils/wasm_common/Cargo.toml
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#4049 Expose validation receipt info for actions
  crates/hdk/CHANGELOG.md
  crates/hdk/src/hdk.rs
  crates/hdk/src/lib.rs
  crates/hdk/src/link/builder.rs
  crates/hdk/src/prelude.rs
  crates/hdk/src/validation_receipt.rs
  crates/holo_hash/src/fixt.rs
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/core/ribosome/host_fn.rs
  crates/holochain/src/core/ribosome/host_fn/get_validation_receipts.rs
  crates/holochain/src/core/ribosome/real_ribosome.rs
  crates/holochain/tests/tests/publish/mod.rs
  crates/holochain_sqlite/src/sql/cell/schema/0.sql
  crates/holochain_state/src/validation_receipts.rs
  crates/holochain_zome_types/src/validate.rs
  crates/holochain_zome_types/src/zome_io.rs
  crates/test_utils/wasm/wasm_workspace/create_entry/src/coordinator.rs
Labels: ShouldBackport/0.3

#4070 Shorten database file names
  crates/holochain/src/conductor/conductor.rs
  crates/holochain_sqlite/CHANGELOG.md
  crates/holochain_sqlite/src/db/access.rs
  crates/holochain_sqlite/src/db/kind.rs
  crates/holochain_sqlite/tests/tests/migrate_unencrypted.rs
Labels: ShouldBackport/0.3

#4087 Update Holochain version in Holonix for 0_3
  versions/0_3/flake.lock
Labels: autorebase:opt-in

#4096 Update Holochain version in Holonix for 0_3_rc
  versions/0_3_rc/flake.lock
  versions/0_3_rc/flake.nix
Labels: autorebase:opt-in

#4092 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#4090 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4093 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#4100 Update Holochain version in Holonix for weekly
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#4104 Update Holochain version in Holonix for 0_3
  versions/0_3/flake.lock
Labels: autorebase:opt-in

#4108 Update Holochain version in Holonix for 0_3_rc
  flake.lock
  nix/modules/cargo-chef.nix
  nix/modules/cargo-rdme.nix
  nix/modules/holochain.nix
  nix/modules/holonix-integration-test.nix
  nix/modules/lair.nix
  nix/modules/launcher.nix
  nix/modules/release-automation.nix
  nix/modules/scaffolding.nix
  versions/0_2_rc/flake.lock
  versions/0_3/flake.lock
  versions/0_3_rc/flake.lock
  versions/0_3_rc/flake.nix
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#4120 Update Holochain version in Holonix for weekly
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#4136 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#4135 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4091 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4129 Missing deps should be retryable for countersigning
  crates/holochain/CHANGELOG.md
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/core/validation.rs
  crates/holochain/src/core/workflow/call_zome_workflow.rs
  crates/holochain/src/sweettest/sweet_conductor.rs
  crates/holochain/tests/tests/countersigning.rs
  crates/holochain_state/src/source_chain/error.rs
Labels: autorebase:opt-in

#4149 Update Holochain version in Holonix for weekly
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#4147 Update Holochain version in Holonix for 0_3
  flake.lock
  versions/0_3/flake.lock
  versions/0_3/flake.nix
Labels: autorebase:opt-in
