Repository holochain/holochain, pull requests merged in 2024-04, with the labels that each got.

#3528 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3530 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3543 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3542 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3546 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3553 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3551 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3555 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3563 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3565 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3568 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3566 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3570 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3569 update source 'crates-io' on branch 'develop'
  Cargo.lock
Labels: autorebase:opt-in

#3575 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3573 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3578 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3579 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3580 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3582 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3577 Do not assume host IP stack for websocket listeners
  crates/hc_sandbox/src/ports.rs
  crates/hc_sandbox/tests/cli.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/sweettest/sweet_conductor.rs
  crates/holochain/tests/send_signal.rs
  crates/holochain/tests/websocket/mod.rs
  crates/holochain_websocket/benches/bench.rs
  crates/holochain_websocket/benches/full_connect.rs
Labels: ShouldBackport/0.2

#3588 update source 'versions/0_2' on branch 'develop'
  versions/0_2/flake.lock
Labels: autorebase:opt-in

#3589 update source 'versions/0_2_rc' on branch 'develop'
  versions/0_2_rc/flake.lock
Labels: autorebase:opt-in

#3591 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3592 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3594 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3601 update source 'crates-io' on branch 'develop'
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3600 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3607 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3608 update source 'crates-io' on branch 'develop'
  Cargo.lock
Labels: autorebase:opt-in

#3614 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3617 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3619 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3620 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3624 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3625 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3628 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3626 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3630 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3631 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3632 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3633 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3634 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3635 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3636 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3637 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3645 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3646 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3650 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3652 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3654 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3653 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3656 update source 'crates-io' on branch 'develop'
  Cargo.lock
Labels: autorebase:opt-in

#3655 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3661 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3666 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3665 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3669 update source 'crates-io' on branch 'develop'
  Cargo.lock
Labels: autorebase:opt-in

#3672 update source 'versions/0_2' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3674 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3675 update source 'crates-io' on branch 'develop'
  Cargo.lock
Labels: autorebase:opt-in

#3676 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3677 update source 'crates-io' on branch 'develop'
  Cargo.lock
Labels: autorebase:opt-in

#3681 update source 'crates-io' on branch 'develop'
  Cargo.lock
Labels: autorebase:opt-in

#3686 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3685 update source 'crates-io' on branch 'develop'
  Cargo.lock
Labels: autorebase:opt-in

#3687 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3689 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3692 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3690 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3693 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3694 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3688 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3697 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3678 Listen on either stack for websocket connections
  Cargo.lock
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/tests/websocket/mod.rs
  crates/holochain_websocket/Cargo.toml
  crates/holochain_websocket/benches/bench.rs
  crates/holochain_websocket/benches/full_connect.rs
  crates/holochain_websocket/src/lib.rs
  crates/holochain_websocket/src/test.rs
Labels: ShouldBackport/0.2

#3714 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3715 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3722 Update Holochain version in Holonix for 0_2_rc
  versions/0_2_rc/flake.lock
  versions/0_2_rc/flake.nix
Labels: autorebase:opt-in

#3716 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3725 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3731 Fix rebinding the same port
  crates/holochain_websocket/src/lib.rs
  crates/holochain_websocket/src/test.rs
Labels: ShouldBackport/0.2

#3733 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3730 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3734 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3738 Update Holochain version in Holonix for 0_2_rc
  versions/0_2_rc/flake.lock
  versions/0_2_rc/flake.nix
Labels: autorebase:opt-in

#3737 update source 'crates-io' on branch 'develop'
  Cargo.lock
Labels: autorebase:opt-in

#3752 update source 'versions/0_2' on branch 'develop'
  flake.lock
  versions/0_2/flake.lock
Labels: autorebase:opt-in

#3751 update source 'versions/0_2_rc' on branch 'develop'
  versions/0_2_rc/flake.lock
Labels: autorebase:opt-in

#3438 SQL query review and cleanup
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
Labels: HOLO LAUNCH

#3756 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3758 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3763 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3762 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3765 Revoke app ws auth tokens
  crates/holochain/CHANGELOG.md
  crates/holochain/src/conductor/api/api_external/admin_interface.rs
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/src/conductor/conductor/app_auth_token_store.rs
  crates/holochain/tests/app_interface_security.rs
  crates/holochain/tests/websocket/mod.rs
  crates/holochain_conductor_api/src/admin_interface.rs
Labels: TargetRelease/0.3.0

#3767 Update Holochain version in Holonix for weekly
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#3766 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3757 build!: update serialization to v0.0.54
  Cargo.lock
  crates/fixt/Cargo.toml
  crates/hc_bundle/Cargo.toml
  crates/hc_demo_cli/src/coordinator.wasm.gz
  crates/hc_demo_cli/src/integrity.wasm.gz
  crates/hdi/Cargo.toml
  crates/hdk/Cargo.toml
  crates/holo_hash/Cargo.toml
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/src/core/ribosome/host_fn/create.rs
  crates/holochain_cascade/Cargo.toml
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_conductor_api/src/admin_interface.rs
  crates/holochain_conductor_api/src/app_interface.rs
  crates/holochain_integrity_types/Cargo.toml
  crates/holochain_keystore/Cargo.toml
  crates/holochain_p2p/Cargo.toml
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_state/Cargo.toml
  crates/holochain_types/Cargo.toml
  crates/holochain_websocket/Cargo.toml
  crates/holochain_zome_types/Cargo.toml
  crates/kitsune_p2p/dht/Cargo.toml
  crates/kitsune_p2p/fetch/Cargo.toml
  crates/kitsune_p2p/timestamp/Cargo.toml
  crates/kitsune_p2p/types/Cargo.toml
  crates/kitsune_p2p/types/src/codec.rs
  crates/mr_bundle/Cargo.toml
  crates/mr_bundle/src/encoding.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: TargetRelease/0.3.0

#3772 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3771 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3773 update source 'crates-io' on branch 'develop'
  Cargo.lock
Labels: autorebase:opt-in

#3774 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3775 update source 'crates-io' on branch 'develop'
  Cargo.lock
Labels: autorebase:opt-in

#3776 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3777 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3779 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3780 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3783 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3784 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3787 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3788 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3790 Update Holochain version in Holonix for 0_2
  flake.lock
  versions/0_2/flake.lock
  versions/0_2/flake.nix
Labels: autorebase:opt-in

#3793 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in
