Repository holochain/holochain, pull requests merged in 2024-05, with the labels that each got.

#3796 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3797 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3800 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3801 update source 'versions/0_3_rc' on branch 'develop'
  versions/0_3_rc/flake.lock
Labels: autorebase:opt-in

#3798 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3795 refactor(types): remove unused type DhtOpOrder
  crates/holochain/CHANGELOG.md
  crates/holochain/src/core/validation.rs
  crates/holochain/src/core/workflow/sys_validation_workflow.rs
  crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs
Labels: housekeeping

#3806 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3810 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3812 update source 'versions/0_2_rc' on branch 'develop'
  versions/0_2_rc/flake.lock
Labels: autorebase:opt-in

#3813 update source 'versions/0_2' on branch 'develop'
  flake.lock
  versions/0_2/flake.lock
Labels: autorebase:opt-in

#3817 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3811 Update actions to latest versions
  .github/actions/update/action.yml
  .github/workflows/holonix-cache.yml
  .github/workflows/release-prepare.yml
  .github/workflows/release.yml
  .github/workflows/ssh-session.yml
  .github/workflows/stale.yml
Labels: autorebase:opt-in

#3818 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3821 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3819 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3814 Clean up websocket connections
  crates/holochain/src/conductor/interface/websocket.rs
  crates/holochain/tests/websocket/mod.rs
  crates/holochain_websocket/src/test.rs
Labels: ShouldBackport/0.2, ShouldBackport/0.3

#3828 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3831 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3833 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3832 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3839 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3843 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3837 Update Holochain version in Holonix for weekly
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#3851 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3852 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3820 better to use the repository field to link to the repository
  crates/holochain/Cargo.toml
Labels: autorebase:opt-in

#3853 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3854 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3856 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3840 fix(app-validation-wf): remove ops to filter when multiple ops missing same hash 0.3
  crates/holochain/CHANGELOG.md
  crates/holochain/src/core/workflow/app_validation_workflow.rs
  crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/unit_tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs
  crates/holochain/src/test_utils.rs
  crates/holochain/tests/regression/must_get_agent_activity_saturation.rs
  crates/holochain_trace/src/lib.rs
  crates/test_utils/wasm/src/lib.rs
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/app_validation/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/app_validation/src/coordinator.rs
  crates/test_utils/wasm/wasm_workspace/app_validation/src/integrity.rs
  crates/test_utils/wasm/wasm_workspace/app_validation/src/lib.rs
Labels: TargetRelease/0.3.0

#3862 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3858 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3869 Update Holochain version in Holonix for weekly
  crates/hc/Cargo.toml
  crates/hc_sandbox/Cargo.toml
  crates/holochain_keystore/Cargo.toml
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_types/Cargo.toml
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#3868 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3871 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3872 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3873 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3807 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3880 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3881 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
Labels: autorebase:opt-in

#3882 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3888 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3889 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3890 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3891 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3879 Update Holochain version in Holonix for 0_3_rc
  versions/0_3_rc/flake.lock
  versions/0_3_rc/flake.nix
Labels: autorebase:opt-in

#3896 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3887 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3898 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3905 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3906 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3903 update source 'crates-io' on branch 'develop'
  Cargo.lock
Labels: autorebase:opt-in

#3895 Tests for sharded publish
  crates/holochain/src/conductor/conductor.rs
  crates/holochain/tests/dht_arc/mod.rs
  crates/kitsune_p2p/dht/src/arq.rs
  crates/kitsune_p2p/dht/src/arq/strat.rs
  crates/kitsune_p2p/dht/src/spacetime/quantum.rs
  crates/kitsune_p2p/dht/src/spacetime/segment.rs
  crates/kitsune_p2p/dht/src/spacetime/topology.rs
  crates/kitsune_p2p/dht_arc/src/dht_arc.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/discover.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/tests/common/data.rs
  crates/kitsune_p2p/kitsune_p2p/tests/common/test_legacy_host.rs
  crates/kitsune_p2p/kitsune_p2p/tests/sharding.rs
  crates/kitsune_p2p/types/src/config.rs
Labels: autorebase:opt-in

#3912 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3907 Bump wasmer to 0.0.94
  Cargo.lock
  crates/hc_bundle/Cargo.toml
  crates/hdi/Cargo.toml
  crates/hdk/Cargo.toml
  crates/holo_hash/Cargo.toml
  crates/holochain/Cargo.toml
  crates/holochain_zome_types/Cargo.toml
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3913 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3908 Update Holochain version in Holonix for 0_3_rc
  versions/0_3_rc/flake.lock
Labels: autorebase:opt-in

#3914 Update Holochain version in Holonix for weekly
  crates/hc/Cargo.toml
  crates/hc_sandbox/Cargo.toml
  crates/holochain_keystore/Cargo.toml
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_types/Cargo.toml
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#3916 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3922 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#3924 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3925 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3926 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3929 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3936 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3937 Update Holochain version in Holonix for weekly
  crates/hc/Cargo.toml
  crates/hc_sandbox/Cargo.toml
  crates/holochain_keystore/Cargo.toml
  crates/holochain_sqlite/Cargo.toml
  crates/holochain_types/Cargo.toml
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#3942 Update Holochain version in Holonix for 0_3_rc
  versions/0_3_rc/flake.lock
Labels: autorebase:opt-in

#3923 update source 'crates-io' on branch 'develop'
  Cargo.lock
  crates/release-automation/Cargo.lock
  crates/test_utils/wasm/wasm_workspace/Cargo.lock
Labels: autorebase:opt-in

#3941 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#3946 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in
