Repository holochain/holochain, pull requests merged in 2024-10, with the labels that each got.

#4320 update source 'rust-overlay' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4321 update source 'nixpkgs' on branch 'develop'
  flake.lock
Labels: autorebase:opt-in

#4351 Update Holochain version in Holonix for weekly
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#4301 Plumb in transfer info for DHT DB
  Cargo.lock
  crates/holochain/src/conductor/cell.rs
  crates/holochain/src/core/ribosome/host_fn/must_get_agent_activity.rs
  crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs
  crates/holochain/src/core/workflow/app_validation_workflow/tests.rs
  crates/holochain/src/core/workflow/incoming_dht_ops_workflow.rs
  crates/holochain_cascade/src/lib.rs
  crates/holochain_p2p/src/spawn/actor.rs
  crates/holochain_sqlite/src/sql/cell/schema/4-up.sql
  crates/holochain_state/Cargo.toml
  crates/holochain_state/src/mutations.rs
  crates/holochain_state/src/source_chain.rs
  crates/kitsune_p2p/fetch/Cargo.toml
  crates/kitsune_p2p/fetch/src/lib.rs
  crates/kitsune_p2p/fetch/src/pool.rs
  crates/kitsune_p2p/fetch/src/test_utils.rs
  crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip.rs
  crates/kitsune_p2p/kitsune_p2p/src/metrics.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/meta_net/tests.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/meta_net_task.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space/bootstrap_task.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/test_util/internal_stub.rs
  crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/test_util/space_internal_stub.rs
  crates/kitsune_p2p/kitsune_p2p/src/types/actor.rs
  crates/kitsune_p2p/kitsune_p2p/tests/performance.rs
  crates/kitsune_p2p/kitsune_p2p/tests/sharding.rs
  crates/kitsune_p2p/kitsune_p2p/tests/tests.rs
  crates/kitsune_p2p/types/src/fetch_pool.rs
  crates/kitsune_p2p/types/src/lib.rs
Labels: ShouldBackport/0.4

#4338 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in, autorebase:non-rebaseable

#4361 Update Holochain version in Holonix for weekly
  versions/weekly/flake.lock
  versions/weekly/flake.nix
Labels: autorebase:opt-in

#4376 Deprecate precompiled wasm bundling for ios
  crates/hc_bundle/CHANGELOG.md
  crates/hc_bundle/src/cli.rs
  crates/hc_bundle/src/packing.rs
  crates/hc_bundle/src/packing/wasmer_sys.rs
  crates/holochain/CHANGELOG.md
  crates/holochain/src/core/ribosome/real_ribosome/wasmer_sys.rs
  crates/holochain_types/CHANGELOG.md
  crates/holochain_types/src/dna/dna_manifest/dna_manifest_v1.rs
  crates/holochain_zome_types/CHANGELOG.md
  crates/holochain_zome_types/src/zome.rs
Labels: ShouldBackport/0.4

#4384 update source 'versions/weekly' on branch 'develop'
  versions/weekly/flake.lock
Labels: autorebase:opt-in

#4342 Disable DPKI by default & introduce unstable-dpki feature
  .config/test-args.nix
  .github/workflows/test.yml
  Cargo.lock
  Makefile
  crates/hc_sandbox/Cargo.toml
  crates/hc_sandbox/examples/setup_5.rs
  crates/hc_sandbox/src/cli.rs
  crates/hc_sandbox/src/cmds.rs
  crates/hc_sandbox/src/config.rs
  crates/hc_sandbox/src/generate.rs
  crates/hc_sandbox/src/sandbox.rs
  crates/hc_sandbox/tests/cli.rs
  crates/holochain/CHANGELOG.md
  crates/holochain/Cargo.toml
  crates/holochain/src/conductor/conductor/tests/agent_key_revocation.rs
  crates/holochain/src/conductor/conductor/tests/agent_lineage.rs
  crates/holochain/src/core/sys_validate/tests.rs
  crates/holochain/tests/tests/mod.rs
  crates/holochain_conductor_api/Cargo.toml
  crates/holochain_conductor_api/src/config/conductor.rs
  crates/holochain_conductor_api/src/config/conductor/dpki_config.rs
Labels: TargetRelease/0.4.0, ShouldBackport/0.4
